import type { MCQuestion } from "./questions";

export const surgeryQuestions: MCQuestion[] = [
  {
    id: "surg-001", topic: "Surgery", subtopic: "Appendicitis",
    stem: "A 25-year-old man has right iliac fossa pain, fever 38.2°C, and WBC 15.5. Alvarado score is 8. CT shows periappendiceal fat stranding with a dilated (8 mm) non-perfused appendix. What is the most appropriate management?",
    options: [
      { label: "A", text: "IV antibiotics alone (non-operative management)" },
      { label: "B", text: "Urgent laparoscopic appendicectomy" },
      { label: "C", text: "CT-guided drainage of appendix abscess" },
      { label: "D", text: "Open appendicectomy" },
      { label: "E", text: "Watchful waiting with serial examinations" },
    ],
    correctAnswer: "B",
    explanation: "Acute appendicitis (Alvarado ≥7 = probable appendicitis, CT confirms non-perforated): laparoscopic appendicectomy is gold standard. Less pain, faster recovery, fewer wound complications vs open. IV antibiotics alone (non-operative): RCTs show feasible for uncomplicated appendicitis in selected patients but 30% fail within 1 year and need surgery. Perforation + abscess: IV antibiotics + CT-guided drainage, interval appendicectomy 6-8 weeks later.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "surg-002", topic: "Surgery", subtopic: "Hernia",
    stem: "A 55-year-old man has a right inguinal hernia that is irreducible and tender after 6 hours. He is nauseated and unable to pass flatus. What is the complication and management?",
    options: [
      { label: "A", text: "Incarcerated hernia — attempt manual reduction then elective repair" },
      { label: "B", text: "Strangulated hernia — emergency surgery" },
      { label: "C", text: "Irreducible hernia — elective repair within 2 weeks" },
      { label: "D", text: "Incarcerated hernia — IV antibiotics and observation" },
      { label: "E", text: "Ventral hernia — urgent CT scan" },
    ],
    correctAnswer: "B",
    explanation: "Strangulated hernia: irreducible + signs of ischaemia (tender, fever, bowel obstruction, absent bowel sounds). Blood supply to herniated contents is compromised → bowel necrosis within hours. Emergency surgery: reduce hernia, assess bowel viability, resect if necrotic. Incarcerated (irreducible but viable): urgent repair within hours. Elective repair only for reducible hernias.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "surg-003", topic: "Surgery", subtopic: "Bowel Obstruction",
    stem: "A 65-year-old woman with previous hysterectomy presents with colicky abdominal pain, distension, vomiting, and obstipation. AXR shows dilated small bowel loops with multiple air-fluid levels. What is the most likely cause and initial management?",
    options: [
      { label: "A", text: "Colonic volvulus — endoscopic decompression" },
      { label: "B", text: "Adhesive small bowel obstruction — IV fluids, NG tube, surgical review" },
      { label: "C", text: "Intussusception — air enema reduction" },
      { label: "D", text: "Gallstone ileus — emergency surgery" },
      { label: "E", text: "Crohn's stricture — steroids" },
    ],
    correctAnswer: "B",
    explanation: "Small bowel obstruction from adhesions (most common cause post-abdominal surgery): conservative management initially — NG decompression ('drip and suck'), IV fluids, strict NBM, serial abdominal examination. 60–80% resolve without surgery. Surgery if: strangulation (peritonitis, fever, ↑WBC, closed-loop obstruction), failure to resolve within 48–72h. CT abdomen: 'transition point' identifies level of obstruction and rules out strangulation.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "surg-004", topic: "Surgery", subtopic: "Colorectal Cancer",
    stem: "A 60-year-old man has a colonoscopy-confirmed sigmoid colon cancer. CT staging: T3 N1 M0 (Stage IIIB). He is fit for surgery. What is the treatment plan?",
    options: [
      { label: "A", text: "Surgery alone — no adjuvant therapy needed" },
      { label: "B", text: "Neoadjuvant chemoradiotherapy then surgery" },
      { label: "C", text: "Resection (sigmoid colectomy) + adjuvant FOLFOX chemotherapy × 6 months" },
      { label: "D", text: "Palliative chemotherapy — Stage III not curable" },
      { label: "E", text: "Radiotherapy alone" },
    ],
    correctAnswer: "C",
    explanation: "Stage III colon cancer (lymph node involvement, no distant metastases): curative surgery (sigmoid colectomy + regional lymph node dissection) + adjuvant chemotherapy (FOLFOX: oxaliplatin + 5-FU/leucovorin × 12 cycles). Adjuvant chemo reduces recurrence by 20-30% in Stage III. Neoadjuvant chemoradiotherapy for RECTAL cancer (not colon). 5-year survival ~70% for Stage III with treatment.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "surg-005", topic: "Surgery", subtopic: "Thyroid",
    stem: "A 35-year-old woman has a 2 cm right thyroid nodule. FNAC reports Bethesda Category IV (follicular neoplasm). TSH is normal. What is the next most appropriate management?",
    options: [
      { label: "A", text: "Repeat FNAC in 6 months" },
      { label: "B", text: "Diagnostic hemithyroidectomy (right thyroid lobectomy)" },
      { label: "C", text: "Total thyroidectomy immediately" },
      { label: "D", text: "Radioactive iodine ablation" },
      { label: "E", text: "Levothyroxine suppression therapy" },
    ],
    correctAnswer: "B",
    explanation: "Bethesda IV (follicular neoplasm): FNA cannot distinguish follicular adenoma (benign) from follicular carcinoma (malignant) — requires histological assessment of capsular/vascular invasion. Management: diagnostic hemithyroidectomy (lobectomy). If final pathology shows follicular carcinoma: completion thyroidectomy. Bethesda V-VI (suspicious/malignant): total thyroidectomy. Bethesda II (benign): surveillance.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "surg-006", topic: "Surgery", subtopic: "Breast",
    stem: "A 52-year-old woman has a 15 mm, grade 2 invasive ductal carcinoma, ER+/PR+, HER2-. Sentinel lymph node biopsy is negative. She wants to preserve her breast if possible. What is the most appropriate surgical management?",
    options: [
      { label: "A", text: "Mastectomy — superior to conservation for all tumours" },
      { label: "B", text: "Breast-conserving surgery (WLE/lumpectomy) + adjuvant radiotherapy" },
      { label: "C", text: "Wide local excision alone — no radiotherapy needed for small tumours" },
      { label: "D", text: "Neoadjuvant chemotherapy before any surgery" },
      { label: "E", text: "Axillary lymph node clearance for all cases" },
    ],
    correctAnswer: "B",
    explanation: "Early breast cancer (T1N0): breast-conserving surgery (wide local excision) + whole breast radiotherapy is oncologically equivalent to mastectomy (multiple RCTs). WLE without RT has 3× higher local recurrence. Patient preferences for BCS should be respected if margins achievable. Hormone therapy (tamoxifen/aromatase inhibitor) for ER+ tumours. Negative sentinel node biopsy: no further axillary dissection needed.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "surg-007", topic: "Surgery", subtopic: "Abdominal Trauma",
    stem: "A 30-year-old man was stabbed in the left upper quadrant. BP 85/55, HR 135. Focused Assessment with Sonography in Trauma (FAST) shows free fluid in the abdomen. He has two large-bore IV lines running. What is the most appropriate next management?",
    options: [
      { label: "A", text: "CT abdomen and pelvis for full characterisation" },
      { label: "B", text: "Emergency laparotomy" },
      { label: "C", text: "Non-operative management with serial abdominal examinations" },
      { label: "D", text: "Diagnostic peritoneal lavage" },
      { label: "E", text: "Angiography for splenic embolisation" },
    ],
    correctAnswer: "B",
    explanation: "Haemodynamically unstable penetrating abdominal trauma with positive FAST = emergency laparotomy. Do NOT delay for CT in unstable patients. CT is for haemodynamically STABLE patients with blunt trauma. Positive FAST + penetrating mechanism + instability = operate immediately. Damage control surgery: temporary haemostasis, planned reoperation. Non-operative management only for stable blunt solid organ injuries.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "surg-008", topic: "Surgery", subtopic: "Acute Pancreatitis",
    stem: "A 45-year-old woman with gallstone pancreatitis has a CT on day 5 showing 50% pancreatic necrosis. She is febrile (39.2°C) with worsening abdominal pain. WBC 24. CT-guided aspiration of necrosis grows E. coli. What is this complication and management?",
    options: [
      { label: "A", text: "Sterile necrosis — supportive management, no antibiotics" },
      { label: "B", text: "Infected necrotising pancreatitis — IV antibiotics + minimally invasive step-up approach" },
      { label: "C", text: "Pancreatic pseudocyst — endoscopic drainage" },
      { label: "D", text: "Immediate open necrosectomy" },
      { label: "E", text: "ERCP for biliary drainage" },
    ],
    correctAnswer: "B",
    explanation: "Infected pancreatic necrosis: fever + leucocytosis + CT evidence of gas in necrosis or positive aspiration culture. Treatment: IV antibiotics with good pancreatic penetration (carbapenems, metronidazole + fluoroquinolone). 'Step-up approach': percutaneous/endoscopic drainage first → if inadequate, minimally invasive necrosectomy (video-assisted retroperitoneal debridement, VARD) → open necrosectomy as last resort. Step-up approach has lower mortality than open surgery.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "surg-009", topic: "Surgery", subtopic: "Post-operative",
    stem: "A 65-year-old man is day 3 post-bowel resection. He develops fever 39°C, HR 115, and right calf tenderness with swelling. Doppler ultrasound confirms DVT. He is currently on heparin infusion for AF. What is the appropriate management of the DVT?",
    options: [
      { label: "A", text: "Add separate therapeutic LMWH to heparin infusion" },
      { label: "B", text: "Continue current therapeutic heparin — already anticoagulated" },
      { label: "C", text: "Insert IVC filter — anticoagulation contraindicated post-surgery" },
      { label: "D", text: "Warfarin alone" },
      { label: "E", text: "Compression stocking only" },
    ],
    correctAnswer: "B",
    explanation: "Patient already on therapeutic anticoagulation (heparin infusion for AF): no additional anticoagulation needed — DVT is already covered. Ensure therapeutic anticoagulation maintained (APTT 60–100 sec for UFH). Transition to LMWH or DOAC once stable. IVC filter: only if anticoagulation is absolutely contraindicated (e.g., active serious bleeding). Compression stockings adjunct but not treatment for confirmed DVT.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "surg-010", topic: "Surgery", subtopic: "Wound",
    stem: "A 60-year-old diabetic woman has a non-healing foot ulcer under the 1st MTP joint for 8 weeks. It is 3 × 2 cm, full-thickness to subcutaneous fat, with slough, surrounding callus, and reduced pedal pulses. ABI 0.65. What is the most important initial investigation and management priority?",
    options: [
      { label: "A", text: "Wound swab and antibiotics" },
      { label: "B", text: "Assess vascular supply (ABI, Doppler/angiography) + revascularisation if needed" },
      { label: "C", text: "Hyperbaric oxygen therapy" },
      { label: "D", text: "Skin grafting immediately" },
      { label: "E", text: "Serial wound debridement alone" },
    ],
    correctAnswer: "B",
    explanation: "Diabetic foot ulcer with reduced ABI (0.65 = moderate PAD): vascular assessment is the critical priority. Neuro-ischaemic ulcers will not heal without adequate perfusion. Assess with ABI, toe pressures (transcutaneous pO2 <30 mmHg = poor healing), arterial Doppler, CT angiography. Revascularisation (angioplasty/bypass) before debridement/wound care. Multidisciplinary diabetic foot team. Off-loading (total contact cast). Infection: Gram stain, probe-to-bone for osteomyelitis.",
    reference: "amc", difficulty: "medium",
  },
];
