import type { MCQuestion } from "./questions";

export const rheumatologyQuestions: MCQuestion[] = [
  {
    id: "rheum-001", topic: "Rheumatology", subtopic: "Rheumatoid Arthritis",
    stem: "A 40-year-old woman presents with 3 months of symmetrical small joint arthritis (MCP, PIP, wrists), morning stiffness >1 hour, and fatigue. RF and anti-CCP are positive. Hands X-ray shows periarticular osteopaenia. What is the first-line DMARD?",
    options: [
      { label: "A", text: "Hydroxychloroquine alone" },
      { label: "B", text: "Methotrexate (MTX) 15–25 mg/week" },
      { label: "C", text: "Adalimumab (anti-TNF) immediately" },
      { label: "D", text: "Prednisolone 10 mg/day long-term" },
      { label: "E", text: "Leflunomide + sulfasalazine combination" },
    ],
    correctAnswer: "B",
    explanation: "RA first-line DMARD: methotrexate (MTX) is the anchor drug. Start 10–15 mg/week, escalate to 25 mg. Add folic acid 5 mg once/week (not same day as MTX) to reduce side effects. Monitor: FBC, LFTs, creatinine every 1–3 months. If MTX insufficient after 3 months at target dose: add hydroxychloroquine or leflunomide. Anti-TNF if inadequate response to ≥2 conventional DMARDs.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "rheum-002", topic: "Rheumatology", subtopic: "Gout",
    stem: "A 55-year-old man presents with acute red, hot, swollen first MTP joint. Uric acid is 560 µmol/L. He is on hydrochlorothiazide for hypertension. What is the first-line treatment for acute gout?",
    options: [
      { label: "A", text: "Start allopurinol immediately to lower urate" },
      { label: "B", text: "NSAIDs (indomethacin or naproxen) or colchicine or prednisolone" },
      { label: "C", text: "Rest and ice only" },
      { label: "D", text: "Probenecid to increase uric acid excretion" },
      { label: "E", text: "IV corticosteroids only" },
    ],
    correctAnswer: "B",
    explanation: "Acute gout: anti-inflammatory treatment within 24 hours. NSAIDs (indomethacin, naproxen), colchicine (0.5 mg TDS for 3 days), or prednisolone (30–40 mg × 3–5 days) are equally effective. Choose based on comorbidities: eGFR<30→ avoid NSAIDs/colchicine; peptic ulcer→avoid NSAIDs; DM→ caution steroids. Do NOT start allopurinol during acute attack (can prolong/exacerbate). Review thiazide (switches to amlodipine better for BP with gout).",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "rheum-003", topic: "Rheumatology", subtopic: "Gout",
    stem: "A 60-year-old man has had 4 gout flares in 2 years. Uric acid is persistently >0.50 mmol/L. He has CKD Stage 2. What is the urate-lowering target and preferred ULT agent?",
    options: [
      { label: "A", text: "Target urate <0.60 mmol/L — allopurinol" },
      { label: "B", text: "Target urate <0.36 mmol/L — allopurinol or febuxostat" },
      { label: "C", text: "Target urate <0.30 mmol/L — febuxostat preferred" },
      { label: "D", text: "No treatment — 4 flares is not enough for ULT" },
      { label: "E", text: "Target urate <0.42 mmol/L — probenecid" },
    ],
    correctAnswer: "B",
    explanation: "Urate-lowering therapy (ULT) indications: ≥2 flares/year, tophi, chronic gouty arthritis, uric acid nephrolithiasis, severe hyperuricaemia. Target urate <0.36 mmol/L (<6 mg/dL) — below monosodium urate saturation point. Allopurinol is first-line: start 50–100 mg/day, escalate slowly (HLA-B*5801 screening in Asians — risk of SJS). Febuxostat (non-purine XO inhibitor) if allopurinol intolerant. Cover with prophylactic colchicine 0.5 mg daily for 6 months when starting ULT.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-004", topic: "Rheumatology", subtopic: "SLE",
    stem: "A 25-year-old woman presents with malar rash, photosensitivity, oral ulcers, arthritis in multiple joints, and proteinuria 2.5 g/day. ANA is positive at 1:640. Anti-dsDNA is elevated. C3 and C4 are low. What is the diagnosis and what does anti-dsDNA indicate?",
    options: [
      { label: "A", text: "Drug-induced lupus — anti-histone antibodies positive" },
      { label: "B", text: "SLE with renal involvement — anti-dsDNA correlates with disease activity" },
      { label: "C", text: "Sjögren's syndrome — anti-Ro/La positive" },
      { label: "D", text: "Mixed connective tissue disease — anti-U1RNP positive" },
      { label: "E", text: "Systemic vasculitis — ANCA positive" },
    ],
    correctAnswer: "B",
    explanation: "SLE: ≥4 SLICC criteria. Anti-dsDNA: specific for SLE (95%), correlates with disease activity and lupus nephritis. Low complement (C3/C4) indicates active immune complex deposition. Proteinuria 2.5 g/day = probable lupus nephritis (class III/IV). Renal biopsy required to classify. Treatment: hydroxychloroquine (all SLE patients), immunosuppression (mycophenolate, azathioprine) for nephritis, belimumab for refractory SLE.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-005", topic: "Rheumatology", subtopic: "Ankylosing Spondylitis",
    stem: "A 28-year-old man presents with 2 years of inflammatory back pain (worse in morning, improves with exercise, not rest), buttock pain alternating sides, and iritis. HLA-B27 is positive. MRI sacroiliac joints show bone marrow oedema. What is the diagnosis and first-line treatment?",
    options: [
      { label: "A", text: "Mechanical back pain — physiotherapy" },
      { label: "B", text: "Ankylosing spondylitis (axial SpA) — NSAIDs first-line" },
      { label: "C", text: "AS — anti-TNF immediately" },
      { label: "D", text: "AS — sulfasalazine" },
      { label: "E", text: "Psoriatic arthritis — methotrexate" },
    ],
    correctAnswer: "B",
    explanation: "Axial spondyloarthritis: inflammatory back pain + HLA-B27 + sacroiliitis on MRI. First-line: NSAIDs (continuous dosing, not PRN) + physiotherapy (exercise is crucial — prevents ankylosis). If ≥2 NSAIDs failed after 4 weeks each → anti-TNF (adalimumab, etanercept, infliximab) or IL-17 inhibitor (secukinumab). Sulfasalazine for peripheral joint disease only. DMARDs not effective for axial disease.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-006", topic: "Rheumatology", subtopic: "Psoriatic Arthritis",
    stem: "A 38-year-old man with plaque psoriasis develops painful swollen fingers with nail pitting. One finger is uniformly swollen (dactylitis). X-ray shows pencil-in-cup deformity at DIP joints. What is the diagnosis?",
    options: [
      { label: "A", text: "Rheumatoid arthritis — anti-CCP test" },
      { label: "B", text: "Psoriatic arthritis — nail/skin involvement, dactylitis, DIP involvement" },
      { label: "C", text: "Reactive arthritis" },
      { label: "D", text: "Gout" },
      { label: "E", text: "Osteoarthritis" },
    ],
    correctAnswer: "B",
    explanation: "Psoriatic arthritis: psoriasis + DIP joint involvement (distinguishes from RA which is PIP/MCP), dactylitis ('sausage digit'), enthesitis, nail changes (pitting, onycholysis), seronegative (RF negative). Pencil-in-cup: severe osteolysis. Treatment: NSAIDs for mild; MTX/leflunomide for moderate; anti-TNF or IL-17i/IL-12/23i (ustekinumab) for severe/refractory. Biologics also treat skin.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-007", topic: "Rheumatology", subtopic: "Osteoporosis",
    stem: "A 68-year-old woman has a DEXA scan showing T-score -2.8 at the lumbar spine. She had a fragility fracture of the wrist 2 years ago. She is on long-term prednisolone. What is the most appropriate treatment?",
    options: [
      { label: "A", text: "Calcium and vitamin D only" },
      { label: "B", text: "Alendronate 70 mg weekly + calcium/vitamin D" },
      { label: "C", text: "HRT (hormone replacement therapy)" },
      { label: "D", text: "Raloxifene (SERM)" },
      { label: "E", text: "Teriparatide (PTH analogue)" },
    ],
    correctAnswer: "B",
    explanation: "Established osteoporosis: T-score ≤-2.5 + fragility fracture = severe osteoporosis. Treatment: bisphosphonate (alendronate 70 mg weekly or risedronate 35 mg weekly) + calcium 1200 mg/day + vitamin D 1000–2000 IU/day. Corticosteroid-induced osteoporosis: bisphosphonate indicated if on prednisolone ≥7.5 mg/day for >3 months. Review after 5 years (drug holiday if low ongoing risk). Teriparatide for severe/refractory cases.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-008", topic: "Rheumatology", subtopic: "Osteoarthritis",
    stem: "A 65-year-old obese woman has bilateral knee pain on movement, crepitus, and bony enlargement. X-ray shows joint space narrowing, osteophytes, and subchondral sclerosis. She asks about the best treatment for pain. Renal function is mildly impaired (eGFR 52). What is first-line?",
    options: [
      { label: "A", text: "Opioids (oxycodone)" },
      { label: "B", text: "NSAIDs (ibuprofen/naproxen) regularly" },
      { label: "C", text: "Paracetamol regular + exercise + weight loss + topical NSAID" },
      { label: "D", text: "Intra-articular corticosteroid immediately" },
      { label: "E", text: "Total knee replacement" },
    ],
    correctAnswer: "C",
    explanation: "OA management: first-line = non-pharmacological: exercise (strengthening, aerobic), weight loss (every kg lost = 4 kg less knee load), physiotherapy. Pharmacological: paracetamol (regular dosing), topical NSAIDs (less systemic risk, eGFR impaired). Systemic NSAIDs: caution with CKD/elderly — GI and renal risk. Opioids: avoid long-term. Intra-articular steroid for acute flares. TKR when conservative management fails and quality of life impaired.",
    reference: "racgp-redbook", difficulty: "easy",
  },
  {
    id: "rheum-009", topic: "Rheumatology", subtopic: "Polymyalgia Rheumatica",
    stem: "A 72-year-old woman presents with 3 months of bilateral shoulder and hip girdle aching and stiffness, worse in the morning for >45 minutes. CRP 85, ESR 78. She has no muscle weakness. What is the diagnosis and treatment?",
    options: [
      { label: "A", text: "Fibromyalgia — low-dose amitriptyline" },
      { label: "B", text: "RA — methotrexate" },
      { label: "C", text: "PMR — prednisolone 15–20 mg/day with gradual taper" },
      { label: "D", text: "Inflammatory myopathy — creatine kinase measurement" },
      { label: "E", text: "Hypothyroidism — TSH" },
    ],
    correctAnswer: "C",
    explanation: "PMR: age >50 (mean 70), bilateral shoulder/hip girdle pain and stiffness, elevated ESR/CRP, rapid response to steroids (diagnostic). Treatment: prednisolone 15 mg/day (shoulder-only) or 20 mg (hip + shoulder) → rapid improvement within days. Taper slowly over 18–24 months. Always screen for GCA (15% association): headache, jaw claudication, temporal tenderness → check for temporal arteritis (higher dose steroids). Monitor with ESR/CRP.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "rheum-010", topic: "Rheumatology", subtopic: "Septic Arthritis",
    stem: "A 35-year-old man presents with acute swollen, red, hot knee with severe pain on movement. Temperature 38.8°C. WBC 18.5. He had IV drug use 2 weeks ago. What is the most important immediate investigation and management?",
    options: [
      { label: "A", text: "MRI knee and oral antibiotics" },
      { label: "B", text: "Joint aspiration → Gram stain and culture → IV antibiotics" },
      { label: "C", text: "Rest, ice and NSAIDs pending culture" },
      { label: "D", text: "X-ray to exclude fracture first" },
      { label: "E", text: "Anti-inflammatory dose prednisolone" },
    ],
    correctAnswer: "B",
    explanation: "Septic arthritis: hot, red, swollen joint + fever = emergency. Joint aspiration is diagnostic and therapeutic: Gram stain (Gram-positive cocci = staph) + culture + cell count (WBC >50,000 + >75% PMN = septic until proven otherwise). Start IV antibiotics immediately after aspirating: IV flucloxacillin (staph coverage). IVDU: add anti-pseudomonal coverage. Washout arthroscopically if no improvement in 24–48h. Gout can coexist — crystals on microscopy don't exclude infection.",
    reference: "amc", difficulty: "medium",
  },
];
