import type { MCQuestion } from "./questions";

export const endocrineQuestions: MCQuestion[] = [
  {
    id: "endo-001", topic: "Endocrinology", subtopic: "Diabetes",
    stem: "A 52-year-old man with T2DM has HbA1c 8.9% on metformin 2g/day. He has cardiovascular disease (prior MI). eGFR is 72. Which second agent provides the most cardiovascular and renal benefit?",
    options: [
      { label: "A", text: "Sulfonylurea (gliclazide)" },
      { label: "B", text: "DPP-4 inhibitor (sitagliptin)" },
      { label: "C", text: "SGLT2 inhibitor (empagliflozin or dapagliflozin)" },
      { label: "D", text: "Insulin glargine" },
      { label: "E", text: "Acarbose" },
    ],
    correctAnswer: "C",
    explanation: "SGLT2 inhibitors in T2DM with CVD: empagliflozin (EMPA-REG) and canagliflozin (CANVAS) reduce MACE, heart failure hospitalisation, and CKD progression. GLP-1 receptor agonists (liraglutide, semaglutide) also have CV benefit. SGLT2i preferred when heart failure or CKD present. Can be used down to eGFR 30 for CV/renal protection (not for glucose lowering at eGFR <45).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-002", topic: "Endocrinology", subtopic: "Diabetes",
    stem: "A 45-year-old woman presents with DKA (glucose 32, pH 7.15, bicarbonate 8, ketones 5.2 mmol/L, anion gap 22). She is mildly confused. What is the most important immediate treatment priority?",
    options: [
      { label: "A", text: "Insulin infusion immediately" },
      { label: "B", text: "IV fluid resuscitation (normal saline)" },
      { label: "C", text: "Bicarbonate infusion to correct acidosis" },
      { label: "D", text: "IV potassium immediately" },
      { label: "E", text: "Oral rehydration" },
    ],
    correctAnswer: "B",
    explanation: "DKA management priority: IV fluid resuscitation FIRST (1 L normal saline bolus then 1 L/hour). Fluids restore volume and reduce glucose/ketones. Insulin only after K+ ≥3.5 mEq/L (insulin drives K+ intracellularly → fatal hypokalaemia). Bicarbonate only if pH <6.9. Monitor K+ every hour. FIXED-RATE insulin infusion 0.1 units/kg/hour after fluids and K+ correction.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-003", topic: "Endocrinology", subtopic: "Thyroid",
    stem: "A 35-year-old woman presents with 3 months of weight loss, heat intolerance, palpitations, and tremor. She has proptosis bilaterally and a diffuse goitre. TSH <0.01, FT4 elevated, FT3 elevated. TRAb antibodies positive. What is the diagnosis and preferred treatment in Australia?",
    options: [
      { label: "A", text: "Toxic multinodular goitre — radioactive iodine (RAI)" },
      { label: "B", text: "Graves' disease — antithyroid drugs (carbimazole) first-line" },
      { label: "C", text: "Toxic adenoma — surgery" },
      { label: "D", text: "Graves' disease — surgery first-line" },
      { label: "E", text: "Subacute thyroiditis — NSAIDs" },
    ],
    correctAnswer: "B",
    explanation: "Graves' disease: TRAb positive, diffuse goitre, orbitopathy, pretibial myxoedema. First-line in Australia: antithyroid drugs (carbimazole 20–40 mg/day) for 12–18 months → 50% remission. Add propranolol for symptomatic relief. Definitive therapy: RAI or thyroidectomy. Graves' orbitopathy worsens with RAI — consider surgery or antithyroid drugs. Pregnancy: propylthiouracil in first trimester.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-004", topic: "Endocrinology", subtopic: "Thyroid",
    stem: "A 68-year-old woman is found to have TSH 12.5 mU/L (normal 0.4–4.0) and FT4 9 pmol/L on routine bloods. She has mild fatigue and feeling cold. Cholesterol is elevated. What is the treatment?",
    options: [
      { label: "A", text: "No treatment — subclinical hypothyroidism, watch and wait" },
      { label: "B", text: "Levothyroxine 50–100 µg/day, adjusted to normalise TSH" },
      { label: "C", text: "Iodine supplementation" },
      { label: "D", text: "Liothyronine (T3) only" },
      { label: "E", text: "Radioactive iodine" },
    ],
    correctAnswer: "B",
    explanation: "Overt hypothyroidism (elevated TSH + low FT4): treatment always indicated. Levothyroxine (T4), start low (25–50 µg in elderly/cardiac disease), titrate to TSH 0.5–2.5 mU/L. Subclinical hypothyroidism (elevated TSH, normal FT4): treat if TSH >10, symptomatic, or planning pregnancy. Target cholesterol should also improve with thyroid replacement.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "endo-005", topic: "Endocrinology", subtopic: "Adrenal",
    stem: "A 42-year-old woman is referred with hypertension, weight gain, easy bruising, moon face, and central obesity. Random cortisol 28.5 µg/dL. 24-hour urinary free cortisol is markedly elevated. What is the next diagnostic step?",
    options: [
      { label: "A", text: "MRI pituitary" },
      { label: "B", text: "CT adrenals" },
      { label: "C", text: "Low-dose dexamethasone suppression test (LDDST)" },
      { label: "D", text: "High-dose dexamethasone suppression test" },
      { label: "E", text: "ACTH stimulation test" },
    ],
    correctAnswer: "C",
    explanation: "Cushing's syndrome: confirm hypercortisolism first with ≥2 tests: 24h UFC (done), LDDST, or late-night salivary cortisol. LDDST: dexamethasone 1 mg at midnight, cortisol next morning — normal suppression <50 nmol/L excludes Cushing's. Then determine ACTH-dependent vs independent: measure ACTH. ACTH elevated → Cushing's disease (pituitary, 70%) or ectopic. ACTH suppressed → adrenal adenoma.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "endo-006", topic: "Endocrinology", subtopic: "Adrenal",
    stem: "A 35-year-old man presents with episodic headaches, diaphoresis, palpitations, and hypertensive crises. BP 210/120 during episodes. Between attacks he is normotensive. 24-hour urinary metanephrines are markedly elevated. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Primary aldosteronism" },
      { label: "B", text: "Phaeochromocytoma" },
      { label: "C", text: "Carcinoid syndrome" },
      { label: "D", text: "Paraganglioma" },
      { label: "E", text: "Essential hypertension" },
    ],
    correctAnswer: "B",
    explanation: "Phaeochromocytoma: catecholamine-secreting tumour of adrenal medulla. 'Rule of 10s': 10% bilateral, 10% extra-adrenal, 10% malignant, 10% familial (MEN2, VHL, NF1). Diagnosis: 24h urinary metanephrines/catecholamines (best test), plasma metanephrines. Imaging: CT/MRI adrenals, then MIBG scan. Pre-operative: alpha-blocker (phenoxybenzamine) FIRST, then beta-blocker. Surgery is curative.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-007", topic: "Endocrinology", subtopic: "Adrenal",
    stem: "A 45-year-old man presents with fatigue, weight loss, hyperpigmentation of skin creases and buccal mucosa, postural hypotension, and hyponatraemia with hyperkalaemia. Cortisol fails to rise after Synacthen stimulation. What is the diagnosis?",
    options: [
      { label: "A", text: "Cushing's syndrome" },
      { label: "B", text: "Primary adrenal insufficiency (Addison's disease)" },
      { label: "C", text: "Secondary adrenal insufficiency (hypopituitarism)" },
      { label: "D", text: "SIADH" },
      { label: "E", text: "Hypothyroidism" },
    ],
    correctAnswer: "B",
    explanation: "Addison's disease (primary AI): hyperpigmentation (↑ACTH-MSH), ↓Na, ↑K (mineralocorticoid deficiency), hypotension, hypoglycaemia. Secondary AI: no hyperpigmentation, ACTH low, Na low but K normal. Synacthen test (short): inject 250 µg ACTH; cortisol should rise >500 nmol/L. Treatment: hydrocortisone (glucocorticoid) + fludrocortisone (mineralocorticoid). Sick day rules: double dose during illness.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-008", topic: "Endocrinology", subtopic: "Pituitary",
    stem: "A 30-year-old woman presents with galactorrhoea, amenorrhoea, and infertility. Prolactin is 2800 mU/L. MRI shows a 15 mm pituitary adenoma. What is the first-line treatment?",
    options: [
      { label: "A", text: "Transsphenoidal surgery" },
      { label: "B", text: "Radiotherapy" },
      { label: "C", text: "Dopamine agonist (cabergoline or bromocriptine)" },
      { label: "D", text: "Oestrogen replacement" },
      { label: "E", text: "Octreotide" },
    ],
    correctAnswer: "C",
    explanation: "Prolactinoma: most common pituitary tumour. Medical treatment with dopamine agonists (cabergoline preferred over bromocriptine — more effective, once weekly, fewer side effects) is first-line even for macroprolactinomas. Surgery for: resistance/intolerance to DA agonists, rapidly deteriorating vision, or patient preference. 80–90% response to cabergoline. Normalises prolactin, reduces tumour size, restores fertility.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-009", topic: "Endocrinology", subtopic: "Diabetes",
    stem: "A 60-year-old man on insulin (glargine 30 units nocte + novorapid TDS) has recurrent nocturnal hypoglycaemia. HbA1c is 6.1%. He lives alone. What is the most appropriate management?",
    options: [
      { label: "A", text: "Increase nocturnal monitoring and continue current dose" },
      { label: "B", text: "Reduce glargine dose and increase HbA1c target to 7–8%" },
      { label: "C", text: "Switch to twice-daily premixed insulin" },
      { label: "D", text: "Add metformin to reduce insulin requirements" },
      { label: "E", text: "Continuous glucose monitoring (CGM) only" },
    ],
    correctAnswer: "B",
    explanation: "Recurrent hypoglycaemia + HbA1c 6.1% = over-treated. In elderly or those living alone, HbA1c target should be relaxed (7–8% or even 8–9% in frail elderly). Reduce glargine dose by 10–20%. Risk of nocturnal hypoglycaemia from glargine: review timing (some switch to morning injection). CGM helpful adjunct. Hypoglycaemia awareness may be impaired in long-standing DM.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "endo-010", topic: "Endocrinology", subtopic: "Thyroid",
    stem: "A 58-year-old man has a 2.5 cm solitary thyroid nodule found incidentally on CT. TSH is normal. What is the next most appropriate investigation?",
    options: [
      { label: "A", text: "CT neck with contrast" },
      { label: "B", text: "Thyroid scintigraphy (nuclear scan)" },
      { label: "C", text: "Ultrasound-guided fine needle aspiration cytology (FNAC)" },
      { label: "D", text: "Surgical excision without further testing" },
      { label: "E", text: "Annual ultrasound surveillance" },
    ],
    correctAnswer: "C",
    explanation: "Thyroid nodule >1 cm (or suspicious US features) with normal TSH: US-guided FNAC is the investigation of choice for cytological diagnosis. Bethesda classification guides management. Thyroid scintigraphy for hyperfunctioning nodules (suppressed TSH). Cold nodules have higher malignancy risk. Hot nodules are rarely malignant. US features suggesting malignancy: hypoechogenicity, irregular margins, microcalcifications, tall>wide shape.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-011", topic: "Endocrinology", subtopic: "Diabetes",
    stem: "A 17-year-old girl presents with 3 days of polyuria, polydipsia, and 4 kg weight loss. Random glucose is 28 mmol/L. pH 7.31, bicarbonate 18, ketones 2.4 mmol/L. She is alert. What is the diagnosis?",
    options: [
      { label: "A", text: "Type 2 DM with new presentation" },
      { label: "B", text: "DKA — admit for IV insulin protocol" },
      { label: "C", text: "Mild DKA (euglycaemic DKA)" },
      { label: "D", text: "Hyperglycaemic hyperosmolar state (HHS)" },
      { label: "E", text: "New-onset Type 1 DM — subcutaneous insulin" },
    ],
    correctAnswer: "B",
    explanation: "Mild/moderate DKA (pH 7.25–7.3, bicarbonate 10–18, ketones elevated). New Type 1 DM presentation. Management: IV fluids + fixed-rate insulin infusion, hourly monitoring, potassium replacement. Even mild DKA requires hospitalisation for IV protocol. HHS: elderly T2DM, very high glucose (>30), osmolality >320, minimal ketonaemia. Once DKA resolved and eating: transition to subcutaneous basal-bolus insulin.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "endo-012", topic: "Endocrinology", subtopic: "Parathyroid",
    stem: "A 55-year-old woman has calcium 2.92 mmol/L, phosphate 0.65, PTH 95 ng/L (elevated), and 24h urinary calcium 8 mmol/day. She has mild fatigue and kidney stones. What is the diagnosis and management?",
    options: [
      { label: "A", text: "Malignancy-related hypercalcaemia — investigate for cancer" },
      { label: "B", text: "Primary hyperparathyroidism — parathyroidectomy if symptomatic" },
      { label: "C", text: "Familial hypocalciuric hypercalcaemia — no treatment" },
      { label: "D", text: "Sarcoidosis — steroids" },
      { label: "E", text: "Vitamin D toxicity — stop supplements" },
    ],
    correctAnswer: "B",
    explanation: "Primary hyperparathyroidism: elevated Ca, low PO4, elevated PTH (PTH-dependent hypercalcaemia). Most common cause of hypercalcaemia in outpatients. Usually parathyroid adenoma (80%). Indications for parathyroidectomy: symptoms, Ca >2.85, age <50, osteoporosis, renal stones, eGFR <60. FHH (familial): low urinary Ca, Ca:creatinine ratio <0.01 — no treatment needed.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "endo-013", topic: "Endocrinology", subtopic: "Metabolic Syndrome",
    stem: "A 48-year-old man has: waist circumference 102 cm, BP 138/88, fasting glucose 5.9 mmol/L, TG 2.4 mmol/L, HDL 0.9 mmol/L. He has 3 of the 5 criteria. What is the diagnosis and key risk?",
    options: [
      { label: "A", text: "Type 2 DM — start metformin" },
      { label: "B", text: "Metabolic syndrome — high risk of T2DM and cardiovascular disease" },
      { label: "C", text: "Hypertriglyceridaemia — fibrate therapy" },
      { label: "D", text: "Pre-diabetes only — monitor HbA1c" },
      { label: "E", text: "Normal findings — no action required" },
    ],
    correctAnswer: "B",
    explanation: "Metabolic syndrome (IDF criteria): central obesity + ≥2 of: TG ≥1.7, HDL <1.0 (males), BP ≥130/85, FBG ≥5.6. This patient has all 5. Associated with 5× increased T2DM risk and 2× CVD risk. Treatment: lifestyle modification (weight loss 5–10%, exercise, diet) is cornerstone. Address individual components: statins, antihypertensives, metformin for pre-diabetes.",
    reference: "racgp-redbook", difficulty: "easy",
  },
];
