import type { MCQuestion } from "./questions";

export const dermatologyQuestions: MCQuestion[] = [
  {
    id: "derm-amedex-0001",
    topic: "Dermatology",
    subtopic: "Herpes Zoster (Shingles) - Acute Management",
    stem: `A 65-year-old man presents with an exquisitely painful vesicular rash, which has been present for the past 7 days and is increasingly painful. The rash is shown in the following photograph. His past medical history is unremarkable. Physical examination is otherwise inconclusive. Which one of the following is the most appropriate immediate management?`,
    options: [
      { label: "A", text: `Oral famciclovir.` },
      { label: "B", text: `Intravenous famciclovir.` },
      { label: "C", text: `Oral amitriptyline.` },
      { label: "D", text: `Intramuscular immunoglobulin.` },
      { label: "E", text: `Oral Phenergan® (promethazine).` },
    ],
    correctAnswer: "C",
    explanation: `The appearance of the rash and the history suggest herpes zoster (shingles) infection as the most likely diagnosis. Herpes zoster is caused by the reactivation of the varicella-zoster virus (VZV). It usually occurs in adults but can be seen in children and in the first 2 years of life if there has been a history of maternal varicella. Pain is a significant complaint in patients with shingles. Tricyclic antidepressants and the anticonvulsant gabapentin are the most effective medications for pain control in neuropathic pain associated with shingles. Antiviral agents such as famciclovir, valacyclovir, or acyclovir should be used in any patient seen within 72 hours of the onset of vesicles, all patients with ophthalmic herpes zoster, and in immunocompromised patients. For pregnant women, only acyclovir (first line) or valacyclovir (second line) are used because the safety of famciclovir during pregnancy has yet to be established. Varicella zoster immunoglobulin (VZIG) and vaccine are used for prophylaxis. Their use is not effective in the treatment or for pain control after the infection has established. Promethazine is not effective for pain control in shingles.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0002",
    topic: "Dermatology",
    subtopic: "Post-Herpetic Neuralgia (PHN) - Chronic Pain Management",
    stem: `A 52-year-old man presents with intense pain in his chest wall for the past 4 months. The problem started with the eruption of a rash over the area. The rash resolved in 2 weeks, but the pain has persisted and increased in intensity. He describes the pain as constant, sharp, and unbearable, affecting his life. He has used Panadol and ibuprofen for pain control with minimal effect. He also has diabetes, hypertension, and stage III chronic kidney disease, and denies any pain or pins and needles elsewhere. Which of the following is the most appropriate option for him?`,
    options: [
      { label: "A", text: `Gabapentin.` },
      { label: "B", text: `Tramadol.` },
      { label: "C", text: `Amitriptyline.` },
      { label: "D", text: `Systemic steroids.` },
      { label: "E", text: `Pregabalin.` },
    ],
    correctAnswer: "C",
    explanation: `The scenario represents post-herpetic neuralgia (PHN), defined as chronic pain associated with herpes zoster infection (shingles) caused by the varicella-zoster virus. Varicella zoster virus (VZV) infection causes two distinct clinical syndromes. Primary infection, varicella or chickenpox, is a common pediatric viral disease. After a chickenpox infection, VZV remains latent in the neurons of cranial nerves and dorsal root ganglia. Subsequent reactivation of latent VZV can result in a vesicular rash in a dermatomal distribution known as herpes zoster (shingles). The lesions are painful, and the pain may last long, even after the resolution of the rash. Pain that persists for 3 months or more is defined as post-herpetic neuralgia (PHN). The pain associated with acute zoster infection and PHN can be burning, sharp, stabbing, and constant or intermittent. More than 90 per cent of patients with PHN also have allodynia, defined as pain evoked by normally nonpainful stimuli such as light touch. Pain control in the acute phase of the infection is often achieved by simple analgesics and/or systemic steroids (e.g., prednisolone 50mg/d for 7 days). Opioids or amitriptyline can be used as second-line options if adequate pain control is achieved. For PHN, the anticonvulsants gabapentin or pregabalin, tricyclic antidepressants (TCAs), or lignocaine dermal patches are used as first-line options. Of the TCA, amitriptyline is the most effective and commonly prescribed one. With pain lasting for 4 months, this patient has PHN. Gabapentin (option A) and pregabalin (option E) are eliminated by renal excretion and should be used with caution and meticulous dose adjustment in patients with renal insufficiency and avoided if better first-line options are applicable. For him, amitriptyline is the most appropriate option for pain control. TCAs inhibit the reuptake of norepinephrine and serotonin in the central nervous system. They are thought to increase the inhibition of nociceptive signals from the periphery. The preferred tricyclic drug for PHN is amitriptyline, starting at 10 mg each night and titrating slowly as tolerated, with a maximum dose of 150 mg daily. Amitriptyline is excreted via the liver and its metabolism and is the most appropriate option in this scenario. Its anticholinergic adverse effects such as sedation and dry mouth) may limit the patient's compliance. Opioids (option B) or tramadol can be used as second-line agents in those with contraindications to the first-line options. While steroids (option D) are used for treating acute herpes zoster pain where inflammation seems to have a role, they have no effect on PHN as it has a different pathophysiology.`,
    reference: "amc",
    difficulty: "hard",
  },
  {
    id: "derm-amedex-0003",
    topic: "Dermatology",
    subtopic: "Scabies - Treatment",
    stem: `The following photograph shows skin lesions on the hand of a 73-year-old woman, who resides in a nursing home. The lesions are severely itchy and she keeps scratching them, especially in the night. The itch prevents her from a good night sleep. On examination, she looks disheveled and poorly cared for. Which one of the following would be the most appropriate treatment for her?`,
    options: [
      { label: "A", text: `Permethrin 5% cream.` },
      { label: "B", text: `Itraconazole cream.` },
      { label: "C", text: `Topical corticosteroids.` },
      { label: "D", text: `Gamma benzene hexachloride.` },
      { label: "E", text: `Topical erythromycin.` },
    ],
    correctAnswer: "A",
    explanation: `The itching, the appearance of the lesions and living in a nursing home all favor of scabies as the most likely diagnosis. First-line medication for treatment of scabies is permethrin 5% cream. If treatment with permethrin fails or the patient is sensitive to this drug, benzyl benzoate can be used as second-line therapy. Benzyl benzoate is more irritating to skin and the treatment is likely to fail due to inadequate adherence. (Option B) Itraconazole cream is used for treatment of fungal skin infections. It has no role in treatment of scabies. (Option C) Topical corticosteroids of moderate potency may be used in conjunction with permethrin or benzyl benzoate, with no effect on the scabies. (Option D) Gamma benzene hexachloride (Lindane®) was formerly used for treatment of scabies. It is no longer approved for this purpose in Australia, as well as many other parts of the world. (Option E) If a bacterial infection superimposes scabies, the antibiotics of choice would be topical mupirocin or oral cephalexin in more severe cases. Erythromycin is not routinely used for`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0004",
    topic: "Dermatology",
    subtopic: "Nail Apparatus Melanoma - Prognosis and Management",
    stem: `Which one of the following statements is correct regarding nail apparatus melanoma?`,
    options: [
      { label: "A", text: `It is a common form of melanoma.` },
      { label: "B", text: `It has a good prognosis.` },
      { label: "C", text: `The 5-year survival depends on the depth (thickness) of the lesion.` },
      { label: "D", text: `Nail removal maybe curative.` },
      { label: "E", text: `There is a strong association to sun exposure.` },
    ],
    correctAnswer: "C",
    explanation: `Nail apparatus melanomas (subungual melanoma) are rare but frequently fatal neoplasms. They account for between 1.5-3% of all melanomas. All age groups can be affected; however, it is most common in the 7th decade of life. Melanoma of the nail initially presents as a longitudinal pigmented streak. Later, the proximal nail fold may become pigmented (Hutchinson's sign). As the disease advances, the nail plate may be destroyed. By this stage, the disease is often advanced, with lymph node metastasis frequently present. As with other melanomas, increased tumor depth and the presence of ulceration are associated with a worse prognosis and decreased five-year survival. 70% of subungual melanomas occur on the thumb or great toe. Subungual melanomas involving the toes can be managed easily with digital amputation at the metatarsal-phalangeal joint. If the first toe (big toe) is involved, complete amputation should be avoided when the lesion is amenable to less invasive oncological treatments because of the importance of the toe in balance. Whenever possible, subungual melanomas of the fingers should be resected at the distal interphalangeal joint to preserve function. Melanomas located more proximally on the fingers can often be managed with wide local excision of soft tissue, skin grafts, or local flaps for soft tissue coverage. NOTE - Longitudinal melanonychia occurs in other conditions, including benign nevi of the nail matrix and the multiple linear streaks that are common in people with dark skin. However, patients with a solitary, widening, irregularly shaped, or irregularly pigmented streak in the nail should undergo a biopsy of the nail matrix to evaluate for melanoma. (Option A) Nail apparatus melanoma accounts for 1.5-3% of all melanomas. It is not the most common form of melanoma. (Option B) Nail apparatus melanoma has a poor prognosis. (Option D) Nail removal has no role in the management of melanoma, as the lesion is in the subungual matrix. (Option E) Nail apparatus melanomas occur with almost equal incidence in people with black skin, Asians, and Caucasians, and in people in tropical versus nontropical climates, sun exposure does not seem to be an etiology.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0005",
    topic: "Dermatology",
    subtopic: "Squamous Cell Carcinoma (SCC) - Risk Factors",
    stem: `John, 42 years old, presents to your GP clinic to discuss skin cancer prevention. His past medical history is significant for a cutaneous squamous cell carcinoma (SCC) excised which was successfully treated years ago. He has fair skin with a tendency to tan rather than burn. He denies a history of sunburns as a child. Which one of the following is the most significant risk factor for developing another SCC?`,
    options: [
      { label: "A", text: `Tendency to tan rather than burn with sun exposure.` },
      { label: "B", text: `History of SCC.` },
      { label: "C", text: `His age.` },
      { label: "D", text: `Absence of sunburns in childhood.` },
      { label: "E", text: `Fair skin.` },
    ],
    correctAnswer: "B",
    explanation: `SCC is the second most common skin cancer in Australia after basal cell carcinoma. Risk factors for SCC are: Unprotected exposure to ultraviolet (UV) radiation from the sun or tanning bed; Age over 50; Male gender; Fair skin (Fitzpatrick I and II); Immunosuppression; Personal history of skin cancers (non-melanoma or melanoma); History of human papillomavirus (HPV) infection; Precancerous skin lesions such as Bowen's disease and actinic keratosis (AK); Chronic infections and skin inflammation from burns, scars, and other conditions. Of these risk factors, the presence of another SCC in history has the most significance (high risk). Fair skin (option E) is another high-risk factor for SCC but not as significant as the history of another SCC. In the absence of past history of skin cancer, it would be the correct answer. He is under 50 and his age (option C) is not a risk factor for now. He tends to tan rather than burn (option A) which is a protective factor. While childhood sunburns are a risk factor, their absence (option D) is not one.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0006",
    topic: "Dermatology",
    subtopic: "Cellulitis - Management",
    stem: `A 51-year-old man presents to the hospital with a swollen hand shown in the following photograph. He was gardening in his courtyard yesterday when his left index finger was injured. This morning, he noticed that his left hand is tender, swollen, and red. On examination, he has a blood pressure of 134/78 mmHg, a pulse of 88, a respiratory rate of 16 breaths/min, and a temperature of 38.1°C. Which one of the following is the most appropriate next step in management?`,
    options: [
      { label: "A", text: `Ultrasound of the hand.` },
      { label: "B", text: `MRI of the hand.` },
      { label: "C", text: `Admission to the hospital and commencement of intravenous antibiotics.` },
      { label: "D", text: `CT scan of the hand.` },
      { label: "E", text: `Discharge him home on oral antibiotics and review in 24-48 hours.` },
    ],
    correctAnswer: "E",
    explanation: `The swollen, red, and tender hand following a recent injury makes cellulitis the most likely diagnosis. Cellulitis is a clinical diagnosis and no imaging studies such as ultrasound (option A), MRI (option B), or CT scan (option D) are required. Streptococcus pyogenes (S.pyogenes) or other Streptococcus species such as group B, C, or G are the most common causes of nonpurulent, recurrent (e.g., associated with lymphedema), or spontaneous rapidly spreading cellulitis. Staphylococcus aureus is less common for cellulitis and is often associated with penetrating trauma, ulceration, or an abscess. Purulent cellulitis is typically caused by Staphylococcus aureus. Antibiotics are the mainstay of treatment. Oral antibiotics are adequate for cellulitis not associated with systemic features and are usually appropriate for patients with a single systemic feature of infection (e.g., fever alone). For adults with two or more of the following clinical features, admission to the hospital and commencement of intravenous antibiotics (option C) should be used initially: Temperature more than 38°C or less than 36°C; Heart rate of more than 90 bpm; Respiratory rate of more than 20 breaths/minute; White cell count more than 12x10⁹/L or less than 4x10⁹/L, or more than 10% immature (band) forms. Other indications for initial intravenous antibiotics (even without having 2 or more of the above) are: Intolerance of oral therapy; Immunocompromised patients; Comorbidities that could be associated with the rapid progression of cellulitis such as diabetes mellitus; Early follow-up is not possible. Patients who are discharged on oral antibiotics require early assessment (within 24-48 hours) for treatment response. For this patient with a fever of 38.1°C as the only concerning factor besides the cellulitis, discharging home on oral antibiotics with an early review is the most appropriate option to consider at this stage. Intravenous antibiotics should be considered next if the response to oral therapy is unsatisfactory. Other advice to give this patient is rest and elevation of the affected area.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0007",
    topic: "Dermatology",
    subtopic: "Pyogenic Granuloma - Diagnosis",
    stem: `Jane, 21 years old, presents with a painless lesion on the distal interphalangeal joint of her right middle finger. The lesion has been present for the past 2 months and increased in size. The lesion is shown in the following photograph. On examination, she is otherwise healthy. Which one of the following is the most likely diagnosis?`,
    options: [
      { label: "A", text: `Abscess.` },
      { label: "B", text: `Pyoderma gangrenosum.` },
      { label: "C", text: `Pyogenic granuloma.` },
      { label: "D", text: `Basal cell carcinoma.` },
      { label: "E", text: `Epidermoid cyst.` },
    ],
    correctAnswer: "C",
    explanation: `The fleshy red lesion on the distal interphalangeal joint of this patient is consistent with the diagnosis of pyogenic granuloma (PG). PG is a common benign acquired vascular neoplasm of the skin and mucous membrane. The etiology is unknown. Some think it might be due to minor trauma, especially for PGs of fingers. Pyogenic granuloma is a misnomer because the lesion is neither pyogenic nor granuloma. It is an erythematosus (fleshy red) dome-shaped papule or nodule that bleeds easily and is prone to ulceration, erosion, and crusting. It is most often seen in adolescents and young adults. Up to 5% of pregnant women may experience it. Although very rare, PGs have been reported in the gastrointestinal tract, the larynx, nasal mucosa, conjunctiva, and cornea. (Options A, D, and E) Abscess, epidermoid cyst, and mucous cyst are covered with skin. (Option B) Pyoderma gangrenosum typically presents with a well-defined border, which is usually violet or blue.`,
    reference: "amc",
    difficulty: "easy",
  },
  {
    id: "derm-amedex-0009",
    topic: "Dermatology",
    subtopic: "Tinea infection",
    stem: `A photograph shows multiple round lesions of different sizes over the face, chest, abdomen, and arm. The lesions have prominent circular edges with centers being clear. With itchiness in the history, which one of the following could be the most likely diagnosis?`,
    options: [
      { label: "A", text: `Tinea infection.` },
      { label: "B", text: `Psoriasis.` },
      { label: "C", text: `Contact dermatitis.` },
      { label: "D", text: `Allergic drug reaction.` },
      { label: "E", text: `Tinea versicolor.` },
    ],
    correctAnswer: "A",
    explanation: `The photograph shows multiple round lesions of different sizes with prominent circular edges and central clearing, characteristic of tinea (dermatophytic infection). Tinea is caused by dermatophytes fungi and presents with annular or arcuate (arc-shaped) lesions that are scaly and itchy, with definite edges and central clearing as it expands. Psoriasis is characterized by erythematous patches distributed symmetrically with silvery scaling, lacking central clearing. Contact dermatitis causes itchy scaly erythematous rash without central clearing. Allergic drug reactions (e.g., cotrimoxazole) can cause various clinical pictures including itchy erythematous rash but without central clearing, and wheels (hives) have clear centers but differ in appearance from those shown. Tinea versicolor presents with hypo/hyperpigmented macules of different sizes with slight scaling and itching but no central clearing.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0010",
    topic: "Dermatology",
    subtopic: "Cellulitis",
    stem: `A 60-year-old man presents to your clinic with complaints of fever and a painful swollen right thigh. He has diabetes well controlled on metformin 500mg 8-hourly and hypertension for which he is taking valsartan 80mg daily. He is on atorvastatin 20 mg daily for hypercholesterolemia as well. His recent medical history is remarkable for deep vein thrombosis (DVT) of his right leg, for which he is currently on warfarin. One week ago, he was admitted to the hospital after one episode of syncope and started on amiodarone after he was diagnosed with ventricular tachycardia (VT). Physical examination is remarkable for a temperature of 38.3°C and a warm swollen tender right thigh that is erythematous. The right thigh circumference is 3 cm greater than that of the left thigh. Which one of the following could be the most likely cause of this presentation?`,
    options: [
      { label: "A", text: `Deep vein thrombosis (DVT).` },
      { label: "B", text: `Cellulitis.` },
      { label: "C", text: `Drug interaction.` },
      { label: "D", text: `Hematoma.` },
      { label: "E", text: `Rhabdomyolysis.` },
    ],
    correctAnswer: "B",
    explanation: `At first glance, there are multiple differential diagnoses for a swollen painful thigh including DVT, cellulitis, and hematoma. The patient is on warfarin for treatment of a previous DVT, which is a risk factor for another venous thromboembolic event (VTE) such as another DVT or pulmonary embolism (PE). However, it is less likely, yet not impossible, for this patient to develop another VTE while on treatment with warfarin. Therefore, DVT of the right leg (option A) is a weak possibility. The interaction between warfarin and amiodarone is well-known. Amiodarone results in decreased metabolization of warfarin through hepatic pathways and leads to increased bleeding tendency. Considering that the patient has been recently started on amiodarone while on warfarin, a hematoma (option D) can also be a possibility. However, the presence of fever, warmth, and erythema of the swelling makes this diagnosis less likely. Pressure from a hematoma on surrounding tissues such as skin or deeper layers (e.g., muscles) can compromise circulation and results in complications such as necrosis or a superimposed infection that can justify, to some extent, the clinical picture; however, the expected sequence would be hematoma formation first and then the development of signs such as tenderness, warmth, and erythema later. It is also worth reminding that hematomas present as bruises or bluish not red discoloration. Hematomas are not warm and are often non-tender. Swelling is a feature though. Drug interaction (option C) between warfarin and amiodarone can result in increased bleeding tendency and the development of a hematoma, and interaction between atorvastatin and amiodarone can lead to an increased potential for the development of statin-related muscle problems. None of these events are associated with the given presentation and are very unlikely to be the cause of this clinical picture. Rhabdomyolysis (option E) is a serious condition followed by muscle fibers breakdown and release of muscle cell contents such as myoglobin and potassium. Myoglobinuria results in the deposition of myoglobin in the kidneys and renal failure. Release of excess potassium from damaged muscle cells leads to hyperkalemia and serious complications such as cardiac arrhythmias. Statins such as atorvastatin and simvastatin in particular are metabolized by cytochrome P450-3A4 (CYP3A4), and amiodarone is a potent inhibitor of this cytochrome. Concomitant use of amiodarone and statins can result in increased activity of statins and rises the likelihood of statin-related adverse effects such as muscular pain, myopathy, and rarely rhabdomyolysis. However, in the event of statin-induced rhabdomyolysis, a systemic presentation is expected. Rhabdomyolysis never causes the focal signs mentioned in the scenario. Of the given options, this clinical picture is most consistent with cellulitis of the left thigh as the most likely diagnosis. Cellulitis presents with systemic signs such as fever and focal findings of induration, warmth, redness, and tenderness of the affected area. Diabetes can be a risk factor.`,
    reference: "amc",
    difficulty: "hard",
  },
  {
    id: "derm-amedex-0011",
    topic: "Dermatology",
    subtopic: "Seborrheic keratosis",
    stem: `John, 60 years of age, presents to your office because he is concerned about a skin lesion on his forearm. The dermatoscopic view of the lesion is shown in the following photograph. Which one of the following could be the most likely diagnosis?`,
    options: [
      { label: "A", text: `Actinic keratosis.` },
      { label: "B", text: `Bowen's disease.` },
      { label: "C", text: `Malignant melanoma.` },
      { label: "D", text: `Dermatosis papulosa nigra.` },
      { label: "E", text: `Seborrheic keratosis.` },
    ],
    correctAnswer: "E",
    explanation: `The photograph shows an oval brown plaque on a sun-exposed area in an old man. There is also keratotic plugging in the surface of the lesion (yellowish-colored). These features are characteristic of seborrheic keratosis as the most likely diagnosis. Seborrheic keratosis (SK) is the most common benign skin tumor in older adults with the incidence increasing with age. It is typically oval or round and brown lesions mostly in sun-exposed areas with adherent greasy scales. The color may range from black to tan. Usually, SK has a velvety verrucous (warty) surface and appears stuck on. However, some lesions are so verrucous that may resemble warts. (Option A) Actinic keratosis is characterized by flat small scaly lesions on the sun-exposed area of old adults, especially the back of the hands. Lesions can be multiple. Actinic keratosis is precancerous with the potential to become squamous cell carcinoma. (Option B) Bowen's disease, similar to AK, is seen in the sun-damaged area of skin in older adults and is precancerous. It is flat and scaly such as AK but is larger in diameter and tends to be thicker with well-demarcated borders. (Option C) Malignant melanoma commonly presents with a rather flat lesion of various colors and irregular borders and shapes. Although nodular melanomas can present with a pigmented dome-shaped lesion, the commonality of SK, the presence of keratotic plugs, and the lack of color variety make malignant nodular melanoma a far less likely diagnosis compared to SK. (Option D) Dermatosis papulosa nigra is a variant of SK consisting of multiple brown-black dome-shaped, small papules found in the face of young to middle-aged people with colored skin, especially black. This single lesion on the forearm of an old man is SK not its variant dermatosis papulosa nigra.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0012",
    topic: "Dermatology",
    subtopic: "Ramsay Hunt syndrome",
    stem: `Jane, 53 years, presents to your GP practice with facial weakness, right ptosis, and drooling from the right corner of her mouth since this morning. She mentions a history of right ear pain a few days earlier. On examination, an erythematous vesicular rash is noted in the right ear canal. Which one of the following would be the most appropriate next step in management?`,
    options: [
      { label: "A", text: `Oral aciclovir.` },
      { label: "B", text: `Oral prednisone.` },
      { label: "C", text: `Methotrexate.` },
      { label: "D", text: `Clindamycin.` },
      { label: "E", text: `Gabapentin.` },
    ],
    correctAnswer: "A",
    explanation: `The clinical findings and history suggest Ramsay Hunt syndrome as the most likely diagnosis. The syndrome is defined as an acute peripheral facial neuropathy caused by the reactivation of a latent varicella-zoster virus infection. The syndrome is associated with an erythematous vesicular rash of the skin of the ear canal, auricle (also known as herpes zoster oticus), and/or oropharyngeal mucous membrane. Varicella zoster virus (VZV) infection causes two distinct clinical syndromes. Primary infection, also known as varicella or chickenpox, is a common pediatric viral disease. After a chickenpox infection, VZV remains latent in the neurons of cranial nerves and dorsal root ganglia. Subsequent reactivation of latent VZV can result in a vesicular rash in a dermatomal distribution, known as herpes zoster. VZV infection or reactivation involving the geniculate ganglion of the 7th cranial nerve (CN VII) within the temporal bone is the main pathophysiological mechanism of Ramsay-Hunt syndrome. Ramsay-Hunt syndrome is estimated to account for 16% of all causes of unilateral facial palsies in children, and 18% of facial palsies in adults. Ramsay Hunt syndrome is thought to be the cause of as many as 20% of clinically diagnosed cases of Bell palsy. Although VZV reactivation is the cause in most cases of this syndrome, herpes simplex virus (HSV) II has been implicated in some cases. The syndrome usually presents with paroxysmal pain deep within the ear. The pain often radiates outward into the pinna of the ear and may be associated with a more constant, diffuse, and dull background pain. The onset of pain usually precedes the rash by several hours or even days. The classic triad includes (1) ipsilateral facial palsy, (2) ear pain, and (3) vesicles in the auditory canal and auricle. In some patients taste perception, hearing (tinnitus, hyperacusis), and lacrimation may occur. Ramsay-Hunt syndrome is generally considered a polycranial neuropathy, with frequent involvement of cranial nerves V, IX, and X. With the involvement of the geniculate ganglion, the inflammation can spread to the 8th cranial nerve (CN VIII), resulting in auditory and vestibular disorders. Clinical manifestations of Ramsay Hunt syndrome may include: vesicular rash of the ear or mouth (as many as 80% of cases); the rash might precede the onset of facial paresis/palsy (involvement of the seventh cranial nerve [CN VIII]); ipsilateral lower motor neuron facial paresis/palsy (CN VII); vertigo and ipsilateral hearing loss (CN VIII); tinnitus; hyperacusis; otalgia (ear pain); headaches; dysarthria; gait ataxia; fever; cervical lymphadenopathy; facial weakness usually reaches maximum severity by one week after the onset of symptoms; other cranial neuropathies might be present and may involve cranial nerves (CNs) VIII, IX, X, V, and VI; ipsilateral hearing loss has been reported in as many as 50% of cases; blisters of the skin of the ear canal, auricle, or both may become secondarily infected, causing cellulitis. Antiviral treatment should be started in all patients within 72 hours of the onset of the rash. This time limit does not apply to patients with herpes zoster ophthalmicus and immunocompromised patients, meaning that such patients should receive antiviral therapy even beyond 72 hours of presentation. Treatment options include famciclovir, valaciclovir, and aciclovir. NOTE - Aciclovir is the preferred medication in children and pregnant women. For this patient, oral acyclovir is the most appropriate option to consider as the next step in management. (Option A) Therapy with oral corticosteroids (e.g. prednisolone daily for 7 days, tapering to 5 mg daily over the next 2 weeks) can reduce symptoms in the acute (inflammatory) phase of herpes zoster, but only when used in combination with an antiviral agent. Corticosteroids are recommended for patients over the age of 50 if not contraindicated and should be used with caution in patients with comorbid conditions such as diabetes. (Option C) Methotrexate has no role in the treatment of herpes zoster. (Option D) Antibiotics other than mentioned antiviral agents are ineffective in treating herpes zoster. (Option E) Gabapentin and tricyclic antidepressants are the most effective treatment options for neuropathic pain associated with herpes zoster infection, but given the time of presentation, antiviral therapy should be considered as the cornerstone of therapy first.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0013",
    topic: "Dermatology",
    subtopic: "Intradermal nevus",
    stem: `Which one of the following lesions of squamous epithelium is not premalignant?`,
    options: [
      { label: "A", text: `Solar (actinic) keratosis.` },
      { label: "B", text: `Leukoplakia.` },
      { label: "C", text: `Intradermal nevus.` },
      { label: "D", text: `Bowen's disease.` },
      { label: "E", text: `Chronic radiation dermatitis.` },
    ],
    correctAnswer: "C",
    explanation: `Of the given options, the only one not associated with skin cancers is intradermal nevus. Benign melanocytic nevi have three major types, classified according to the position of the melanocytes in relation to epidermal: Intradermal nevus: all of the nevus cells are within dermis. This type accounts for a majority of benign congenital nevi. Junctional nevus: the nevus cells are located at the junction of the basal epidermal layers and dermis. Combined nevus: nevus cells are both intradermal and junctional. (Option A) Solar (actinic) keratosis is usually a raised plaque usually on sun-exposed area of the skin. It is a precursor of SCC. (Option B) Leukoplakia is whitish lesion in the oral cavity and associated with SCC. (Option D) Bowen disease is considered SCC in situ, and is malignant. (Option E) Chronic radiation dermatitis may result in SCC.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0014",
    topic: "Dermatology",
    subtopic: "Contact dermatitis",
    stem: `Which one of the following statements regarding contact dermatitis is not correct?`,
    options: [
      { label: "A", text: `Plants are the most common cause of contact dermatitis.` },
      { label: "B", text: `It can be treated with topical steroids.` },
      { label: "C", text: `It can be treated with oral steroids.` },
      { label: "D", text: `The application of skin moisturisers can assist the healing process.` },
      { label: "E", text: `Avoidance of the allergen is essential to the prevention of further flare-ups.` },
    ],
    correctAnswer: "A",
    explanation: `Allergic contact dermatitis is a type 4 or delayed hypersensitivity reaction and occurs 48-72 hours after exposure to the allergen. The mechanism involves CD4+ T-lymphocytes and the release of cytokines that activate the immune system and cause dermatitis. Contact allergy occurs predominantly from an allergen on the skin rather than from internal sources or food. Of note is that a patient might have been in contact with the allergen for years without it causing dermatitis. Even small quantities of an allergen can induce dermatitis. Allergic contact dermatitis is especially common in metal workers, hairdressers, beauticians, healthcare workers, cleaners, painters, and florists. Patients with impaired barrier function are more prone to contact dermatitis. Allergic contact dermatitis develops hours after contact with the responsible material and settles down over a few days, provided the skin is no longer in contact with the allergen. The condition is often limited to the contact site with the allergen, but it may extend outside the contact area or become generalised. Transmission from the fingers can lead to dermatitis on the eyelids and genitals. Therefore, the mainstay of the treatment is preventing further contact with the allergen. A skin patch test may be required to find the culprit. Active lesions are often treated with topical steroids (option B). More severe cases may necessitate a short course of oral steroids (option C). Other treatment options can include phototherapy/photochemotherapy, immune suppressants such as azathioprine or ciclosporin, or immune system modulators tacrolimus ointment depending on the severity and the clinical course. The application of skin moisturisers (option D) can promote general skin health conditions, alleviate the symptoms, and accelerate the healing process. Although plants can cause contact dermatitis, they are not the most common cause. Nickel and other metals/chemicals are the most common cause.`,
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "derm-amedex-0015",
    topic: "Dermatology",
    subtopic: "Multiple symmetrical subcutaneous lipomas",
    stem: `A 50-year-old woman presents to your clinic with multiple lumps. She has had these lumps for 20 years. The only complaint, apart from her concerns about the look of the lumps, is that they become painful at times. On examination, about 30 mobile subcutaneous lumps feel soft, rubbery, and lobulated when palpated. They are distributed bilaterally in her upper and lower extremities, chest, and back. She mentions that her mother has the same problem. She is otherwise healthy. Which one of the following is the most likely diagnosis?`,
    options: [
      { label: "A", text: `Adipose dolorosa.` },
      { label: "B", text: `Multiple desmoid tumors.` },
      { label: "C", text: `Multiple epidermoid cysts.` },
      { label: "D", text: `Multiple symmetrical subcutaneous lipomas.` },
      { label: "E", text: `Neurofibromatosis type I (Von Recklinghausen disease of nerve).` },
    ],
    correctAnswer: "D",
    explanation: `The clinical presentation of multiple soft, rubbery, lobulated subcutaneous lumps distributed bilaterally in the extremities, chest, and back, with a long history (20 years) and family history (mother affected), is most consistent with multiple symmetrical subcutaneous lipomas. Lipomas are benign fatty tumors that are common, mobile, soft, and painless or occasionally painful. The presence of multiple lipomas with bilateral symmetric distribution and positive family history is characteristic of this condition.`,
    reference: "amc",
    difficulty: "easy",
  },
];
