export interface MCQuestion {
  id: string;
  topic: string;
  subtopic: string;
  stem: string;
  options: { label: string; text: string }[];
  correctAnswer: string;
  explanation: string;
  reference: "murtagh" | "amc" | "racgp-redbook" | "other";
  difficulty: "easy" | "medium" | "hard";
}

export const seedQuestions: MCQuestion[] = [
  // ── CARDIOVASCULAR ──────────────────────────────────────────────
  {
    id: "q-001",
    topic: "Cardiovascular",
    subtopic: "Ischaemic Heart Disease",
    stem: "A 58-year-old man presents with sudden onset central chest pain radiating to his left arm for 90 minutes. He is diaphoretic and pale. His ECG shows ST elevation in leads II, III, and aVF. Which artery is most likely occluded?",
    options: [
      { label: "A", text: "Left anterior descending artery" },
      { label: "B", text: "Right coronary artery" },
      { label: "C", text: "Left circumflex artery" },
      { label: "D", text: "Left main coronary artery" },
      { label: "E", text: "Posterior descending artery" },
    ],
    correctAnswer: "B",
    explanation: "ST elevation in II, III, aVF = inferior STEMI. The inferior wall is supplied by the RCA in ~80% of cases (right-dominant circulation). Left circumflex supplies inferior wall in left-dominant systems (~20%).",
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "q-002",
    topic: "Cardiovascular",
    subtopic: "Heart Failure",
    stem: "A 72-year-old woman with known heart failure presents with worsening dyspnoea, orthopnoea and bilateral ankle oedema. Her BNP is markedly elevated. Echocardiogram shows EF of 35%. Which medication has been shown to reduce mortality in this condition?",
    options: [
      { label: "A", text: "Digoxin" },
      { label: "B", text: "Amlodipine" },
      { label: "C", text: "Carvedilol" },
      { label: "D", text: "Furosemide" },
      { label: "E", text: "Nitrates" },
    ],
    correctAnswer: "C",
    explanation: "Beta-blockers (carvedilol, bisoprolol, metoprolol succinate) reduce mortality in HFrEF (EF <40%). Furosemide and digoxin improve symptoms but not mortality. ACEi/ARBs and SGLT2 inhibitors also reduce mortality.",
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "q-003",
    topic: "Cardiovascular",
    subtopic: "Hypertension",
    stem: "According to RACGP guidelines, what is the recommended first-line treatment for a 55-year-old Aboriginal Australian man with newly diagnosed hypertension (BP 158/95) and no other comorbidities?",
    options: [
      { label: "A", text: "Beta-blocker" },
      { label: "B", text: "ACE inhibitor" },
      { label: "C", text: "Calcium channel blocker" },
      { label: "D", text: "Thiazide diuretic" },
      { label: "E", text: "Lifestyle measures alone for 6 months" },
    ],
    correctAnswer: "B",
    explanation: "ACE inhibitors are first-line for Aboriginal and Torres Strait Islander peoples with hypertension due to high rates of renal disease and cardiovascular risk. ACEi provide renoprotection beyond BP lowering.",
    reference: "racgp-redbook",
    difficulty: "medium",
  },

  // ── RESPIRATORY ─────────────────────────────────────────────────
  {
    id: "q-004",
    topic: "Respiratory",
    subtopic: "Asthma",
    stem: "A 22-year-old woman with known asthma presents with wheeze and SOB. Her PEFR is 40% of predicted. She has not improved after 3 doses of salbutamol. What is the MOST appropriate next step?",
    options: [
      { label: "A", text: "Discharge with oral prednisolone" },
      { label: "B", text: "IV magnesium sulphate" },
      { label: "C", text: "Add ipratropium bromide nebuliser" },
      { label: "D", text: "Intubate and ventilate" },
      { label: "E", text: "Repeat salbutamol every 20 minutes" },
    ],
    correctAnswer: "C",
    explanation: "PEFR 33-50% = moderate-severe attack. After 3 rounds of salbutamol without improvement, add ipratropium bromide (anticholinergic). Magnesium is for life-threatening asthma (PEFR <33%). Intubation is last resort.",
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "q-005",
    topic: "Respiratory",
    subtopic: "COPD",
    stem: "A 65-year-old male smoker (40 pack-years) with COPD has FEV1/FVC of 0.62 and FEV1 55% predicted. He has 2 exacerbations per year requiring oral steroids. Which inhaler regimen is most appropriate?",
    options: [
      { label: "A", text: "SABA alone" },
      { label: "B", text: "LABA alone" },
      { label: "C", text: "LAMA alone" },
      { label: "D", text: "LABA + ICS" },
      { label: "E", text: "LAMA + LABA + ICS (triple therapy)" },
    ],
    correctAnswer: "E",
    explanation: "GOLD Group E (high exacerbation risk, ≥2 moderate or ≥1 hospitalisation). Triple therapy (LAMA+LABA+ICS) reduces exacerbations compared to dual therapy in this group. ICS indicated when eosinophils >300 or frequent exacerbations.",
    reference: "amc",
    difficulty: "hard",
  },
  {
    id: "q-006",
    topic: "Respiratory",
    subtopic: "Pneumonia",
    stem: "A 45-year-old previously well man presents with 3 days of fever, productive cough, and pleuritic chest pain. CXR shows right lower lobe consolidation. His CURB-65 score is 1. What is the most appropriate management?",
    options: [
      { label: "A", text: "Admit for IV piperacillin-tazobactam" },
      { label: "B", text: "Admit for IV ceftriaxone + azithromycin" },
      { label: "C", text: "Oral amoxicillin and discharge home" },
      { label: "D", text: "Oral doxycycline and discharge home" },
      { label: "E", text: "CT chest before treatment" },
    ],
    correctAnswer: "C",
    explanation: "CURB-65 score 0-1 = low severity CAP, treat as outpatient. Amoxicillin is first-line for typical CAP in Australia (Therapeutic Guidelines). Doxycycline is used if atypical organism suspected or penicillin allergy.",
    reference: "amc",
    difficulty: "easy",
  },

  // ── GASTROENTEROLOGY ────────────────────────────────────────────
  {
    id: "q-007",
    topic: "Gastroenterology",
    subtopic: "Appendicitis",
    stem: "A 32-year-old woman presents with right lower quadrant pain for 18 hours, nausea, and low-grade fever (37.8°C). WCC 14.5. CRP 45. Urine: trace blood. Which is the MOST important initial investigation?",
    options: [
      { label: "A", text: "CT abdomen and pelvis with contrast" },
      { label: "B", text: "Diagnostic laparoscopy" },
      { label: "C", text: "Serum beta-hCG" },
      { label: "D", text: "Abdominal X-ray" },
      { label: "E", text: "MRI abdomen" },
    ],
    correctAnswer: "C",
    explanation: "In any woman of reproductive age with lower abdominal pain, beta-hCG must be checked FIRST to exclude ectopic pregnancy — a life-threatening condition that mimics appendicitis. This takes priority before imaging.",
    reference: "murtagh",
    difficulty: "medium",
  },
  {
    id: "q-008",
    topic: "Gastroenterology",
    subtopic: "Upper GI Bleed",
    stem: "A 60-year-old man on aspirin and ibuprofen presents with haematemesis and melaena. BP 95/60, HR 118. Hb 78 g/L. What is the FIRST priority?",
    options: [
      { label: "A", text: "Urgent endoscopy" },
      { label: "B", text: "IV proton pump inhibitor" },
      { label: "C", text: "Two large-bore IV cannulas and fluid resuscitation" },
      { label: "D", text: "Transfuse packed red cells" },
      { label: "E", text: "Stop aspirin and ibuprofen" },
    ],
    correctAnswer: "C",
    explanation: "ABC first — haemodynamic stabilisation precedes endoscopy. Two large-bore IV cannulas and fluid resuscitation (crystalloid initially). Transfuse if Hb <70 or haemodynamically unstable. Endoscopy within 24h once stable. IV PPI reduces rebleeding but is not the first step.",
    reference: "amc",
    difficulty: "easy",
  },

  // ── NEUROLOGY ───────────────────────────────────────────────────
  {
    id: "q-009",
    topic: "Neurology",
    subtopic: "Headache",
    stem: "A 35-year-old woman presents with sudden severe headache she describes as 'the worst headache of my life', neck stiffness and photophobia. CT head is normal. What is the NEXT most important investigation?",
    options: [
      { label: "A", text: "MRI brain with contrast" },
      { label: "B", text: "Lumbar puncture" },
      { label: "C", text: "EEG" },
      { label: "D", text: "Carotid Doppler" },
      { label: "E", text: "Discharge with analgesics and review in 24 hours" },
    ],
    correctAnswer: "B",
    explanation: "Thunderclap headache + normal CT = LP is mandatory to exclude SAH. CT misses up to 5% of SAH. LP looks for xanthochromia at 12 hours post-onset. Never discharge without excluding SAH.",
    reference: "murtagh",
    difficulty: "medium",
  },
  {
    id: "q-010",
    topic: "Neurology",
    subtopic: "Stroke",
    stem: "A 68-year-old man presents with acute onset right-sided weakness and dysphasia for 1.5 hours. CT head shows no haemorrhage. His BP is 185/105. What is the most appropriate management?",
    options: [
      { label: "A", text: "Aggressive BP lowering to <140 before thrombolysis" },
      { label: "B", text: "IV alteplase if no contraindications" },
      { label: "C", text: "Aspirin 300mg immediately and observe" },
      { label: "D", text: "Wait for MRI before any intervention" },
      { label: "E", text: "Heparin infusion" },
    ],
    correctAnswer: "B",
    explanation: "Ischaemic stroke within 4.5 hours — IV alteplase is indicated if no contraindications. BP should only be lowered to <185/110 before thrombolysis (not aggressively lower). Aspirin alone is inadequate in the thrombolysis window.",
    reference: "amc",
    difficulty: "medium",
  },

  // ── ENDOCRINOLOGY ───────────────────────────────────────────────
  {
    id: "q-011",
    topic: "Endocrinology",
    subtopic: "Diabetes",
    stem: "According to RACGP Red Book guidelines, which of the following is recommended for a 52-year-old man with well-controlled Type 2 Diabetes?",
    options: [
      { label: "A", text: "HbA1c every 6 months, annual retinal review, annual foot exam" },
      { label: "B", text: "HbA1c annually, biennial retinal review, 5-yearly foot exam" },
      { label: "C", text: "HbA1c every 3 months, 6-monthly retinal review, annual foot exam" },
      { label: "D", text: "HbA1c every 6 months, biennial retinal review, annual foot exam" },
      { label: "E", text: "HbA1c annually, annual retinal review, annual foot exam" },
    ],
    correctAnswer: "A",
    explanation: "RACGP Red Book: HbA1c 6-monthly for T2DM. Annual dilated retinal exam (biennial if well-controlled and no retinopathy). Annual comprehensive foot examination. Annual urine ACR and eGFR.",
    reference: "racgp-redbook",
    difficulty: "easy",
  },
  {
    id: "q-012",
    topic: "Endocrinology",
    subtopic: "Thyroid",
    stem: "A 38-year-old woman presents with weight loss, palpitations, heat intolerance, and a fine tremor. TSH <0.01, free T4 elevated. Eye examination shows proptosis. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Toxic multinodular goitre" },
      { label: "B", text: "Graves' disease" },
      { label: "C", text: "De Quervain's thyroiditis" },
      { label: "D", text: "Hashimoto's thyroiditis" },
      { label: "E", text: "Toxic adenoma" },
    ],
    correctAnswer: "B",
    explanation: "Graves' disease is the only cause of hyperthyroidism associated with ophthalmopathy (proptosis, lid lag). It is autoimmune (TSH receptor antibodies). De Quervain's is painful subacute thyroiditis. Toxic MNG and adenoma don't cause eye disease.",
    reference: "murtagh",
    difficulty: "easy",
  },

  // ── PSYCHIATRY ──────────────────────────────────────────────────
  {
    id: "q-013",
    topic: "Psychiatry",
    subtopic: "Postnatal Depression",
    stem: "A 27-year-old woman at 8 weeks postpartum scores 14 on the EPDS. She denies thoughts of self-harm. What is the MOST appropriate initial management?",
    options: [
      { label: "A", text: "Immediate psychiatric admission" },
      { label: "B", text: "Prescribe sertraline and review in 4 weeks" },
      { label: "C", text: "Reassure — normal baby blues, review in 2 weeks" },
      { label: "D", text: "Psychoeducation, social support, CBT referral, close GP follow-up" },
      { label: "E", text: "Benzodiazepine for short-term anxiety relief" },
    ],
    correctAnswer: "D",
    explanation: "EPDS ≥13 = moderate-severe PND. Without safety concerns, first-line is psychoeducation, social support, and psychological therapy (CBT/IPT). Medication (sertraline) added for moderate-severe. Baby blues resolve by 2 weeks — this is 8 weeks postpartum.",
    reference: "racgp-redbook",
    difficulty: "medium",
  },
  {
    id: "q-014",
    topic: "Psychiatry",
    subtopic: "Depression",
    stem: "A 45-year-old man with moderate depression has failed 2 adequate trials of SSRIs. He has no psychotic features. What is the MOST appropriate next step?",
    options: [
      { label: "A", text: "Add lithium augmentation" },
      { label: "B", text: "Switch to venlafaxine (SNRI)" },
      { label: "C", text: "Refer for ECT" },
      { label: "D", text: "Add antipsychotic" },
      { label: "E", text: "Increase dose of current SSRI" },
    ],
    correctAnswer: "B",
    explanation: "After 2 failed SSRI trials, switching to an SNRI (venlafaxine) is standard next step for treatment-resistant depression. Lithium augmentation and ECT are later options. Antipsychotics are for psychotic depression or augmentation after further failure.",
    reference: "amc",
    difficulty: "medium",
  },

  // ── MUSCULOSKELETAL ─────────────────────────────────────────────
  {
    id: "q-015",
    topic: "Musculoskeletal",
    subtopic: "Back Pain",
    stem: "A 55-year-old man presents with 6 weeks of low back pain radiating to his right leg below the knee with paraesthesia in L5 distribution. Straight leg raise positive at 40°. What is the MOST appropriate management?",
    options: [
      { label: "A", text: "Urgent MRI and surgical referral" },
      { label: "B", text: "Bed rest for 2 weeks" },
      { label: "C", text: "Continue normal activity, NSAIDs, physiotherapy" },
      { label: "D", text: "Immediate CT myelogram" },
      { label: "E", text: "Oral corticosteroids for 5 days" },
    ],
    correctAnswer: "C",
    explanation: "Sciatica without red flags (cauda equina, neurological deterioration) is managed conservatively first: stay active, NSAIDs, physiotherapy. Most resolve within 6-12 weeks. MRI if no improvement at 6 weeks or red flags develop.",
    reference: "murtagh",
    difficulty: "easy",
  },
  {
    id: "q-016",
    topic: "Musculoskeletal",
    subtopic: "Gout",
    stem: "A 52-year-old man presents with acute swelling, erythema and severe pain in the right first MTP joint for 12 hours. Serum urate is 0.52 mmol/L. What is the MOST appropriate immediate treatment?",
    options: [
      { label: "A", text: "Start allopurinol immediately" },
      { label: "B", text: "NSAIDs (e.g. indomethacin) or colchicine" },
      { label: "C", text: "Oral prednisolone" },
      { label: "D", text: "Joint aspiration only" },
      { label: "E", text: "Antibiotics for septic arthritis" },
    ],
    correctAnswer: "B",
    explanation: "Acute gout: NSAIDs or colchicine are first-line. Note: serum urate may be NORMAL during an acute attack. Allopurinol should NOT be started during an acute attack — wait 2-4 weeks after resolution. Prednisolone if NSAIDs/colchicine contraindicated.",
    reference: "murtagh",
    difficulty: "medium",
  },

  // ── OBSTETRICS & GYNAECOLOGY ────────────────────────────────────
  {
    id: "q-017",
    topic: "Obstetrics & Gynaecology",
    subtopic: "Ectopic Pregnancy",
    stem: "A 28-year-old woman presents with 6 weeks amenorrhoea, lower abdominal pain and light vaginal bleeding. BP 90/60, HR 120, urine hCG positive. What is the MOST appropriate immediate step?",
    options: [
      { label: "A", text: "Transvaginal ultrasound and discharge if scan normal" },
      { label: "B", text: "IV access, fluids, urgent gynaecology review" },
      { label: "C", text: "IM methotrexate" },
      { label: "D", text: "Serum quantitative hCG and review in 48 hours" },
      { label: "E", text: "Oral analgesia and pelvic rest" },
    ],
    correctAnswer: "B",
    explanation: "Haemodynamically unstable with positive hCG = ruptured ectopic until proven otherwise. This is a surgical emergency. Immediate IV access, fluids, and urgent gynaecology referral/theatre. Methotrexate is for stable, unruptured ectopic.",
    reference: "amc",
    difficulty: "easy",
  },
  {
    id: "q-018",
    topic: "Obstetrics & Gynaecology",
    subtopic: "Cervical Cancer Screening",
    stem: "According to RACGP Red Book, when should cervical screening commence and at what interval for an average-risk Australian woman?",
    options: [
      { label: "A", text: "Age 18, annually" },
      { label: "B", text: "Age 21, every 2 years (Pap smear)" },
      { label: "C", text: "Age 25, every 5 years (HPV test)" },
      { label: "D", text: "Age 25, every 2 years (HPV test)" },
      { label: "E", text: "Age 18, every 5 years (HPV test)" },
    ],
    correctAnswer: "C",
    explanation: "Australia updated to HPV-based cervical screening in 2017. Cervical Screening Test starts at age 25 and is done every 5 years until age 74. No co-test needed. Replaced the 2-yearly Pap smear program.",
    reference: "racgp-redbook",
    difficulty: "easy",
  },

  // ── PAEDIATRICS ─────────────────────────────────────────────────
  {
    id: "q-019",
    topic: "Paediatrics",
    subtopic: "Febrile Child",
    stem: "A 9-month-old presents with fever 39.2°C, irritability and a non-blanching petechial rash on the trunk. He is lethargic. What is the MOST urgent action?",
    options: [
      { label: "A", text: "Blood cultures and admit for observation" },
      { label: "B", text: "IM benzylpenicillin immediately and transfer to hospital" },
      { label: "C", text: "Lumbar puncture to confirm meningitis before antibiotics" },
      { label: "D", text: "Reassure parents and give paracetamol" },
      { label: "E", text: "FBC and CRP and wait for results" },
    ],
    correctAnswer: "B",
    explanation: "Non-blanching petechial rash + fever = meningococcal septicaemia until proven otherwise. Do NOT delay antibiotics for LP. Give IM/IV benzylpenicillin immediately and transfer. In Australia, GIVE penicillin in the community before hospital transfer.",
    reference: "amc",
    difficulty: "easy",
  },
  {
    id: "q-020",
    topic: "Paediatrics",
    subtopic: "Developmental Milestones",
    stem: "A 2-year-old boy has no single words, does not point to objects, makes poor eye contact and does not respond to his name consistently. What is the MOST appropriate action?",
    options: [
      { label: "A", text: "Reassure parents — boys develop slower" },
      { label: "B", text: "Refer to audiology and developmental paediatrician" },
      { label: "C", text: "Suggest more screen time for educational content" },
      { label: "D", text: "Review in 6 months" },
      { label: "E", text: "Refer to speech therapy only" },
    ],
    correctAnswer: "B",
    explanation: "Language delay + poor eye contact + not responding to name = red flags for autism spectrum disorder. Requires urgent referral: audiology (exclude hearing loss) AND developmental paediatrician. Never reassure and delay — early intervention is critical.",
    reference: "murtagh",
    difficulty: "easy",
  },

  // ── INFECTIOUS DISEASE ──────────────────────────────────────────
  {
    id: "q-021",
    topic: "Infectious Disease",
    subtopic: "Sepsis",
    stem: "A 70-year-old woman presents confused, with HR 118, RR 24, BP 88/55, temp 38.9°C, and WCC 18.5. Urine is cloudy. What is the FIRST hour bundle for sepsis?",
    options: [
      { label: "A", text: "Blood cultures, then broad-spectrum antibiotics within 3 hours" },
      { label: "B", text: "CT chest/abdomen to find source before antibiotics" },
      { label: "C", text: "Blood cultures, IV antibiotics, 30mL/kg IV crystalloid, lactate" },
      { label: "D", text: "Urine cultures and targeted antibiotics only" },
      { label: "E", text: "ICU referral before starting antibiotics" },
    ],
    correctAnswer: "C",
    explanation: "Surviving Sepsis Campaign 1-hour bundle: measure lactate, blood cultures before antibiotics, broad-spectrum IV antibiotics, 30mL/kg IV crystalloid if hypotensive/lactate ≥4. Antibiotics within 1 hour — do not delay for CT or cultures.",
    reference: "amc",
    difficulty: "medium",
  },
  {
    id: "q-022",
    topic: "Infectious Disease",
    subtopic: "HIV",
    stem: "A 35-year-old man is newly diagnosed with HIV (CD4 450, viral load 25,000). He is asymptomatic. According to current guidelines, when should antiretroviral therapy be started?",
    options: [
      { label: "A", text: "When CD4 drops below 350" },
      { label: "B", text: "When CD4 drops below 200" },
      { label: "C", text: "Immediately — regardless of CD4 count" },
      { label: "D", text: "Only when symptomatic (AIDS-defining illness)" },
      { label: "E", text: "When viral load exceeds 100,000" },
    ],
    correctAnswer: "C",
    explanation: "Current international guidelines (DHHS, WHO, ASHM): ART should be started immediately in ALL HIV-positive patients regardless of CD4 count or symptoms. Early treatment reduces transmission, immune decline, and non-AIDS complications.",
    reference: "amc",
    difficulty: "medium",
  },

  // ── RENAL ────────────────────────────────────────────────────────
  {
    id: "q-023",
    topic: "Renal",
    subtopic: "AKI",
    stem: "A 65-year-old man on ramipril and metformin has gastroenteritis for 3 days. His creatinine rises from baseline 95 to 310 μmol/L. What is the MOST important immediate step?",
    options: [
      { label: "A", text: "Continue all medications and increase fluid intake orally" },
      { label: "B", text: "Stop ramipril and metformin, IV fluid resuscitation" },
      { label: "C", text: "Start haemodialysis" },
      { label: "D", text: "Nephrology referral before any medication changes" },
      { label: "E", text: "Give IV furosemide to increase urine output" },
    ],
    correctAnswer: "B",
    explanation: "Sick day rules: hold nephrotoxic/renal-excreting drugs during AKI — ramipril (can worsen AKI in dehydration) and metformin (risk of lactic acidosis). IV fluids for pre-renal AKI. 'SADMANS' drugs to hold: sulfonamides, ACEi, diuretics, metformin, aminoglycosides, NSAIDs, SGLT2i.",
    reference: "murtagh",
    difficulty: "medium",
  },

  // ── HAEMATOLOGY ─────────────────────────────────────────────────
  {
    id: "q-024",
    topic: "Haematology",
    subtopic: "Anaemia",
    stem: "A 35-year-old woman has Hb 95 g/L, MCV 68 fL, low serum ferritin, and normal B12/folate. She has heavy menstrual bleeding. What is the MOST likely diagnosis and treatment?",
    options: [
      { label: "A", text: "Anaemia of chronic disease — treat underlying cause" },
      { label: "B", text: "Iron deficiency anaemia — oral iron supplementation" },
      { label: "C", text: "Thalassaemia trait — no treatment needed" },
      { label: "D", text: "B12 deficiency — IM hydroxycobalamin" },
      { label: "E", text: "Haemolytic anaemia — corticosteroids" },
    ],
    correctAnswer: "B",
    explanation: "Microcytic anaemia (low MCV) + low ferritin = iron deficiency anaemia. Heavy menstrual bleeding is the most common cause in premenopausal women. Treat with oral ferrous sulfate 325mg daily. Also investigate source. Thalassaemia has normal/low ferritin but normal/high serum iron.",
    reference: "murtagh",
    difficulty: "easy",
  },
];
