import type { MCQuestion } from "./questions";

export const obsgynQuestions: MCQuestion[] = [
  {
    id: "og-001", topic: "Obstetrics & Gynaecology", subtopic: "Ectopic Pregnancy",
    stem: "A 28-year-old woman presents with 6 weeks amenorrhoea, LIF pain, and PV spotting. BP 90/60, HR 118. Urine hCG positive. USS shows no intrauterine pregnancy, 4 cm adnexal mass, and free fluid in POD. What is the diagnosis and management?",
    options: [
      { label: "A", text: "Threatened miscarriage — bed rest and serial hCG" },
      { label: "B", text: "Ruptured ectopic pregnancy — immediate surgical management" },
      { label: "C", text: "Ovarian cyst rupture — laparoscopy electively" },
      { label: "D", text: "Methotrexate for medical management" },
      { label: "E", text: "IV fluids and observation for 24 hours" },
    ],
    correctAnswer: "B",
    explanation: "Ruptured ectopic pregnancy: haemodynamic instability + positive hCG + empty uterus + adnexal mass + haemoperitoneum. Life-threatening emergency. Immediate resuscitation + emergency surgery (laparoscopy or laparotomy depending on stability). Methotrexate only for unruptured, haemodynamically stable, small ectopic (<3.5 cm), no fetal heartbeat, hCG <5000 IU/L. Anti-D if Rh negative.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "og-002", topic: "Obstetrics & Gynaecology", subtopic: "Pre-eclampsia",
    stem: "A 32-year-old primigravida at 34 weeks presents with BP 158/105, headache, epigastric pain, and 3+ proteinuria on dipstick. Platelet count 88 × 10⁹/L, ALT 210 U/L, creatinine 110 µmol/L. What is the diagnosis?",
    options: [
      { label: "A", text: "Gestational hypertension" },
      { label: "B", text: "Pre-eclampsia with severe features" },
      { label: "C", text: "HELLP syndrome" },
      { label: "D", text: "Acute fatty liver of pregnancy" },
      { label: "E", text: "Chronic hypertension with superimposed pre-eclampsia" },
    ],
    correctAnswer: "C",
    explanation: "HELLP syndrome: Haemolysis (↑LDH, ↓Hb), Elevated Liver enzymes (↑ALT), Low Platelets (<100 × 10⁹/L). Severe form of pre-eclampsia. Features: epigastric/RUQ pain, nausea, hypertension. Fetal and maternal emergency. Management: stabilise, corticosteroids for fetal lung maturity if <34 weeks, definitive treatment = delivery. MgSO4 for seizure prophylaxis.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "og-003", topic: "Obstetrics & Gynaecology", subtopic: "Gestational Diabetes",
    stem: "A 34-year-old woman at 26 weeks gestation has an OGTT result: fasting glucose 5.3 mmol/L, 1-hour 11.5 mmol/L, 2-hour 9.2 mmol/L. What is the diagnosis (ADIPS 2014 criteria) and initial management?",
    options: [
      { label: "A", text: "Normal OGTT — no action" },
      { label: "B", text: "GDM — dietary modification + monitoring, insulin if targets not met" },
      { label: "C", text: "Type 2 DM in pregnancy — immediate insulin" },
      { label: "D", text: "GDM — metformin first-line" },
      { label: "E", text: "Impaired fasting glucose only — retest at 36 weeks" },
    ],
    correctAnswer: "B",
    explanation: "GDM (ADIPS 2014): fasting ≥5.1, 1h ≥10.0, 2h ≥8.5 (any ONE met = GDM). This patient meets 1h criterion (11.5≥10). Initial management: medical nutrition therapy (MNT) + blood glucose monitoring (BGL targets: fasting <5.0, 1h post-meal <7.4, 2h <6.7). Insulin if targets not met within 1–2 weeks. Metformin can be used but placental transfer — insulin preferred.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "og-004", topic: "Obstetrics & Gynaecology", subtopic: "Cervical Cancer",
    stem: "A 45-year-old woman with no prior cervical screening presents with post-coital bleeding and vaginal discharge. Pelvic exam shows an irregular, friable 3 cm cervical mass. Biopsy confirms squamous cell carcinoma. CT pelvis shows no lymph node involvement beyond pelvis. What is the stage and treatment?",
    options: [
      { label: "A", text: "Stage IA — cone biopsy alone" },
      { label: "B", text: "Stage IB2/IIB — chemoradiation" },
      { label: "C", text: "Stage IVA — palliative chemotherapy" },
      { label: "D", text: "Stage IA2 — radical trachelectomy" },
      { label: "E", text: "Stage IB1 — radical hysterectomy" },
    ],
    correctAnswer: "B",
    explanation: "Cervical cancer staging: 3 cm visible tumour confined to cervix = Stage IB2. Treatment for Stage IB2: chemoradiation (concurrent cisplatin + external beam radiotherapy + brachytherapy) — equivalent outcomes to radical hysterectomy. Radical hysterectomy for Stage IA2–IB1. Chemoradiation preferred for larger tumours. HPV 16/18 causes 70% of cervical SCC. Prevent with vaccination + screening.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "og-005", topic: "Obstetrics & Gynaecology", subtopic: "Menorrhagia",
    stem: "A 38-year-old nulliparous woman has heavy menstrual bleeding (changing pad every 2 hours) for 6 months. Pelvic USS shows a 4 cm fibroid (intramural). Hb 98 g/L, iron deficient. She wants to preserve fertility. What is the most appropriate first-line treatment?",
    options: [
      { label: "A", text: "Hysterectomy" },
      { label: "B", text: "Levonorgestrel-releasing IUD (Mirena)" },
      { label: "C", text: "Myomectomy immediately" },
      { label: "D", text: "GnRH agonist (leuprolide)" },
      { label: "E", text: "Oral tranexamic acid during menstruation" },
    ],
    correctAnswer: "B",
    explanation: "Fibroids + menorrhagia, wants fertility preservation: LNG-IUD (Mirena) is first-line medical management — reduces menstrual blood loss by 75–85%, treats anaemia. Tranexamic acid/NSAIDs less effective. GnRH agonists used pre-operatively (reduce fibroid size) but not long-term (bone loss). Myomectomy for fertility preservation if medical management fails or submucosal fibroids. Iron supplementation for anaemia.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "og-006", topic: "Obstetrics & Gynaecology", subtopic: "Endometriosis",
    stem: "A 30-year-old woman has dysmenorrhoea, deep dyspareunia, and subfertility. CA-125 is mildly elevated (58 U/mL). Transvaginal US shows an 8 cm ovarian endometrioma. She wants to conceive. What is the most appropriate management?",
    options: [
      { label: "A", text: "Combined OCP for 6 months" },
      { label: "B", text: "Laparoscopic endometrioma drainage and ablation" },
      { label: "C", text: "IVF immediately" },
      { label: "D", text: "GnRH agonist for 6 months then IVF" },
      { label: "E", text: "Hysterectomy with bilateral salpingo-oophorectomy" },
    ],
    correctAnswer: "B",
    explanation: "Endometrioma ≥4 cm + subfertility: laparoscopic cystectomy (endometrioma drainage and ablation) improves spontaneous pregnancy rates and IVF outcomes (better ovarian stimulation). Surgical diagnosis is gold standard for endometriosis staging. OCP does not improve fertility. GnRH agonist suppresses ovulation — not for women trying to conceive. BSO only for severe refractory disease after family complete.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "og-007", topic: "Obstetrics & Gynaecology", subtopic: "Ovarian Cancer",
    stem: "A 62-year-old postmenopausal woman presents with abdominal bloating, early satiety, and increased abdominal girth over 3 months. CA-125 is 2800 U/mL. USS shows bilateral complex ovarian masses and ascites. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Benign ovarian cysts — laparoscopic oophorectomy" },
      { label: "B", text: "Advanced ovarian carcinoma (epithelial) — staging laparotomy + debulking + chemotherapy" },
      { label: "C", text: "Endometrial cancer — endometrial biopsy" },
      { label: "D", text: "Metastatic GI cancer — colonoscopy" },
      { label: "E", text: "Tuberculous peritonitis — RHEZ therapy" },
    ],
    correctAnswer: "B",
    explanation: "Ovarian cancer presentation: postmenopausal, non-specific symptoms (bloating, early satiety), bilateral masses, markedly elevated CA-125, ascites. Most present Stage III-IV. Epithelial ovarian cancer most common (90%). Primary treatment: staging laparotomy + maximal cytoreductive surgery (debulking) + platinum-based chemotherapy (carboplatin + paclitaxel). CA-125 used for monitoring, not screening.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "og-008", topic: "Obstetrics & Gynaecology", subtopic: "Contraception",
    stem: "A 28-year-old woman requests emergency contraception. She had unprotected sex 48 hours ago. She is breastfeeding a 3-month-old. Which is the most effective option available and safe while breastfeeding?",
    options: [
      { label: "A", text: "Combined oral contraceptive pill (double dose)" },
      { label: "B", text: "Levonorgestrel EC (Plan B) 1.5 mg" },
      { label: "C", text: "Ulipristal acetate (EllaOne)" },
      { label: "D", text: "Copper IUD (most effective EC)" },
      { label: "E", text: "Mifepristone" },
    ],
    correctAnswer: "D",
    explanation: "Copper IUD is the most effective emergency contraception (>99%, can be used up to 5 days, also provides ongoing contraception). Safe while breastfeeding. Levonorgestrel EC: safe in breastfeeding, effective if taken within 72 hours (efficacy decreases over time, less if BMI >75th percentile). Ulipristal: avoid in breastfeeding (secreted in breast milk). Combined OCP not recommended as EC anymore.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "og-009", topic: "Obstetrics & Gynaecology", subtopic: "Antenatal",
    stem: "A 25-year-old woman at 12 weeks gestation has a routine FBE showing Hb 104 g/L, MCV 68 fL. Serum ferritin 6 µg/L. She is vegetarian. What is the appropriate management?",
    options: [
      { label: "A", text: "No action — mild anaemia normal in pregnancy" },
      { label: "B", text: "Oral iron supplementation + dietary advice" },
      { label: "C", text: "IV iron infusion immediately" },
      { label: "D", text: "Check haemoglobin electrophoresis for thalassaemia" },
      { label: "E", text: "Blood transfusion" },
    ],
    correctAnswer: "B",
    explanation: "Iron deficiency anaemia in pregnancy (Hb <110 g/L first trimester, ferritin <30 µg/L): oral iron supplementation (ferrous sulfate 325 mg daily or BD). Dietary advice for vegetarians (legumes, dark leafy greens, vitamin C to enhance absorption, avoid tea with meals). IV iron for: severe anaemia, intolerance of oral iron, or >34 weeks with inadequate response. Check Hb electrophoresis if microcytic anaemia not responding (thalassaemia trait).",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "og-010", topic: "Obstetrics & Gynaecology", subtopic: "Labour",
    stem: "A 38-year-old woman at 41+3 weeks is in active labour. CTG shows a late deceleration pattern with baseline HR 145, variability 8 bpm, and no accelerations for 45 minutes. She is 6 cm dilated. What does this CTG pattern indicate?",
    options: [
      { label: "A", text: "Normal pattern — continue conservative management" },
      { label: "B", text: "Suspicious CTG — change maternal position, IV fluids, stop syntocinon if used" },
      { label: "C", text: "Pathological CTG — consider urgent FBS or expedite delivery" },
      { label: "D", text: "Normal variability — safe to continue" },
      { label: "E", text: "Early decelerations — reassuring" },
    ],
    correctAnswer: "C",
    explanation: "Pathological CTG: late decelerations (placental insufficiency/hypoxia), no accelerations for >45 min, reduced variability — indicates uteroplacental insufficiency. RANZCOG classification: normal → suspicious → pathological. Pathological CTG: consider FBS (fetal blood sampling) for pH/lactate or immediate delivery (vacuum/forceps/caesarean based on circumstances). Late decelerations most concerning (reflect fetal hypoxia).",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "og-011", topic: "Obstetrics & Gynaecology", subtopic: "Postpartum",
    stem: "A woman is 2 days postpartum after normal vaginal delivery. She presents with fever 38.5°C, uterine tenderness, and foul-smelling lochia. WBC 18.5. What is the most likely diagnosis and treatment?",
    options: [
      { label: "A", text: "Endometritis — IV amoxicillin + clavulanate or clindamycin + gentamicin" },
      { label: "B", text: "UTI — oral trimethoprim" },
      { label: "C", text: "DVT — LMWH" },
      { label: "D", text: "Mastitis — flucloxacillin" },
      { label: "E", text: "Normal postpartum fever — no treatment needed" },
    ],
    correctAnswer: "A",
    explanation: "Postpartum endometritis: fever >38°C, uterine tenderness, offensive lochia, within 10 days of delivery. Risk factors: CS, prolonged labour/ROM, GBS colonisation. Treatment: IV broad-spectrum antibiotics (clindamycin + gentamicin is gold standard, or amoxicillin-clavulanate). Covers GAS, GBS, Gram-negatives, anaerobes. Usually responds within 48h — if not, consider retained products (USS).",
    reference: "amc", difficulty: "medium",
  },
];
