import type { MCQuestion } from "./questions";

export const paediatricsQuestions: MCQuestion[] = [
  {
    id: "paeds-001", topic: "Paediatrics", subtopic: "Fever",
    stem: "A 6-week-old infant presents with fever of 38.2°C, irritability, and poor feeding. He is the product of a normal term delivery. What is the most appropriate initial management?",
    options: [
      { label: "A", text: "Paracetamol and review in 24 hours" },
      { label: "B", text: "Full septic screen and IV antibiotics" },
      { label: "C", text: "Blood culture only and oral amoxicillin" },
      { label: "D", text: "Observe in ED for 4 hours then discharge" },
      { label: "E", text: "Urine culture and oral antibiotics if positive" },
    ],
    correctAnswer: "B",
    explanation: "Infant <3 months with fever ≥38°C = serious bacterial infection (SBI) must be excluded. Perform full septic screen: FBC, CRP, blood culture, LP (CSF), urine MCS. Admit for IV antibiotics (ampicillin + gentamicin or cefotaxime) while awaiting cultures. Risk of bacteraemia, meningitis, UTI is significant in this age group. Do NOT delay for 'observation only'.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-002", topic: "Paediatrics", subtopic: "Respiratory",
    stem: "A 2-year-old boy presents with a barking cough, inspiratory stridor, and hoarse voice, worse at night. Temperature 37.6°C. He is mildly distressed but alert. SpO2 97%. What is the diagnosis and treatment?",
    options: [
      { label: "A", text: "Epiglottitis — immediate intubation" },
      { label: "B", text: "Croup (laryngotracheobronchitis) — dexamethasone oral" },
      { label: "C", text: "Foreign body aspiration — urgent bronchoscopy" },
      { label: "D", text: "Anaphylaxis — IM adrenaline" },
      { label: "E", text: "Viral tonsillitis — analgesics only" },
    ],
    correctAnswer: "B",
    explanation: "Croup: barking (seal-like) cough, inspiratory stridor, hoarse voice, low-grade fever, age 6 months–3 years, viral (parainfluenza). Mild-moderate: oral dexamethasone 0.15–0.6 mg/kg (single dose) — reduces severity, prevents admission. Severe croup: nebulised adrenaline (temporary, lasts 2h) + dexamethasone. Epiglottitis: drooling, tripod position, toxic, high fever, avoid throat examination (can precipitate obstruction).",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "paeds-003", topic: "Paediatrics", subtopic: "Febrile Convulsion",
    stem: "A 2-year-old girl has a generalised tonic-clonic seizure lasting 3 minutes during fever. She has no prior seizures. She recovers fully, is alert within 20 minutes. This is her first febrile seizure. Which is the most appropriate management?",
    options: [
      { label: "A", text: "Urgent MRI brain and EEG" },
      { label: "B", text: "Phenobarbitone prophylaxis for 2 years" },
      { label: "C", text: "Reassurance + source of fever treated; no anticonvulsant prophylaxis" },
      { label: "D", text: "LP to exclude meningitis in all cases" },
      { label: "E", text: "Ongoing rectal diazepam at home for all fever episodes" },
    ],
    correctAnswer: "C",
    explanation: "Simple febrile convulsion: generalised, <15 minutes, single episode per febrile illness, age 6m–6yr, full recovery. No long-term sequelae, no increased epilepsy risk (slightly elevated but <2%). Management: treat fever source, reassure parents. No anticonvulsant prophylaxis needed (risk>benefit). LP only if meningitis signs or <18 months and fully examined. Recurrence risk 30%. Teach parents first aid.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-004", topic: "Paediatrics", subtopic: "Developmental",
    stem: "A 9-month-old infant cannot yet sit unsupported, does not babble, and has not yet started pincer grasp. His weight is on the 10th centile. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Reassure parents — normal variation" },
      { label: "B", text: "Comprehensive developmental assessment, hearing and vision testing, consider referral" },
      { label: "C", text: "Refer for speech therapy immediately" },
      { label: "D", text: "Karyotype for Down syndrome" },
      { label: "E", text: "MRI brain" },
    ],
    correctAnswer: "B",
    explanation: "Developmental red flags at 9 months: no sitting (expected 6–8 months), no babbling (expected 6 months), no pincer grasp (expected 9–10 months). Multiple delays = global developmental delay (GDD). Comprehensive assessment needed: developmental history, hearing, vision, neurological exam, metabolic screening, genetics referral. Causes: cerebral palsy, genetic syndromes, hearing impairment, environmental deprivation.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-005", topic: "Paediatrics", subtopic: "Dehydration",
    stem: "A 10-month-old with gastroenteritis has 5–8% dehydration: sunken eyes, prolonged skin turgor, dry mucous membranes, but normal BP. He is still alert and not in shock. What is the preferred rehydration method?",
    options: [
      { label: "A", text: "IV normal saline bolus" },
      { label: "B", text: "Oral rehydration solution (ORS) — 5–10 mL every 5 minutes" },
      { label: "C", text: "IV 4% dextrose in 0.18% saline" },
      { label: "D", text: "NG rehydration with formula" },
      { label: "E", text: "Restrict fluids to allow GI rest" },
    ],
    correctAnswer: "B",
    explanation: "Mild-moderate dehydration (3–9%) without shock: oral rehydration therapy (ORS) is first-line — as effective as IV for non-severe cases. Small frequent sips (5 mL every 5 min, escalate as tolerated). ORS composition (WHO formula): Na 75, K 20, glucose 75, osmolarity 245 mOsm/L. IV fluids for: severe dehydration/shock, unable to tolerate ORS, altered consciousness. Avoid hypotonic fluids (risk hyponatraemia).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-006", topic: "Paediatrics", subtopic: "Asthma",
    stem: "A 7-year-old boy has exercise-triggered wheeze, nocturnal cough >2 nights/week, and reliever use >3/week. He is on ICS (fluticasone 100 µg/day). What is the next step in management per GINA paediatric guidelines?",
    options: [
      { label: "A", text: "Continue current therapy — well controlled" },
      { label: "B", text: "Add montelukast to ICS" },
      { label: "C", text: "Step up: increase ICS dose or add LABA" },
      { label: "D", text: "Start oral prednisolone" },
      { label: "E", text: "Remove all pets and allergens — no medication change" },
    ],
    correctAnswer: "C",
    explanation: "Uncontrolled asthma symptoms on low-dose ICS: step up therapy. GINA step 3: medium-dose ICS or low-dose ICS+LABA (in children ≥5 years). Montelukast can be added as step 2–3 add-on. Check inhaler technique and adherence before stepping up. Also assess comorbidities (allergic rhinitis, GORD). Trial allergen avoidance as adjunct but not primary management.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-007", topic: "Paediatrics", subtopic: "Immunisation",
    stem: "A parent refuses the MMR vaccine for their 12-month-old citing concerns about autism linked to the MMR vaccine from a 1998 study. What is the most appropriate response?",
    options: [
      { label: "A", text: "Accept the refusal and document it" },
      { label: "B", text: "Explain the fraudulent 1998 Wakefield study was retracted; reassure with current evidence" },
      { label: "C", text: "Call child protection services" },
      { label: "D", text: "Administer the vaccine without parental consent" },
      { label: "E", text: "Refer to immunologist for allergy testing before vaccination" },
    ],
    correctAnswer: "B",
    explanation: "Vaccine hesitancy: address empathetically, explore concerns. The 1998 Wakefield study (Lancet) was fraudulently fabricated, completely retracted, and Wakefield was struck off. Over 20 large studies involving millions of children confirm no link between MMR and autism. Explain measles risk. HERD immunity protects vulnerable children. No-fault compensation scheme exists. Document discussion. Never administer without consent.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "paeds-008", topic: "Paediatrics", subtopic: "Meningococcal",
    stem: "A 3-year-old presents with fever 39.5°C, a non-blanching petechial rash on the legs and trunk, irritability, and neck stiffness. She deteriorates rapidly with BP 70/40 and HR 165. What is the MOST important immediate action?",
    options: [
      { label: "A", text: "LP before starting antibiotics" },
      { label: "B", text: "CT head before LP" },
      { label: "C", text: "IV/IO benzylpenicillin immediately + resuscitation" },
      { label: "D", text: "IM ceftriaxone and transfer to hospital" },
      { label: "E", text: "Blood cultures before antibiotics" },
    ],
    correctAnswer: "C",
    explanation: "Meningococcal septicaemia with septic shock = immediate life-threatening emergency. Give IV/IO benzylpenicillin IMMEDIATELY — do NOT delay for LP, CT, or blood cultures. If in community: IM penicillin before transfer. Aggressive resuscitation: IV fluids 20 mL/kg saline bolus, oxygen, vasopressors if needed. LP contraindicated in shock — raised ICP risk. Blood cultures if no delay to antibiotic administration.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "paeds-009", topic: "Paediatrics", subtopic: "Child Abuse",
    stem: "A 2-year-old boy presents with multiple bruises in various stages of healing on his buttocks, back, and upper thighs. His father explains he 'fell off the couch'. The child is subdued and does not interact with his parents. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Accept the explanation and reassure the father" },
      { label: "B", text: "Request a skeletal survey and ophthalmology review" },
      { label: "C", text: "Mandatory notification to child protection + skeletal survey + admit" },
      { label: "D", text: "Social work referral and discharge with safety plan" },
      { label: "E", text: "Wait for further injuries before reporting" },
    ],
    correctAnswer: "C",
    explanation: "Non-accidental injury (NAI): bruises in non-mobile toddler in protected areas (buttocks, back, trunk, face, ears), multiple injuries in different healing stages, inconsistent history, withdrawn affect. Actions: admit for safety, skeletal survey (metaphyseal fractures, posterior rib fractures), ophthalmology (retinal haemorrhages in shaken baby), mandatory notification to child protection (DOCS/CPS). Document objectively. Do not confront parents aggressively.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-010", topic: "Paediatrics", subtopic: "Neonatology",
    stem: "A term newborn has jaundice on day 1 of life. Serum bilirubin is 155 µmol/L (predominantly conjugated). He is ABO incompatible with mother (Group O mother, Group A baby). Direct Coombs test is positive. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Physiological jaundice of the newborn" },
      { label: "B", text: "Haemolytic disease of newborn (ABO incompatibility)" },
      { label: "C", text: "Biliary atresia" },
      { label: "D", text: "Crigler-Najjar syndrome" },
      { label: "E", text: "Breast milk jaundice" },
    ],
    correctAnswer: "B",
    explanation: "Haemolytic disease of newborn: jaundice on day 1 (any jaundice day 1 is pathological — investigate), positive DAT (direct Coombs), ABO or Rh incompatibility. Management: phototherapy for mild, exchange transfusion for severe (risk of kernicterus). Physiological jaundice: days 2–5 (unconjugated). Biliary atresia: conjugated (direct) hyperbilirubinaemia, pale stools, dark urine — different presentation.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-011", topic: "Paediatrics", subtopic: "Failure to Thrive",
    stem: "A 9-month-old girl's weight has fallen from 50th centile at birth to 5th centile now. Length is on 25th centile. She is observed to feed well in hospital and gains weight normally. At home she is cared for by her grandmother. What is the most likely cause?",
    options: [
      { label: "A", text: "Cystic fibrosis" },
      { label: "B", text: "Malabsorption (coeliac disease)" },
      { label: "C", text: "Non-organic failure to thrive (inadequate caloric intake/neglect)" },
      { label: "D", text: "Hypothyroidism" },
      { label: "E", text: "Congenital heart disease" },
    ],
    correctAnswer: "C",
    explanation: "Non-organic FTT: weight gain in hospital with normal feeds confirms adequate caloric intake possible — problem is in home environment (inadequate feeding, neglect, psychosocial deprivation). Weight affected before length/height. Organic causes: CF (malabsorption, recurrent infections), coeliac (weight loss after solids introduced), CHD (failure to thrive from early infancy, murmur). Psychosocial assessment and home visit essential.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-012", topic: "Paediatrics", subtopic: "Gastrointestinal",
    stem: "A 3-week-old male presents with 4 days of projectile vomiting after every feed. He is hungry immediately after vomiting. He is mildly dehydrated. Bloods show hypochloraemic, hypokalaemic metabolic alkalosis. An olive-shaped mass is palpable in the RUQ. What is the diagnosis and treatment?",
    options: [
      { label: "A", text: "Gastroenteritis — rehydration" },
      { label: "B", text: "Hypertrophic pyloric stenosis — Ramstedt pyloromyotomy after correction of electrolytes" },
      { label: "C", text: "Duodenal atresia — urgent surgery" },
      { label: "D", text: "Reflux — thickened feeds" },
      { label: "E", text: "Malrotation with volvulus — urgent laparotomy" },
    ],
    correctAnswer: "B",
    explanation: "Hypertrophic pyloric stenosis (HPS): age 2–8 weeks, male (4:1), projectile non-bilious vomiting, always hungry, metabolic alkalosis (HCl lost in vomit → H+Cl- loss → ↑HCO3, compensatory K+ wasting). Pyloric mass ('olive') palpable in 80%. USS confirms (elongated, thickened pylorus). Rehydrate and correct electrolytes FIRST then Ramstedt pyloromyotomy (laparoscopic). Surgery NOT until electrolytes corrected (anaesthetic risk).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "paeds-013", topic: "Paediatrics", subtopic: "Respiratory",
    stem: "A 4-month-old presents in winter with 2 days of fever, tachypnoea (RR 62), wheeze, and subcostal recession. SpO2 92% on room air. Chest has crackles throughout. Parents report noisy breathing. This is the first episode of wheeze. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Asthma — salbutamol nebuliser" },
      { label: "B", text: "Bronchiolitis (RSV) — supportive care, oxygen" },
      { label: "C", text: "Pneumonia — antibiotics" },
      { label: "D", text: "Croup — dexamethasone" },
      { label: "E", text: "Foreign body aspiration" },
    ],
    correctAnswer: "B",
    explanation: "Bronchiolitis: age <2 years, winter, RSV most common (70%). Wheeze + crackles + first episode + young infant. Management: supportive — supplemental oxygen (target SpO2 ≥92%), adequate hydration (NG feeds if poor oral intake), no role for salbutamol/steroids/antibiotics routinely (multiple RCTs show no benefit). High-flow nasal cannula for moderate-severe. Admit if SpO2 <92%, RR >70, poor feeding, apnoea.",
    reference: "amc", difficulty: "easy",
  },
];
