import type { MCQuestion } from "./questions";

export const pharmacologyQuestions: MCQuestion[] = [
  {
    id: "pharm-001", topic: "Pharmacology", subtopic: "Prescribing",
    stem: "A 75-year-old man is prescribed gentamicin for Gram-negative bacteraemia. He has CKD (eGFR 28). Which parameter requires adjustment for aminoglycosides in renal impairment?",
    options: [
      { label: "A", text: "Increase the dose to compensate for poor absorption" },
      { label: "B", text: "Extend the dosing interval (reduce frequency)" },
      { label: "C", text: "Halve the dose and maintain normal frequency" },
      { label: "D", text: "Aminoglycosides are absolutely contraindicated in CKD" },
      { label: "E", text: "No adjustment needed — gentamicin is hepatically metabolised" },
    ],
    correctAnswer: "B",
    explanation: "Aminoglycosides (gentamicin, tobramycin): renally cleared, nephrotoxic and ototoxic. In renal impairment: extend dosing interval (same peak dose, longer interval — maintains bactericidal peak while allowing trough to fall). Once-daily dosing (Hartford protocol) preferred. Monitor levels: pre-dose trough <1 mg/L, post-dose peak 8–10 mg/L for once-daily. Avoid with other nephrotoxins.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "pharm-002", topic: "Pharmacology", subtopic: "Drug Interactions",
    stem: "A 60-year-old man on warfarin (INR 2.8) is started on clarithromycin for a chest infection. He returns 5 days later with gum bleeding and INR 6.2. What is the mechanism?",
    options: [
      { label: "A", text: "Clarithromycin is a potent CYP3A4 inhibitor — reduces warfarin metabolism → ↑INR" },
      { label: "B", text: "Clarithromycin is a CYP3A4 inducer — increases warfarin metabolism → should have ↓INR" },
      { label: "C", text: "Clarithromycin displaces warfarin from protein binding" },
      { label: "D", text: "Clarithromycin kills gut bacteria → reduces vitamin K production" },
      { label: "E", text: "Clarithromycin has intrinsic anticoagulant properties" },
    ],
    correctAnswer: "A",
    explanation: "Warfarin is metabolised by CYP2C9 (mainly) and CYP3A4. Clarithromycin (macrolide) inhibits CYP3A4 → reduced warfarin metabolism → ↑plasma levels → supratherapeutic INR. Also reduces gut flora (vitamin K). Management: close INR monitoring when adding any CYP inhibitor/inducer to warfarin. Strong CYP2C9 inhibitors: fluconazole, amiodarone, metronidazole, trimethoprim. P-glycoprotein inhibitors also increase DOACs.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "pharm-003", topic: "Pharmacology", subtopic: "Drug Interactions",
    stem: "A 45-year-old woman on sertraline 100 mg/day is started on tramadol for back pain. Which serious drug interaction should be warned about?",
    options: [
      { label: "A", text: "Tramadol reduces sertraline absorption" },
      { label: "B", text: "Serotonin syndrome — tremor, hyperthermia, agitation, clonus, diarrhoea" },
      { label: "C", text: "QT prolongation only" },
      { label: "D", text: "Reduced analgesic effect of tramadol" },
      { label: "E", text: "Increased bleeding risk" },
    ],
    correctAnswer: "B",
    explanation: "Serotonin syndrome: tramadol (weak SNRI + weak opioid agonist) + SSRI → excess serotonergic activity. Features: triad of cognitive changes (agitation, confusion), neuromuscular abnormalities (clonus, hyperreflexia, tremor), and autonomic instability (hyperthermia, tachycardia, diaphoresis). Severe: life-threatening hyperthermia, seizures. Distinguish from NMS (onset hours vs days, clonus vs rigidity). Treatment: stop offending drugs, cyproheptadine, benzodiazepines.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "pharm-004", topic: "Pharmacology", subtopic: "Adverse Effects",
    stem: "A 55-year-old man on amiodarone for AF develops a dry cough, progressive dyspnoea, and bilateral reticular infiltrates on CXR. PFTs show a restrictive pattern with reduced DLCO. What is the diagnosis?",
    options: [
      { label: "A", text: "ACE inhibitor cough — switch to ARB" },
      { label: "B", text: "Amiodarone pulmonary toxicity — stop amiodarone" },
      { label: "C", text: "Heart failure exacerbation — increase diuretics" },
      { label: "D", text: "IPF — start pirfenidone" },
      { label: "E", text: "Amiodarone-induced hypothyroidism" },
    ],
    correctAnswer: "B",
    explanation: "Amiodarone toxicities (HELP mnemonic): Hepatic (↑LFTs), Eyes (corneal microdeposits), Lungs (pulmonary toxicity - serious, 5%), Pigmentation (grey-blue skin), thyroid (hypo or hyperthyroidism). Pulmonary toxicity: bilateral infiltrates, restrictive PFTs, low DLCO, ↑KL-6. Stop amiodarone; steroids if severe. Amiodarone has many interactions — inhibits CYP2C9 (↑warfarin), P-gp (↑digoxin). Long half-life (40–55 days) — toxicity may persist after stopping.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "pharm-005", topic: "Pharmacology", subtopic: "Medication Review",
    stem: "A 78-year-old woman is on amlodipine, metoprolol, aspirin, simvastatin, alendronate, omeprazole, ibuprofen, and temazepam. She presents with bilateral ankle oedema and elevated BP. Which medication is most likely causing her ankle oedema?",
    options: [
      { label: "A", text: "Metoprolol" },
      { label: "B", text: "Simvastatin" },
      { label: "C", text: "Amlodipine (calcium channel blocker)" },
      { label: "D", text: "Aspirin" },
      { label: "E", text: "Omeprazole" },
    ],
    correctAnswer: "C",
    explanation: "Amlodipine (dihydropyridine CCB): common side effect is dose-dependent peripheral oedema from pre-capillary arteriolar dilation without corresponding venous dilation → increased hydrostatic pressure → dependent oedema. Not due to fluid retention (diuretics won't help). Management: reduce dose, switch to another antihypertensive, or add ACEi/ARB (reduces CCB-induced oedema). Ankle oedema with CCBs is worse in elderly, hot weather, prolonged standing.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "pharm-006", topic: "Pharmacology", subtopic: "Antibiotics",
    stem: "A 30-year-old woman with penicillin allergy (anaphylaxis as a child) needs treatment for community-acquired pneumonia. Which antibiotic should be avoided due to cross-reactivity?",
    options: [
      { label: "A", text: "Azithromycin — avoid due to cross-reactivity" },
      { label: "B", text: "Cefalexin (cephalosporin) — significant cross-reactivity with anaphylaxis history" },
      { label: "C", text: "Doxycycline — crosses the beta-lactam ring" },
      { label: "D", text: "Moxifloxacin — related to penicillin" },
      { label: "E", text: "Co-trimoxazole" },
    ],
    correctAnswer: "B",
    explanation: "Penicillin and cephalosporins share the beta-lactam ring: cross-reactivity exists (1–2% overall, higher risk if previous anaphylaxis to penicillin). With history of anaphylaxis: avoid cephalosporins and all beta-lactams (carbapenems 1% cross-reactivity). Use azithromycin (macrolide) or doxycycline for CAP in penicillin-anaphylaxis patients. Allergy testing can be performed if beta-lactam is essential (skin testing/graded challenge).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "pharm-007", topic: "Pharmacology", subtopic: "Analgesics",
    stem: "A 65-year-old woman with CKD Stage 3 (eGFR 38) has chronic low back pain. Which analgesic is most appropriate?",
    options: [
      { label: "A", text: "Regular ibuprofen 400 mg TDS" },
      { label: "B", text: "Regular paracetamol 1 g QDS" },
      { label: "C", text: "Tramadol 100 mg QDS" },
      { label: "D", text: "Codeine 30 mg QDS" },
      { label: "E", text: "Naproxen 500 mg BD with PPI" },
    ],
    correctAnswer: "B",
    explanation: "Analgesia in CKD: paracetamol is the safest first-line analgesic (hepatic metabolism, no nephrotoxicity at standard doses). NSAIDs (ibuprofen, naproxen): reduce prostaglandin-mediated afferent vasodilation → further reduction in GFR → AKI risk, especially eGFR <60. Opioids: accumulate in CKD (active metabolites) — use with caution, reduce dose/frequency. Tramadol: seizure risk in CKD, accumulates. Avoid NSAIDs in CKD.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "pharm-008", topic: "Pharmacology", subtopic: "Drug Overdose",
    stem: "A patient intentionally overdoses on metoprolol 2500 mg. She presents with HR 42, BP 78/50, and heart blocks on ECG. She is confused. High-dose insulin therapy is being considered. What is the rationale?",
    options: [
      { label: "A", text: "Insulin reverses beta-blockade at receptor level" },
      { label: "B", text: "Hyperinsulinaemia-euglycaemia (HIET) enhances myocardial glucose uptake and improves cardiac contractility" },
      { label: "C", text: "Insulin reverses hypoglycaemia from beta-blocker" },
      { label: "D", text: "Insulin reduces beta-blocker absorption" },
      { label: "E", text: "Insulin is the antidote for all cardiac drug overdoses" },
    ],
    correctAnswer: "B",
    explanation: "Beta-blocker toxicity: bradycardia, hypotension, heart block. Treatments: atropine, calcium gluconate, glucagon (increases cAMP bypassing beta-receptors), high-dose insulin (HIET: 1 unit/kg bolus then 0.5–1 unit/kg/hr infusion) + dextrose. HIET rationale: blocked beta-receptors → heart uses fatty acids not glucose; insulin shifts metabolism to glucose → improved cardiac contractility ('metabolic resuscitation'). Also indicated for CCB toxicity. IV lipid emulsion for refractory cases.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "pharm-009", topic: "Pharmacology", subtopic: "NSAIDs",
    stem: "A 60-year-old man with osteoarthritis starts diclofenac. He also takes aspirin 100 mg for secondary CVD prevention. What important interaction should be considered?",
    options: [
      { label: "A", text: "Diclofenac reduces aspirin's antiplatelet effect — take aspirin 2h before NSAID" },
      { label: "B", text: "Diclofenac enhances aspirin's anticoagulant effect — bleeding risk" },
      { label: "C", text: "No interaction — take together freely" },
      { label: "D", text: "Both inhibit COX-2 — increased GI toxicity but no CV interaction" },
      { label: "E", text: "Diclofenac is safer than all other NSAIDs for CV disease" },
    ],
    correctAnswer: "A",
    explanation: "NSAID + aspirin interaction: non-selective NSAIDs (ibuprofen, naproxen, diclofenac) compete with aspirin for COX-1 acetylation at platelet level → reduce aspirin's irreversible antiplatelet effect → reduced CV protection. To minimise: take aspirin at least 2h before NSAID (especially ibuprofen). Diclofenac has highest CV risk among NSAIDs (↑MI risk). COX-2 selective NSAIDs (celecoxib) don't affect aspirin platelet inhibition. PPI co-prescription for GI protection.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "pharm-010", topic: "Pharmacology", subtopic: "Corticosteroids",
    stem: "A 45-year-old woman on prednisolone 20 mg/day for 3 months requires an urgent appendicectomy. She takes no extra steroids pre-operatively and postoperatively becomes hypotensive and confused despite fluid resuscitation. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Post-operative infection" },
      { label: "B", text: "Adrenal crisis due to HPA axis suppression" },
      { label: "C", text: "Anaphylaxis to anaesthetic agent" },
      { label: "D", text: "Pulmonary embolism post-surgery" },
      { label: "E", text: "Hypovolaemia from inadequate resuscitation" },
    ],
    correctAnswer: "B",
    explanation: "Adrenal crisis: long-term steroid use >3 weeks suppresses HPA axis → adrenal atrophy → cannot mount cortisol stress response for surgery. 'Stress dosing' required perioperatively: hydrocortisone 25 mg IV at induction + 25 mg every 8h for 24h, then taper to maintenance. Signs: hypotension, confusion, hyponatraemia, hyperkalaemia not responding to fluids. Treatment: IV hydrocortisone 100 mg stat + 50–100 mg every 6–8h. Any patient on >5 mg prednisolone/day for >4 weeks needs steroid coverage for surgery.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "pharm-011", topic: "Pharmacology", subtopic: "Medication in Pregnancy",
    stem: "A 28-year-old woman at 8 weeks gestation needs antihypertensive treatment (BP 155/100). Which is the MOST appropriate choice?",
    options: [
      { label: "A", text: "ACE inhibitor (perindopril)" },
      { label: "B", text: "ARB (irbesartan)" },
      { label: "C", text: "Labetalol or methyldopa" },
      { label: "D", text: "Furosemide" },
      { label: "E", text: "Spironolactone" },
    ],
    correctAnswer: "C",
    explanation: "Safe antihypertensives in pregnancy: labetalol (first-line), methyldopa (longstanding safety record), nifedipine (CCB). AVOID: ACEi and ARBs (teratogenic — oligohydramnios, renal dysgenesis, fetal death in 2nd/3rd trimester; also avoid in 1st trimester). Avoid spironolactone (anti-androgenic). Diuretics reduce plasma volume — can worsen uteroplacental perfusion. Target BP <150/100 (avoid hypotension — reduces placental perfusion).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "pharm-012", topic: "Pharmacology", subtopic: "Anticoagulation",
    stem: "A 70-year-old man on warfarin (INR 3.1) for mechanical heart valve has a supratherapeutic INR of 8.5 but is not bleeding. What is the appropriate management?",
    options: [
      { label: "A", text: "Hold warfarin; give IV vitamin K 10 mg" },
      { label: "B", text: "Hold 1–2 doses of warfarin; give oral vitamin K 1–2 mg; recheck INR in 24h" },
      { label: "C", text: "Start IV fresh frozen plasma" },
      { label: "D", text: "Give protamine sulphate" },
      { label: "E", text: "No action — INR <10 in asymptomatic patient does not require intervention" },
    ],
    correctAnswer: "B",
    explanation: "Warfarin supratherapeutic INR 5–9, no bleeding: hold warfarin 1–2 doses + low-dose oral vitamin K 1–2 mg (partial correction — don't use IV K for mechanical valve as can cause warfarin resistance/over-correction). Recheck INR in 24h. For INR >9 or minor bleeding: oral vitamin K 5 mg + stop warfarin. Major bleeding: FFP + IV vitamin K 5–10 mg. Mechanical valve: avoid high-dose vitamin K (INR reversal increases valve thrombosis risk).",
    reference: "amc", difficulty: "hard",
  },
];
