import type { MCQuestion } from "./questions";

export const renalQuestions: MCQuestion[] = [
  {
    id: "renal-001", topic: "Renal", subtopic: "AKI",
    stem: "A 70-year-old man on perindopril and furosemide for hypertension starts ibuprofen for knee pain. He presents with oliguria and creatinine rise from 110 to 280 µmol/L. This is the 'triple whammy'. What is the mechanism?",
    options: [
      { label: "A", text: "ACEi reduces GFR; diuretic reduces perfusion; NSAID reduces afferent vasoconstriction" },
      { label: "B", text: "ACEi blocks angiotensin II efferent constriction; diuretic reduces volume; NSAID reduces prostaglandin-mediated afferent vasodilation" },
      { label: "C", text: "All three are direct nephrotoxins" },
      { label: "D", text: "NSAID causes interstitial nephritis; ACEi causes tubular damage" },
      { label: "E", text: "Triple whammy only relevant in diabetes" },
    ],
    correctAnswer: "B",
    explanation: "Triple whammy AKI: ACEi/ARB (blocks efferent arteriolar constriction via RAAS → reduces GFR) + diuretic (volume depletion) + NSAID (blocks prostaglandins that maintain afferent vasodilation in low-volume states) → critical reduction in GFR → AKI. Management: stop all three, IV fluids. ACEi/diuretic can usually be restarted after recovery. Avoid NSAIDs in elderly with CKD.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "renal-002", topic: "Renal", subtopic: "CKD",
    stem: "A 55-year-old diabetic woman has CKD Stage 3b (eGFR 32 mL/min/1.73m²). Her BP is 140/88 on amlodipine. Urine ACR 85 mg/mmol. She is on metformin. Which medications should be addressed?",
    options: [
      { label: "A", text: "Stop amlodipine — contraindicated in CKD" },
      { label: "B", text: "Stop metformin (eGFR <30) + add ACEi/ARB for proteinuria" },
      { label: "C", text: "Continue all medications — no changes needed at eGFR 32" },
      { label: "D", text: "Add diuretic for BP control" },
      { label: "E", text: "Refer for dialysis immediately" },
    ],
    correctAnswer: "B",
    explanation: "CKD Stage 3b (eGFR 30–44): metformin should be stopped at eGFR <30 (risk of lactic acidosis). Review at eGFR <45 (reduce dose, more frequent monitoring). ACEi or ARB: first-line for proteinuric CKD (reduces ACR, slows progression). SGLT2i now approved for CKD with albuminuria (eGFR ≥20). Amlodipine is safe in CKD. Monitor K+ with ACEi/ARB.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "renal-003", topic: "Renal", subtopic: "Nephrotic Syndrome",
    stem: "A 5-year-old boy develops periorbital oedema, ascites, and frothy urine. Urine protein 3+ (>3.5 g/day). Serum albumin 18 g/L. Cholesterol elevated. BP normal. No haematuria. What is the most likely diagnosis and treatment?",
    options: [
      { label: "A", text: "IgA nephropathy — no treatment" },
      { label: "B", text: "Minimal change disease — high-dose prednisolone" },
      { label: "C", text: "Focal segmental glomerulosclerosis — ciclosporin" },
      { label: "D", text: "Membranous nephropathy — watchful waiting" },
      { label: "E", text: "Henoch-Schönlein purpura — steroids" },
    ],
    correctAnswer: "B",
    explanation: "Nephrotic syndrome in children: most common cause is minimal change disease (MCD). Features: heavy proteinuria (>3.5 g/day), hypoalbuminaemia, oedema, hyperlipidaemia, no haematuria (unlike nephritic). Treat empirically with corticosteroids (prednisolone 60 mg/m²/day) — 90% respond. Biopsy only if atypical features or steroid resistance. MCD in adults: often paraneoplastic (Hodgkin's lymphoma).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "renal-004", topic: "Renal", subtopic: "Nephritic Syndrome",
    stem: "A 28-year-old man has haematuria (red cell casts on urine microscopy), proteinuria 1.5 g/day, hypertension, and creatinine 180 µmol/L. He had pharyngitis 3 weeks ago. C3 is low, C4 normal. ASOT elevated. What is the diagnosis?",
    options: [
      { label: "A", text: "IgA nephropathy (Berger's disease)" },
      { label: "B", text: "Post-streptococcal glomerulonephritis (PSGN)" },
      { label: "C", text: "Lupus nephritis" },
      { label: "D", text: "Anti-GBM disease (Goodpasture's)" },
      { label: "E", text: "ANCA vasculitis" },
    ],
    correctAnswer: "B",
    explanation: "PSGN: 1–3 weeks after Group A strep throat infection (10 days if skin). Nephritic syndrome, low C3 (normal C4 — alternative complement pathway), elevated ASOT. Usually self-limiting. Treat BP, fluid balance. No specific therapy. Most recover fully. IgA nephropathy: haematuria 1–2 days after URTI (concurrent, not 3 weeks later), normal complement. SLE: low C3+C4. Anti-GBM: haemoptysis + renal failure.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "renal-005", topic: "Renal", subtopic: "Urinary Tract Infection",
    stem: "A 25-year-old healthy woman presents with dysuria, frequency, and suprapubic pain. Temperature 37.4°C. No loin pain. Urine dipstick: nitrites +, leucocytes 3+. What is first-line treatment and duration?",
    options: [
      { label: "A", text: "Trimethoprim 300 mg daily × 3 days" },
      { label: "B", text: "Nitrofurantoin 100 mg BD × 5 days" },
      { label: "C", text: "Cefalexin × 7 days" },
      { label: "D", text: "Ciprofloxacin × 3 days" },
      { label: "E", text: "Amoxicillin 500 mg TDS × 7 days" },
    ],
    correctAnswer: "A",
    explanation: "Uncomplicated UTI (young healthy non-pregnant woman): trimethoprim 300 mg nocte × 3 days is first-line in Australia (Therapeutic Guidelines). Nitrofurantoin 100 mg (Macrobid) × 5 days also first-line. Avoid quinolones (resistance, adverse effects). Avoid amoxicillin (high E. coli resistance in Australia). Complicated UTI (pyelonephritis, catheter, immunosuppressed): 7–14 days with broader coverage.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "renal-006", topic: "Renal", subtopic: "Pyelonephritis",
    stem: "A 30-year-old woman presents with fever 39°C, rigors, loin pain, and vomiting. Urine MCS grows E. coli >10⁸ CFU/L. She is dehydrated but haemodynamically stable. What is appropriate management?",
    options: [
      { label: "A", text: "Oral trimethoprim 3 days" },
      { label: "B", text: "Oral cefalexin or ciprofloxacin for 10–14 days (if able to tolerate orally)" },
      { label: "C", text: "IV ceftriaxone until afebrile, then oral to complete 14 days" },
      { label: "D", text: "Refer for nephrostomy" },
      { label: "E", text: "Urology review and cystoscopy" },
    ],
    correctAnswer: "B",
    explanation: "Mild-moderate pyelonephritis (haemodynamically stable, able to tolerate oral): outpatient management with oral antibiotics × 10–14 days. Cefalexin or ciprofloxacin/norfloxacin (check local resistance patterns). IV ceftriaxone for: severe (unable to tolerate orals, sepsis, immunosuppressed, pregnancy). Urine MCS guides antibiotic choice. Follow-up urine MCS 1 week after completing antibiotics. Exclude obstruction (USS) in severe/recurrent cases.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "renal-007", topic: "Renal", subtopic: "Renal Calculi",
    stem: "A 35-year-old man presents with acute severe loin-to-groin pain, nausea, and microscopic haematuria. CTKUB shows a 4 mm stone at the vesicoureteric junction (VUJ). Creatinine is normal. No signs of infection. What is the most appropriate management?",
    options: [
      { label: "A", text: "Emergency lithotripsy" },
      { label: "B", text: "Conservative management with analgesia + alpha-blocker (tamsulosin) for medical expulsive therapy" },
      { label: "C", text: "Urgent cystoscopy and stone extraction" },
      { label: "D", text: "Percutaneous nephrolithotomy" },
      { label: "E", text: "IV antibiotics" },
    ],
    correctAnswer: "B",
    explanation: "Uncomplicated renal colic with small stone ≤5 mm: conservative management — analgesia (NSAIDs first-line; IV morphine if vomiting), alpha-blocker (tamsulosin 0.4 mg nocte = medical expulsive therapy, increases spontaneous passage rate for 4–10 mm stones). Stones <5 mm pass spontaneously in 90%. Urgent urological referral if: urosepsis (infection + obstruction = emergency), solitary kidney, bilateral obstruction, or pain not controlled.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "renal-008", topic: "Renal", subtopic: "Haematuria",
    stem: "A 65-year-old male smoker presents with painless macroscopic haematuria. He has no other urinary symptoms. Urine MCS is negative. What is the most appropriate investigation?",
    options: [
      { label: "A", text: "Repeat urine MCS in 1 week" },
      { label: "B", text: "Cystoscopy + upper tract imaging (CT urogram)" },
      { label: "C", text: "PSA and digital rectal exam" },
      { label: "D", text: "Urine cytology alone" },
      { label: "E", text: "Renal biopsy" },
    ],
    correctAnswer: "B",
    explanation: "Painless visible haematuria in a man >50 years (especially smoker): transitional cell carcinoma (TCC) of bladder or upper tract must be excluded. Cystoscopy is gold standard for bladder cancer. CT urogram for upper urinary tract (renal pelvis, ureter). Bladder cancer risk factors: smoking (most important), aniline dyes, cyclophosphamide, radiation. Refer urgently to urology.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "renal-009", topic: "Renal", subtopic: "Electrolytes",
    stem: "A 75-year-old woman on thiazide diuretic has Na 122 mmol/L. She is mildly confused. No peripheral oedema. She appears euvolaemic. Urine Na 45 mmol/L, urine osmolality 380 mOsm/kg. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Psychogenic polydipsia — restrict water" },
      { label: "B", text: "SIADH — fluid restriction to 1 L/day" },
      { label: "C", text: "Hypovolaemic hyponatraemia — IV normal saline" },
      { label: "D", text: "Adrenal insufficiency — hydrocortisone" },
      { label: "E", text: "Hypothyroidism — levothyroxine" },
    ],
    correctAnswer: "B",
    explanation: "SIADH: euvolaemia + hyponatraemia + inappropriately concentrated urine (>100 mOsm/kg) + urine Na >30 + no oedema/dehydration. Causes: thiazides most common drug cause (blocks diluting segment), CNS disease, pulmonary disease, medications (SSRIs, carbamazepine). Treatment: fluid restriction 800–1000 mL/day. If symptomatic/severe (<120 or acutely falling): hypertonic saline (correct ≤8-10 mEq/day to prevent osmotic demyelination).",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "renal-010", topic: "Renal", subtopic: "BPH",
    stem: "A 68-year-old man has IPSS score 18, nocturia × 4, Qmax 8 mL/sec, post-void residual 120 mL, PSA 2.8 ng/mL. Prostate 45 g on DRE. His renal function is normal. What is first-line management?",
    options: [
      { label: "A", text: "Alpha-blocker (tamsulosin) only" },
      { label: "B", text: "5-alpha reductase inhibitor (finasteride) only" },
      { label: "C", text: "Combination alpha-blocker + 5-ARI (finasteride or dutasteride)" },
      { label: "D", text: "TURP immediately" },
      { label: "E", text: "Anticholinergic for detrusor overactivity" },
    ],
    correctAnswer: "C",
    explanation: "Moderate-severe LUTS (IPSS >8) with large prostate (>40 g) and elevated PSA: combination therapy (alpha-blocker + 5-ARI) is superior to monotherapy for symptom control and prevention of progression (MTOPS, CombAT trials). Alpha-blocker: rapid onset, reduces smooth muscle tone. 5-ARI (finasteride/dutasteride): slow onset 6 months, shrinks gland, reduces PSA by ~50%, prevents progression. Surgery if: retention, renal impairment, recurrent UTI, haematuria.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "renal-011", topic: "Renal", subtopic: "AKI",
    stem: "A 45-year-old man has AKI with potassium 6.8 mEq/L. ECG shows peaked T waves and widened QRS. What is the most urgent treatment to protect the heart?",
    options: [
      { label: "A", text: "Calcium resonium (kayexalate) to remove potassium" },
      { label: "B", text: "Insulin + dextrose infusion to shift K+ intracellularly" },
      { label: "C", text: "IV calcium gluconate 10 mL of 10% to stabilise cardiac membrane" },
      { label: "D", text: "Haemodialysis immediately" },
      { label: "E", text: "Sodium bicarbonate" },
    ],
    correctAnswer: "C",
    explanation: "Hyperkalaemic emergency with ECG changes (peaked T waves, widened QRS, sine wave): IV calcium gluconate 10 mL 10% over 2 minutes is FIRST — cardioprotective (stabilises myocardial membrane). Does NOT lower K+. Then: insulin (10 units actrapid) + 50 mL 50% dextrose (shifts K+ into cells, onset 30 min). Nebulised salbutamol (shifts K+). Remove K+: furosemide, calcium resonium, haemodialysis. Bicarbonate if metabolic acidosis.",
    reference: "amc", difficulty: "medium",
  },
];
