import type { MCQuestion } from "./questions";

export const emergencyQuestions: MCQuestion[] = [
  {
    id: "em-001", topic: "Emergency Medicine", subtopic: "Anaphylaxis",
    stem: "A 25-year-old woman collapses 10 minutes after a bee sting. She has urticaria, angioedema, wheeze, and BP 70/40. HR 135. What is the immediate first-line treatment?",
    options: [
      { label: "A", text: "IV chlorphenamine (antihistamine)" },
      { label: "B", text: "IV hydrocortisone 200 mg" },
      { label: "C", text: "IM adrenaline 0.5 mg (1:1000) into the outer thigh" },
      { label: "D", text: "Nebulised salbutamol" },
      { label: "E", text: "High-flow oxygen alone" },
    ],
    correctAnswer: "C",
    explanation: "Anaphylaxis: IM adrenaline (epinephrine) 0.5 mg (1:1000) into the anterolateral thigh is the FIRST and most important treatment. Do NOT give IV adrenaline routinely (risk of VF) unless cardiac arrest. Position flat (legs up if hypotension). Then: high-flow O2, IV fluids, repeat adrenaline in 5 min if no response. Antihistamines and steroids are adjuncts only — NOT first-line.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "em-002", topic: "Emergency Medicine", subtopic: "Poisoning",
    stem: "A 19-year-old woman presents 6 hours after intentional paracetamol overdose of 15 g. She is asymptomatic. What is the initial assessment and treatment?",
    options: [
      { label: "A", text: "No treatment needed — she is asymptomatic" },
      { label: "B", text: "Check paracetamol level and plot on Rumack-Matthew nomogram; start N-acetylcysteine if above treatment line" },
      { label: "C", text: "Activated charcoal is effective at 6 hours" },
      { label: "D", text: "LFTs only — treat if ALT elevated" },
      { label: "E", text: "Start N-acetylcysteine for all paracetamol overdoses regardless of level" },
    ],
    correctAnswer: "B",
    explanation: "Paracetamol overdose: asymptomatic early (liver damage occurs 24–72h). Serum paracetamol level at ≥4 hours post-ingestion → plot on Rumack-Matthew nomogram. If above treatment line → IV N-acetylcysteine (NAC) immediately. NAC most effective <8h. Activated charcoal only if <2h and alert/protected airway. Always psychiatric assessment after intentional overdose.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-003", topic: "Emergency Medicine", subtopic: "Trauma",
    stem: "A 30-year-old man is brought in after a motorbike accident. GCS 14 (E3V4M5), BP 95/70, HR 128, RR 28. He has decreased breath sounds on the left and a deviated trachea to the right. What is the immediate management?",
    options: [
      { label: "A", text: "CXR to confirm diagnosis" },
      { label: "B", text: "CT chest immediately" },
      { label: "C", text: "Needle decompression of left chest immediately" },
      { label: "D", text: "Intubate and ventilate first" },
      { label: "E", text: "IV fluid resuscitation 2 L" },
    ],
    correctAnswer: "C",
    explanation: "Tension pneumothorax: trachea deviated AWAY from affected side, absent breath sounds on affected side, haemodynamic instability. Clinical diagnosis — do NOT wait for CXR. Immediate needle decompression (14-16G needle, 2nd ICS, midclavicular line). Then definitive chest drain. In intubated patients, sudden deterioration after intubation + tension → needle decompression.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "em-004", topic: "Emergency Medicine", subtopic: "Burns",
    stem: "A 35-year-old man sustains burns from a house fire. He has circumferential full-thickness burns to the right arm and superficial partial-thickness burns to the anterior trunk and right leg. Using the rule of nines, what is the TBSA% and what is the parkland formula fluid in 24 hours (weight 80 kg)?",
    options: [
      { label: "A", text: "TBSA 27%, fluid 8640 mL" },
      { label: "B", text: "TBSA 36%, fluid 11520 mL" },
      { label: "C", text: "TBSA 20%, fluid 6400 mL" },
      { label: "D", text: "TBSA 45%, fluid 14400 mL" },
      { label: "E", text: "TBSA 18%, fluid 5760 mL" },
    ],
    correctAnswer: "A",
    explanation: "Rule of nines: arm = 9%, anterior trunk = 18%, leg = 18%. Full-thickness arm (9%) + partial trunk half (18%/2 = 9%) + partial leg (9%) = 27% TBSA (using Lund-Browder for accuracy; rule of nines here gives approximation). Parkland formula: 4 mL × kg × TBSA = 4 × 80 × 27 = 8640 mL Hartmann's in 24h (half in first 8h from time of burn, remainder in next 16h). Superficial burns not included in fluid calculation.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "em-005", topic: "Emergency Medicine", subtopic: "Head Injury",
    stem: "A 22-year-old rugby player is knocked out briefly, regains consciousness, but 2 hours later becomes increasingly confused and vomits. GCS drops from 15 to 12. CT head shows a biconvex hyperdense lesion. What is the diagnosis?",
    options: [
      { label: "A", text: "Diffuse axonal injury" },
      { label: "B", text: "Extradural (epidural) haematoma — urgent neurosurgical evacuation" },
      { label: "C", text: "Subdural haematoma" },
      { label: "D", text: "Subarachnoid haemorrhage" },
      { label: "E", text: "Cerebral contusion" },
    ],
    correctAnswer: "B",
    explanation: "Extradural haematoma: biconvex hyperdense lesion on CT (blood between skull and dura). Classic: lucid interval then deterioration (blood from middle meningeal artery after temporal bone fracture). Management: urgent neurosurgical evacuation. Subdural: concave hyperdense lesion, bridging veins, often elderly. Prognosis of EDH excellent if treated early — excellent recovery.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-006", topic: "Emergency Medicine", subtopic: "Sepsis",
    stem: "A 70-year-old woman presents with fever 39.2°C, HR 115, BP 88/52, RR 26, and confusion. WBC 22.5. Urine is cloudy and malodorous. Lactate 3.8 mmol/L. What is the diagnosis and what bundle should be initiated within 1 hour?",
    options: [
      { label: "A", text: "Sepsis — blood cultures + oral antibiotics + monitor" },
      { label: "B", text: "Septic shock — Surviving Sepsis Bundle: cultures, IV broad-spectrum antibiotics, 30 mL/kg IV crystalloid, vasopressors if needed" },
      { label: "C", text: "SIRS — IV fluids only" },
      { label: "D", text: "UTI — IV antibiotics, no fluid bolus" },
      { label: "E", text: "Sepsis — antibiotics within 3 hours" },
    ],
    correctAnswer: "B",
    explanation: "Septic shock: sepsis + hypotension despite fluids + lactate ≥2 + organ dysfunction. Surviving Sepsis Campaign 1-hour bundle: blood cultures (before antibiotics), IV broad-spectrum antibiotics within 1 hour (critical), IV crystalloid 30 mL/kg for hypotension/lactate ≥4, vasopressors (noradrenaline first-line) if MAP <65 despite fluids. Lactate >2 indicates tissue hypoperfusion. Measure lactate 2-4 hourly.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-007", topic: "Emergency Medicine", subtopic: "Hypoglycaemia",
    stem: "A 65-year-old man with T2DM on gliclazide is brought in unconscious with BGL 1.8 mmol/L. He cannot swallow. What is the most appropriate immediate management?",
    options: [
      { label: "A", text: "Oral glucose gel placed in cheek" },
      { label: "B", text: "IM glucagon 1 mg" },
      { label: "C", text: "IV 50% dextrose 25–50 mL" },
      { label: "D", text: "Subcutaneous glucagon" },
      { label: "E", text: "IV normal saline infusion" },
    ],
    correctAnswer: "C",
    explanation: "Unconscious hypoglycaemia with no IV access: IM glucagon 1 mg (onset 10–15 min). WITH IV access: 50 mL of 50% dextrose IV (or 150 mL 10% dextrose). After recovery, oral carbohydrate to prevent recurrence. For sulfonylurea-induced hypoglycaemia (gliclazide): prolonged — patient must be observed for 24+ hours, may need dextrose infusion. Octreotide reduces sulfonylurea-induced insulin secretion in severe cases.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "em-008", topic: "Emergency Medicine", subtopic: "Acute Asthma",
    stem: "A 20-year-old presents with acute severe asthma (PEFR 40%, RR 28, HR 120, SpO2 93%). He is speaking in partial sentences. After back-to-back salbutamol nebulisers + ipratropium + IV hydrocortisone for 30 minutes, there is minimal improvement. What is the next step?",
    options: [
      { label: "A", text: "Repeat salbutamol continuously" },
      { label: "B", text: "IV magnesium sulphate 2 g over 20 minutes" },
      { label: "C", text: "Immediate intubation" },
      { label: "D", text: "Inhaled heliox" },
      { label: "E", text: "IV aminophylline infusion" },
    ],
    correctAnswer: "B",
    explanation: "Acute severe asthma not responding to initial therapy: IV MgSO4 2 g over 20 minutes (bronchodilates via calcium channel blockade). Evidence: reduces admission rate, improves PEFR. Consider IV salbutamol if nebulised salbutamol inadequate. Aminophylline: narrow therapeutic range, many interactions, rarely used. Intubation only as last resort (mechanically ventilating asthma carries high risk). CPAP/BiPAP as bridge to avoid intubation.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-009", topic: "Emergency Medicine", subtopic: "Overdose",
    stem: "A 30-year-old man is brought in unconscious with miosis, bradycardia, bradypnoea (RR 6), and needle track marks on his arms. SpO2 85%. What is the most important immediate treatment?",
    options: [
      { label: "A", text: "IV naloxone 0.4–2 mg" },
      { label: "B", text: "Activated charcoal" },
      { label: "C", text: "Flumazenil to reverse benzodiazepine effects" },
      { label: "D", text: "Intubation and ventilation" },
      { label: "E", text: "IV N-acetylcysteine" },
    ],
    correctAnswer: "A",
    explanation: "Opioid toxidrome: pinpoint miosis + bradypnoea + decreased consciousness. Immediate treatment: IV/IM/intranasal naloxone (opioid antagonist) 0.4–2 mg, repeat every 2–3 min up to 10 mg. Titrate to adequate respirations (not full reversal — causes withdrawal). Short half-life: naloxone infusion needed for long-acting opioids. Airway support (BVM) while preparing naloxone. Flumazenil for benzo overdose with no mixed ingestion.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "em-010", topic: "Emergency Medicine", subtopic: "Resuscitation",
    stem: "A 60-year-old man collapses in the waiting room. He is pulseless and unresponsive. The monitor shows VF. After initiating CPR, what is the next step?",
    options: [
      { label: "A", text: "IV adrenaline 1 mg before defibrillation" },
      { label: "B", text: "Immediate defibrillation (unsynchronised 200 J biphasic)" },
      { label: "C", text: "Intubate before defibrillation" },
      { label: "D", text: "Amiodarone 300 mg before defibrillation" },
      { label: "E", text: "Continue CPR for 2 minutes then defibrillate" },
    ],
    correctAnswer: "B",
    explanation: "VF/Pulseless VT: immediate unsynchronised defibrillation is the most important intervention (180–200 J biphasic first shock). Resume CPR immediately after shock (2 minutes). Adrenaline 1 mg IV: after 3rd shock (i.e., 2nd cycle of CPR). Amiodarone 300 mg: after 3rd shock if VF/VT persists. Do NOT delay defibrillation for intubation. Each minute of VF without defibrillation → 10% survival decrease.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-011", topic: "Emergency Medicine", subtopic: "Acute Abdomen",
    stem: "A 28-year-old man presents with sudden severe diffuse abdominal pain. He has a rigid board-like abdomen with guarding and rebound tenderness. Upright AXR shows free air under the right hemidiaphragm. What is the diagnosis and immediate management?",
    options: [
      { label: "A", text: "Acute appendicitis — appendicectomy" },
      { label: "B", text: "Perforated viscus — IV antibiotics, NG tube, IV fluids, emergency surgery" },
      { label: "C", text: "Mesenteric ischaemia — CT angiography" },
      { label: "D", text: "Dissecting aortic aneurysm — CT aorta" },
      { label: "E", text: "Sigmoid volvulus — endoscopic decompression" },
    ],
    correctAnswer: "B",
    explanation: "Pneumoperitoneum (free air under diaphragm) + peritonitis = perforated viscus (peptic ulcer, appendix, diverticulum). Management: IV broad-spectrum antibiotics, IV fluids, NG tube (decompress stomach), Foley catheter, analgesia, urgent surgical consultation. Emergency laparotomy/laparoscopy for washout and repair. Most common cause: perforated duodenal ulcer. Erect CXR detects 75% of pneumoperitoneum.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "em-012", topic: "Emergency Medicine", subtopic: "Hyperglycaemic Emergency",
    stem: "A 75-year-old woman with T2DM is brought in confused and dehydrated. BGL 48 mmol/L. Sodium (corrected) 158 mEq/L. Serum osmolality 345 mOsm/kg. pH 7.38, bicarbonate 24. Ketones negative. What is the diagnosis and key treatment principle?",
    options: [
      { label: "A", text: "DKA — fixed-rate insulin infusion" },
      { label: "B", text: "HHS — slow rehydration with 0.9% saline targeting correction over 24–48h" },
      { label: "C", text: "HHS — rapid fluid replacement to correct within 4 hours" },
      { label: "D", text: "HONK — treat with bicarbonate" },
      { label: "E", text: "HHS — insulin is the primary treatment" },
    ],
    correctAnswer: "B",
    explanation: "HHS (Hyperosmolar Hyperglycaemic State): glucose >30, osmolality >320, minimal ketones, no significant acidosis. Elderly T2DM. Treatment: 0.9% saline to restore circulating volume SLOWLY (24–48h) — rapid correction risks cerebral oedema, central pontine myelinolysis. Target Na correction <10 mEq/L/day, osmolality <3 mOsm/kg/hour. Insulin after initial fluid (lower dose than DKA). LMWH for DVT prophylaxis (high thrombotic risk).",
    reference: "amc", difficulty: "hard",
  },
];
