import type { MCQuestion } from "./questions";

export const infectiousQuestions: MCQuestion[] = [
  {
    id: "inf-001", topic: "Infectious Disease", subtopic: "HIV",
    stem: "A 35-year-old man is newly diagnosed with HIV. CD4 count is 280 cells/µL. HIV viral load 45,000 copies/mL. He has no AIDS-defining illness. What is the most appropriate management?",
    options: [
      { label: "A", text: "Start ART only if CD4 <200" },
      { label: "B", text: "Start ART immediately regardless of CD4 count + PCP prophylaxis" },
      { label: "C", text: "Observe and repeat CD4 in 3 months before starting ART" },
      { label: "D", text: "Start ART only if viral load >100,000" },
      { label: "E", text: "PCP prophylaxis alone until CD4 <200" },
    ],
    correctAnswer: "B",
    explanation: "Current HIV guidelines (DHHS, EACS): ART (antiretroviral therapy) recommended for ALL HIV-positive individuals regardless of CD4 count — reduces transmission, AIDS progression, and non-AIDS events. START trial confirmed benefit even at CD4 >500. CD4 280 → PCP prophylaxis indicated (CD4 <200: co-trimoxazole). Preferred first-line ART: integrase inhibitor-based (bictegravir/TAF/FTC or dolutegravir).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-002", topic: "Infectious Disease", subtopic: "HIV",
    stem: "A patient on HIV treatment (dolutegravir + TDF/FTC) presents with fever, dry cough, and dyspnoea. CD4 count is 45 cells/µL. CXR shows bilateral diffuse infiltrates. LDH is markedly elevated. What is the most likely diagnosis and treatment?",
    options: [
      { label: "A", text: "Community-acquired pneumonia — amoxicillin" },
      { label: "B", text: "PCP (Pneumocystis jirovecii pneumonia) — co-trimoxazole + prednisolone if pO2 <70" },
      { label: "C", text: "TB — RHEZ therapy" },
      { label: "D", text: "CMV pneumonitis — ganciclovir" },
      { label: "E", text: "Kaposi's sarcoma — chemotherapy" },
    ],
    correctAnswer: "B",
    explanation: "PCP: CD4 <200 (most common at CD4 <50), insidious onset dyspnoea, dry cough, bilateral perihilar infiltrates, ↑LDH. Diagnosis: bronchoalveolar lavage (methenamine silver stain). Treatment: high-dose IV/oral co-trimoxazole (TMP-SMX) for 21 days. Add prednisolone 40 mg BD if PaO2 <70 mmHg (reduces mortality). Prophylaxis: co-trimoxazole 1 DS tablet daily when CD4 <200.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-003", topic: "Infectious Disease", subtopic: "STI",
    stem: "A 22-year-old man presents with a painless penile ulcer with indurated edges and enlarged inguinal lymph nodes. TPHA and VDRL are both reactive. What is the diagnosis, stage, and treatment?",
    options: [
      { label: "A", text: "Genital herpes — aciclovir" },
      { label: "B", text: "Primary syphilis (Treponema pallidum) — benzathine penicillin G 2.4 MU IM once" },
      { label: "C", text: "Chancroid (Haemophilus ducreyi) — azithromycin" },
      { label: "D", text: "Lymphogranuloma venereum — doxycycline 21 days" },
      { label: "E", text: "Squamous cell carcinoma — biopsy" },
    ],
    correctAnswer: "B",
    explanation: "Primary syphilis: painless indurated ulcer (chancre) + non-tender inguinal lymphadenopathy. TPHA (specific treponemal test) + VDRL (non-specific, used for monitoring titre post-treatment). Treatment: benzathine penicillin 2.4 MU IM single dose. Doxycycline if penicillin allergy. Partner notification + testing essential. Secondary syphilis: rash on palms/soles, condylomata lata, alopecia. Latent: positive serology, no symptoms.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-004", topic: "Infectious Disease", subtopic: "STI",
    stem: "A 19-year-old woman presents with vaginal discharge and dysuria. High vaginal swab grows Chlamydia trachomatis (NAAT positive). She has a boyfriend of 3 months. What is the treatment and key counselling point?",
    options: [
      { label: "A", text: "Ciprofloxacin 500 mg single dose" },
      { label: "B", text: "Azithromycin 1 g stat (or doxycycline 100 mg BD × 7 days)" },
      { label: "C", text: "Metronidazole 400 mg BD × 7 days" },
      { label: "D", text: "Benzylpenicillin IM" },
      { label: "E", text: "No treatment — resolves spontaneously in most cases" },
    ],
    correctAnswer: "B",
    explanation: "Chlamydia: most common bacterial STI in Australia. Treatment: azithromycin 1 g stat (single dose, better compliance) or doxycycline 100 mg BD × 7 days (preferred for complicated infection). Partner notification and treatment mandatory (contact tracing). Test of cure not routinely required unless recurrence (azithromycin — no test of cure; doxycycline test of cure recommended). Screen for gonorrhoea concurrently.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "inf-005", topic: "Infectious Disease", subtopic: "Tropical",
    stem: "A 30-year-old man returns from a 2-week trip to West Africa with fever, rigors, headache, and myalgia starting 12 days after return. Temperature 39.8°C, splenomegaly. FBC: Hb 95, platelets 78. Blood film shows ring-form trophozoites and banana-shaped gametocytes. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Plasmodium vivax malaria" },
      { label: "B", text: "Plasmodium falciparum malaria — urgent treatment" },
      { label: "C", text: "Dengue fever" },
      { label: "D", text: "Typhoid fever" },
      { label: "E", text: "Viral haemorrhagic fever" },
    ],
    correctAnswer: "B",
    explanation: "Plasmodium falciparum malaria: banana-shaped gametocytes (pathognomonic), ring forms, travel to sub-Saharan Africa, anaemia, thrombocytopaenia, fever. Most dangerous form — can cause cerebral malaria, ARDS, renal failure, death. Treat as medical emergency. Treatment: artemether-lumefantrine (first-line uncomplicated) or IV artesunate (severe malaria). Chloroquine resistance widespread for falciparum.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "inf-006", topic: "Infectious Disease", subtopic: "Meningitis",
    stem: "A 25-year-old immunocompetent woman has acute bacterial meningitis. CT head is normal. LP is performed. CSF: WBC 1200 (90% neutrophils), protein 3.8 g/L, glucose 1.8 (serum 7.2 mmol/L). Gram stain shows Gram-positive cocci in pairs. Which is the most likely organism and treatment?",
    options: [
      { label: "A", text: "Neisseria meningitidis — benzylpenicillin" },
      { label: "B", text: "Streptococcus pneumoniae — ceftriaxone + dexamethasone" },
      { label: "C", text: "Listeria monocytogenes — ampicillin + gentamicin" },
      { label: "D", text: "Haemophilus influenzae — ceftriaxone" },
      { label: "E", text: "Cryptococcus — amphotericin B" },
    ],
    correctAnswer: "B",
    explanation: "Streptococcus pneumoniae meningitis: Gram-positive diplococci. Most common bacterial meningitis in adults. CSF: neutrophilia, high protein, very low glucose ratio (<0.3). Treatment: IV ceftriaxone 2 g BD + dexamethasone 0.15 mg/kg QDS for 4 days (reduces hearing loss and neurological sequelae in pneumococcal meningitis). Start dexamethasone with or before first antibiotic dose. Listeria in elderly, neonates, immunosuppressed.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-007", topic: "Infectious Disease", subtopic: "Hepatitis C",
    stem: "A 45-year-old man who previously injected drugs has anti-HCV antibodies positive. HCV RNA PCR is 2.3 × 10⁶ IU/mL. Genotype 1a. Liver biopsy shows F2 fibrosis. What is the current treatment?",
    options: [
      { label: "A", text: "Pegylated interferon + ribavirin for 48 weeks" },
      { label: "B", text: "Direct-acting antivirals (DAAs) — genotype-specific regimen × 8–12 weeks" },
      { label: "C", text: "No treatment — await new medications" },
      { label: "D", text: "Liver transplant assessment" },
      { label: "E", text: "Tenofovir + emtricitabine" },
    ],
    correctAnswer: "B",
    explanation: "HCV: DAAs (direct-acting antivirals) have revolutionised treatment. Pan-genotypic regimens: sofosbuvir/velpatasvir (Epclusa) 12 weeks or glecaprevir/pibrentasvir (Maviret) 8 weeks — >95% sustained virological response (SVR = cure). Available via PBS in Australia since 2016 for all genotypes, any fibrosis stage. No longer need to wait for fibrosis progression. Interferon/ribavirin largely obsolete. Test for cure: HCV RNA 12 weeks after completion.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-008", topic: "Infectious Disease", subtopic: "COVID/Respiratory Viruses",
    stem: "A 70-year-old immunosuppressed man on steroids for PMR develops influenza A confirmed by PCR. He presents within 36 hours of symptom onset with fever, myalgia, and cough. What is the most appropriate antiviral treatment?",
    options: [
      { label: "A", text: "No antiviral needed — supportive care only" },
      { label: "B", text: "Oseltamivir (Tamiflu) 75 mg BD × 5 days" },
      { label: "C", text: "Amantadine" },
      { label: "D", text: "Zanamivir inhaled" },
      { label: "E", text: "Aciclovir" },
    ],
    correctAnswer: "B",
    explanation: "Influenza antiviral treatment: oseltamivir indicated for high-risk patients (elderly, immunosuppressed, chronic disease, severe illness, hospitalised). Start within 48 hours of symptom onset — reduces duration, severity, and complications. 75 mg BD × 5 days (or 10 days for severe/immunosuppressed). Amantadine/rimantadine: resistance widespread in influenza A, not recommended. Zanamivir: inhaled, alternative if oseltamivir resistance. Annual vaccination most important prevention.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "inf-009", topic: "Infectious Disease", subtopic: "Skin and Soft Tissue",
    stem: "A 55-year-old diabetic woman has a hot, red, tender expanding area on her lower leg. Temperature 38.5°C, WBC 14.5. No crepitus. Skin is intact but erythematous. What is the most likely diagnosis and treatment?",
    options: [
      { label: "A", text: "DVT — Doppler ultrasound + anticoagulation" },
      { label: "B", text: "Cellulitis — oral flucloxacillin or cefalexin" },
      { label: "C", text: "Necrotising fasciitis — urgent surgical debridement" },
      { label: "D", text: "Contact dermatitis — topical steroids" },
      { label: "E", text: "Varicose eczema — emollients" },
    ],
    correctAnswer: "B",
    explanation: "Cellulitis: acute bacterial skin/subcutaneous infection. Most common organisms: Streptococcus pyogenes (Group A strep), Staphylococcus aureus. Mild: oral flucloxacillin (Staph coverage) or cefalexin. Penicillin allergy: doxycycline or clindamycin. If MRSA risk: doxycycline/trimethoprim. Inpatient IV for: systemic sepsis, rapid spread, facial cellulitis, immunosuppression, poor response to oral. Mark border with pen to monitor spread. Crepitus or rapidly spreading → necrotising fasciitis (emergency surgical debridement).",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "inf-010", topic: "Infectious Disease", subtopic: "Travel Medicine",
    stem: "A 28-year-old backpacker returns from Southeast Asia with 3 days of profuse rice-water diarrhoea, vomiting, and dehydration. He has no fever. Stool shows no blood. He is alert but significantly dehydrated. What is the treatment for likely cholera?",
    options: [
      { label: "A", text: "Loperamide to control diarrhoea" },
      { label: "B", text: "Aggressive oral/IV rehydration + doxycycline 300 mg single dose" },
      { label: "C", text: "IV ceftriaxone" },
      { label: "D", text: "Ciprofloxacin alone" },
      { label: "E", text: "Nothing by mouth and IV fluids only" },
    ],
    correctAnswer: "B",
    explanation: "Cholera (Vibrio cholerae): profuse rice-water diarrhoea, no fever, no blood. Dehydration is the cause of death. Treatment: aggressive rehydration (ORS for mild-moderate; IV Hartmann's/saline for severe) is PARAMOUNT. Antibiotics shorten illness and reduce excretion: doxycycline 300 mg single dose (first-line adults) or azithromycin. Avoid anti-motility agents — can increase complications. WHO ORS formula. Case notification required.",
    reference: "amc", difficulty: "medium",
  },
];
