import type { MCQuestion } from "./questions";

export const respiratoryQuestions: MCQuestion[] = [
  {
    id: "resp-001", topic: "Respiratory", subtopic: "Asthma",
    stem: "A 28-year-old woman with known asthma uses a reliever inhaler more than 3 times per week. She has night-time symptoms twice per week. Her peak flow variability is 25%. According to GINA guidelines, how should her asthma be classified?",
    options: [
      { label: "A", text: "Mild intermittent" },
      { label: "B", text: "Mild persistent" },
      { label: "C", text: "Moderate persistent" },
      { label: "D", text: "Severe persistent" },
      { label: "E", text: "Well-controlled asthma" },
    ],
    correctAnswer: "C",
    explanation: "Moderate persistent asthma: daily symptoms, night symptoms >1/week, reliever use daily, peak flow variability >30%. This patient has >3 reliever uses/week and nocturnal symptoms twice weekly. Step up to Step 3: low-dose ICS + LABA or medium-dose ICS.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-002", topic: "Respiratory", subtopic: "Asthma",
    stem: "A 16-year-old boy on budesonide/formoterol MART therapy has well-controlled asthma. His parents ask about exercise-induced bronchoconstriction during sport. What is the most appropriate advice?",
    options: [
      { label: "A", text: "Stop all exercise" },
      { label: "B", text: "Use SABA 15 minutes before exercise as prophylaxis" },
      { label: "C", text: "Use an extra MART inhaler dose before exercise" },
      { label: "D", text: "Double ICS dose permanently" },
      { label: "E", text: "Add montelukast to the regimen" },
    ],
    correctAnswer: "B",
    explanation: "Exercise-induced bronchoconstriction: pre-exercise SABA (salbutamol) 2 puffs 10–15 minutes before activity is the standard prophylaxis. MART therapy uses the same ICS/LABA inhaler as both maintenance and reliever, but pre-exercise SABA prophylaxis is well-established. Montelukast is an alternative preventive option.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-003", topic: "Respiratory", subtopic: "COPD",
    stem: "A 70-year-old ex-smoker with GOLD Stage 3 COPD (FEV1 35% predicted) presents with increasing breathlessness, increased sputum, and purulent green sputum for 3 days. What is this event called and the appropriate antibiotic?",
    options: [
      { label: "A", text: "Acute exacerbation COPD — amoxicillin or doxycycline" },
      { label: "B", text: "Pneumonia — IV ceftriaxone" },
      { label: "C", text: "Acute asthma — high-dose ICS" },
      { label: "D", text: "Pulmonary embolism — anticoagulation" },
      { label: "E", text: "Cardiac decompensation — diuretics" },
    ],
    correctAnswer: "A",
    explanation: "AECOPD: ≥2 of worsening dyspnoea, increased sputum, purulent sputum. Antibiotic indicated for purulent sputum. First-line: amoxicillin, doxycycline, or trimethoprim. Add oral prednisolone 30–40 mg for 5 days. Escalate antibiotics if Pseudomonas risk (frequent exacerbations, bronchiectasis) or hospitalised.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "resp-004", topic: "Respiratory", subtopic: "COPD",
    stem: "A 68-year-old man with severe COPD has resting PaO2 of 54 mmHg (SpO2 87%) on room air. He is clinically stable. What is the threshold for long-term oxygen therapy (LTOT) and minimum daily use?",
    options: [
      { label: "A", text: "PaO2 <70 mmHg — 8 hours/day" },
      { label: "B", text: "PaO2 <60 mmHg (SpO2 ≤88%) — at least 15 hours/day" },
      { label: "C", text: "PaO2 <55 mmHg — 24 hours/day" },
      { label: "D", text: "SpO2 <92% — as tolerated" },
      { label: "E", text: "Any hypoxaemia — supplemental oxygen at night only" },
    ],
    correctAnswer: "B",
    explanation: "LTOT criteria: PaO2 ≤55 mmHg (SpO2 ≤88%), or PaO2 56–59 mmHg with cor pulmonale, polycythaemia or pulmonary hypertension. Minimum 15 hours/day (including sleep). Survival benefit proven in NOTT and MRC trials — reduces pulmonary hypertension and polycythaemia. No benefit if PaO2 >60 mmHg at rest.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-005", topic: "Respiratory", subtopic: "Pneumonia",
    stem: "A 55-year-old man with alcoholism presents with fever, productive rust-coloured sputum, and lobar consolidation on CXR (right upper lobe). Gram stain shows Gram-positive diplococci. Which organism is most likely?",
    options: [
      { label: "A", text: "Klebsiella pneumoniae" },
      { label: "B", text: "Staphylococcus aureus" },
      { label: "C", text: "Streptococcus pneumoniae" },
      { label: "D", text: "Haemophilus influenzae" },
      { label: "E", text: "Legionella pneumophila" },
    ],
    correctAnswer: "C",
    explanation: "Streptococcus pneumoniae is the most common cause of CAP. Gram-positive diplococci, rust-coloured sputum (blood-tinged), lobar consolidation. Upper lobe involvement in alcoholics also suggests aspiration or Klebsiella (Gram-negative rods, 'currant jelly' sputum), but diplococci point to Streptococcus. Legionella: no organisms on Gram stain, detected by urinary antigen.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-006", topic: "Respiratory", subtopic: "Lung Cancer",
    stem: "A 65-year-old male smoker presents with haemoptysis, weight loss, and a right hilar mass on CXR. He also has new-onset gynaecomastia and low sodium (126 mmol/L). What type of lung cancer and paraneoplastic syndrome is most likely?",
    options: [
      { label: "A", text: "Adenocarcinoma — hypertrophic osteoarthropathy" },
      { label: "B", text: "Squamous cell carcinoma — hypercalcaemia" },
      { label: "C", text: "Small cell carcinoma — SIADH and gynaecomastia" },
      { label: "D", text: "Large cell carcinoma — Eaton-Lambert syndrome" },
      { label: "E", text: "Mesothelioma — pleural effusion" },
    ],
    correctAnswer: "C",
    explanation: "Small cell lung carcinoma (SCLC): central hilar mass, early metastasis. Paraneoplastic: SIADH (hyponatraemia), Cushing's (ectopic ACTH), Eaton-Lambert syndrome (proximal weakness — unlike MG, gets better with repeated use). Squamous cell: PTHrP → hypercalcaemia. Adenocarcinoma: peripheral, clubbing, hypertrophic osteoarthropathy.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-007", topic: "Respiratory", subtopic: "Lung Cancer",
    stem: "A 58-year-old woman (never smoker) presents with a 2.5 cm peripheral lung nodule on CT. She is well. CT-PET shows no lymph node or distant metastases (stage IA). What is the best treatment?",
    options: [
      { label: "A", text: "Chemotherapy" },
      { label: "B", text: "Stereotactic ablative radiotherapy (SABR)" },
      { label: "C", text: "Surgical resection (lobectomy)" },
      { label: "D", text: "CT surveillance for 2 years" },
      { label: "E", text: "Immunotherapy with pembrolizumab" },
    ],
    correctAnswer: "C",
    explanation: "Stage IA NSCLC (T1-2a, N0, M0): surgical resection (lobectomy + mediastinal lymph node dissection) is gold standard. 5-year survival 70–90% for stage IA. SABR is used for medically inoperable patients. Adjuvant chemotherapy not indicated for stage IA. Test for EGFR/ALK/ROS1 mutations especially in never-smokers (adenocarcinoma).",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-008", topic: "Respiratory", subtopic: "Pleural Effusion",
    stem: "A 55-year-old man has a right-sided pleural effusion. Thoracocentesis shows: protein 45 g/L (serum 72 g/L), LDH 350 U/L (serum 220 U/L), glucose 3.2 mmol/L, pH 7.15. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Transudative effusion — heart failure" },
      { label: "B", text: "Parapneumonic effusion (complicated)" },
      { label: "C", text: "Malignant effusion" },
      { label: "D", text: "Tuberculous effusion" },
      { label: "E", text: "Transudative effusion — hypoalbuminaemia" },
    ],
    correctAnswer: "B",
    explanation: "Light's criteria: exudate if any of: pleural:serum protein >0.5, pleural:serum LDH >0.6, pleural LDH >2/3 upper limit of normal. This is an exudate. pH <7.2 + glucose <3.3 in parapneumonic effusion = complicated (loculated) requiring chest drain. Simple parapneumonic: pH >7.2. Empyema: frank pus.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-009", topic: "Respiratory", subtopic: "Tuberculosis",
    stem: "A 32-year-old Indian immigrant presents with 3 months of cough, night sweats, and 8 kg weight loss. CXR shows right upper lobe cavitation. Sputum AFB smear is positive. What is standard first-line therapy?",
    options: [
      { label: "A", text: "Isoniazid + rifampicin for 6 months" },
      { label: "B", text: "RHEZ (rifampicin, isoniazid, ethambutol, pyrazinamide) for 2 months, then RH for 4 months" },
      { label: "C", text: "Azithromycin + rifampicin" },
      { label: "D", text: "Isoniazid alone for 9 months (latent TB)" },
      { label: "E", text: "IV amphotericin B" },
    ],
    correctAnswer: "B",
    explanation: "Active TB: standard 6-month regimen: RHEZ × 2 months (intensive phase) then RH × 4 months (continuation phase). Add pyridoxine (B6) with isoniazid to prevent peripheral neuropathy. Test for drug resistance before starting. Isolate smear-positive patients. Directly observed therapy (DOT) recommended.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-010", topic: "Respiratory", subtopic: "Pulmonary Embolism",
    stem: "A 42-year-old woman 6 weeks post-caesarean section develops sudden dyspnoea and right-sided pleuritic chest pain. SpO2 88% on room air. HR 112. The Wells PE score is 6. D-dimer is elevated. What is the next most appropriate investigation?",
    options: [
      { label: "A", text: "V/Q scan" },
      { label: "B", text: "CT pulmonary angiogram (CTPA)" },
      { label: "C", text: "Lower limb Doppler ultrasound" },
      { label: "D", text: "Echocardiogram" },
      { label: "E", text: "Treat empirically without imaging" },
    ],
    correctAnswer: "B",
    explanation: "Wells score ≥5 = high probability. CTPA is gold standard for PE diagnosis — highest sensitivity and specificity. V/Q scan used if CTPA contraindicated (renal failure, contrast allergy, pregnancy — lower radiation). With Wells >4 and elevated D-dimer, proceed directly to CTPA. Treat empirically with LMWH while awaiting CTPA if high probability and delay anticipated.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-011", topic: "Respiratory", subtopic: "Obstructive Sleep Apnoea",
    stem: "A 48-year-old obese man (BMI 36) presents with excessive daytime sleepiness, witnessed apnoeas, and snoring. Epworth sleepiness scale is 16/24. Polysomnography shows AHI of 32 events/hour with SpO2 nadir 82%. What is first-line treatment?",
    options: [
      { label: "A", text: "Weight loss only" },
      { label: "B", text: "Continuous positive airway pressure (CPAP)" },
      { label: "C", text: "Mandibular advancement splint" },
      { label: "D", text: "Uvulopalatopharyngoplasty (UPPP)" },
      { label: "E", text: "Modafinil for daytime sleepiness" },
    ],
    correctAnswer: "B",
    explanation: "OSA with AHI ≥30 = severe. First-line: CPAP therapy — reduces AHI, improves sleepiness, reduces cardiovascular risk. Mandibular advancement device for mild-moderate OSA or CPAP-intolerant patients. Weight loss is adjunct but rarely sufficient alone. Modafinil for residual sleepiness despite CPAP.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "resp-012", topic: "Respiratory", subtopic: "Bronchiectasis",
    stem: "A 45-year-old woman has recurrent respiratory infections since childhood. CT shows dilated, thickened bronchi predominantly in the lower lobes. She produces 50 mL of purulent sputum daily. What is the cornerstone of management?",
    options: [
      { label: "A", text: "Long-term oral azithromycin only" },
      { label: "B", text: "Airway clearance techniques + treat exacerbations" },
      { label: "C", text: "Inhaled corticosteroids" },
      { label: "D", text: "Long-term prophylactic amoxicillin" },
      { label: "E", text: "Surgical resection of affected lobes" },
    ],
    correctAnswer: "B",
    explanation: "Bronchiectasis management: airway clearance (chest physiotherapy, huffing, oscillating PEP devices) is the cornerstone. Treat exacerbations with targeted antibiotics (guided by sputum culture). Long-term azithromycin reduces exacerbations in frequent exacerbators but has resistance risk. ICS not recommended unless concurrent asthma. Identify underlying cause (CF, PCD, immunodeficiency).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-013", topic: "Respiratory", subtopic: "Interstitial Lung Disease",
    stem: "A 65-year-old male ex-smoker presents with progressive breathlessness and dry cough over 2 years. Examination reveals fine bibasal Velcro crackles and clubbing. HRCT shows honeycombing with traction bronchiectasis, predominantly basal. Spirometry: FVC 65%, TLC 68%, DLCO 50%. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Sarcoidosis" },
      { label: "B", text: "Idiopathic pulmonary fibrosis (IPF)" },
      { label: "C", text: "Hypersensitivity pneumonitis" },
      { label: "D", text: "Non-specific interstitial pneumonia (NSIP)" },
      { label: "E", text: "Cryptogenic organising pneumonia (COP)" },
    ],
    correctAnswer: "B",
    explanation: "IPF: older male, smoker, progressive dyspnoea, basal crackles, clubbing, restrictive pattern (↓FVC, ↓TLC, ↓DLCO), HRCT UIP pattern (basal honeycombing). Median survival 3–5 years. Antifibrotics (pirfenidone, nintedanib) slow decline. NSIP: younger, more homogeneous ground-glass. Sarcoidosis: upper lobe, bilateral hilar lymphadenopathy.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-014", topic: "Respiratory", subtopic: "Pneumothorax",
    stem: "A 22-year-old tall thin man presents with sudden right-sided chest pain and shortness of breath. CXR shows a 2.5 cm rim of air around the right lung. He is haemodynamically stable. SpO2 95%. What is the most appropriate management?",
    options: [
      { label: "A", text: "High-flow oxygen and discharge home with review in 24h" },
      { label: "B", text: "Needle aspiration" },
      { label: "C", text: "Intercostal catheter (chest drain)" },
      { label: "D", text: "Video-assisted thoracoscopic surgery (VATS)" },
      { label: "E", text: "CT chest to further characterise" },
    ],
    correctAnswer: "B",
    explanation: "Primary spontaneous pneumothorax (PSP) in young fit patient. Size 2.5 cm rim = >2 cm = large PSP. Symptomatic large PSP: needle aspiration first (less invasive, same success rate as chest drain for PSP). If unsuccessful, insert intercostal drain. Small (<2 cm) asymptomatic: observation + high-flow O2 ± discharge. VATS for recurrence (≥2nd episode).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-015", topic: "Respiratory", subtopic: "Pneumothorax",
    stem: "A 55-year-old man with COPD has worsening dyspnoea and right-sided chest pain. Examination shows absent breath sounds on the right, trachea deviated to the left, HR 130, BP 80/50. What is the immediate management?",
    options: [
      { label: "A", text: "CXR to confirm diagnosis" },
      { label: "B", text: "CT chest for characterisation" },
      { label: "C", text: "Needle decompression (2nd intercostal space, midclavicular line)" },
      { label: "D", text: "Urgent intercostal drain under ultrasound" },
      { label: "E", text: "High-flow oxygen and wait for imaging" },
    ],
    correctAnswer: "C",
    explanation: "Tension pneumothorax: haemodynamic compromise + absent breath sounds + tracheal deviation. Life-threatening emergency — do NOT wait for imaging. Immediate needle decompression: 14-16G needle, 2nd ICS, midclavicular line (or 4th-5th ICS, anterior axillary line per ATLS). Follow with formal intercostal drain insertion.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "resp-016", topic: "Respiratory", subtopic: "Haemoptysis",
    stem: "A 55-year-old male smoker presents with 3 episodes of blood-streaked sputum over 2 weeks. He is systemically well. CXR is normal. What is the most appropriate next investigation?",
    options: [
      { label: "A", text: "Sputum cytology and AFB" },
      { label: "B", text: "CT chest (high resolution)" },
      { label: "C", text: "Bronchoscopy" },
      { label: "D", text: "CT pulmonary angiogram" },
      { label: "E", text: "Repeat CXR in 6 weeks" },
    ],
    correctAnswer: "B",
    explanation: "Haemoptysis in a smoker >40 years, even with normal CXR, warrants CT chest to exclude lung cancer (CXR misses 20% of lung cancers). CT first, then bronchoscopy if CT shows central lesion or CT negative with ongoing haemoptysis. Bronchoscopy is the gold standard for endobronchial lesions.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-017", topic: "Respiratory", subtopic: "Sarcoidosis",
    stem: "A 32-year-old woman presents with bilateral ankle swelling, erythema nodosum, bilateral hilar lymphadenopathy on CXR, and uveitis. Serum ACE is elevated. What is the diagnosis and when is systemic treatment required?",
    options: [
      { label: "A", text: "Sarcoidosis — treat all patients with prednisolone" },
      { label: "B", text: "Sarcoidosis — treat only if symptomatic, progressive, or vital organs involved" },
      { label: "C", text: "Lymphoma — urgent CT staging" },
      { label: "D", text: "TB — RHEZ therapy" },
      { label: "E", text: "Löfgren syndrome — always requires immunosuppression" },
    ],
    correctAnswer: "B",
    explanation: "Löfgren syndrome (erythema nodosum + bilateral hilar lymphadenopathy + arthritis/uveitis) = good prognosis, often resolves spontaneously. Sarcoidosis treatment: prednisolone for symptomatic pulmonary disease, cardiac, neurological, ocular, or hypercalcaemia involvement. Asymptomatic hilar lymphadenopathy alone → surveillance. 60–70% of pulmonary sarcoidosis resolves without treatment.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-018", topic: "Respiratory", subtopic: "COPD",
    stem: "A 72-year-old woman with GOLD Stage 2 COPD has FEV1 58% predicted, 1 exacerbation last year, CAT score 16. Which is the recommended maintenance inhaler combination per GOLD 2023 guidelines?",
    options: [
      { label: "A", text: "SABA alone (salbutamol PRN)" },
      { label: "B", text: "ICS monotherapy (budesonide)" },
      { label: "C", text: "LAMA alone (tiotropium)" },
      { label: "D", text: "LAMA + LABA dual bronchodilation" },
      { label: "E", text: "Triple therapy LAMA + LABA + ICS" },
    ],
    correctAnswer: "D",
    explanation: "GOLD 2023: initial maintenance based on symptoms (CAT) and exacerbation risk. CAT ≥10 = significant symptoms. 1 moderate exacerbation = moderate risk. GOLD group B/E: LAMA+LABA dual bronchodilator recommended for initial therapy. Triple (LAMA+LABA+ICS) for ≥2 exacerbations or 1 hospitalisation, especially if blood eosinophils ≥300.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-019", topic: "Respiratory", subtopic: "Cystic Fibrosis",
    stem: "A 22-year-old man with known cystic fibrosis presents with increased dyspnoea, purulent sputum, and FEV1 drop of 15% from baseline. Sputum culture grows Pseudomonas aeruginosa. What is the most appropriate antibiotic?",
    options: [
      { label: "A", text: "Oral amoxicillin" },
      { label: "B", text: "IV tobramycin + anti-pseudomonal beta-lactam" },
      { label: "C", text: "Oral doxycycline" },
      { label: "D", text: "Inhaled DNase (dornase alfa)" },
      { label: "E", text: "IV meropenem alone" },
    ],
    correctAnswer: "B",
    explanation: "CF exacerbation with Pseudomonas: IV combination therapy required (aminoglycoside + anti-pseudomonal beta-lactam: piperacillin-tazobactam, ceftazidime, or meropenem + tobramycin/gentamicin). Combination reduces resistance. IV preferred for significant exacerbations. Inhaled tobramycin for maintenance between exacerbations. Monitor renal function and tobramycin levels.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-020", topic: "Respiratory", subtopic: "Respiratory Failure",
    stem: "An ABG in a 70-year-old man with COPD shows: pH 7.28, PaCO2 72 mmHg, PaO2 48 mmHg, HCO3 30 mmol/L on room air. What type of respiratory failure and what immediate oxygen target?",
    options: [
      { label: "A", text: "Type 1 (hypoxic) — target SpO2 94–98%" },
      { label: "B", text: "Type 2 (hypercapnic) — target SpO2 88–92%" },
      { label: "C", text: "Type 2 — give high-flow O2 immediately" },
      { label: "D", text: "Type 1 — BiPAP immediately" },
      { label: "E", text: "Type 2 — target SpO2 >95%" },
    ],
    correctAnswer: "B",
    explanation: "Type 2 RF: ↑PaCO2 + ↓PaO2 (hypoxic + hypercapnic). In COPD, hypoxic drive to breathe — high-flow O2 can worsen hypercapnia. Target SpO2 88–92% in COPD/Type 2 RF. Metabolic compensation: ↑HCO3 = chronic component. Acute on chronic: pH 7.28 = acidaemia. If worsening → NIV (BiPAP).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "resp-021", topic: "Respiratory", subtopic: "Asthma",
    stem: "A 10-year-old boy has life-threatening asthma: SpO2 88%, PEFR <33% predicted, silent chest, cyanosis. He has received 3× salbutamol nebulisers and IV steroids. What is the next most important intervention?",
    options: [
      { label: "A", text: "IV aminophylline" },
      { label: "B", text: "IV magnesium sulphate (MgSO4)" },
      { label: "C", text: "Heliox (helium-oxygen mixture)" },
      { label: "D", text: "Ketamine anaesthesia + intubation" },
      { label: "E", text: "IV salbutamol infusion" },
    ],
    correctAnswer: "B",
    explanation: "Life-threatening asthma (PEFR <33%, silent chest, cyanosis): after bronchodilators and steroids, add IV MgSO4 40 mg/kg (max 2 g) over 20 minutes. Bronchodilates smooth muscle independently of β2-receptors. Evidence from RCTs: reduces hospitalisation. IV salbutamol/aminophylline have more adverse effects. Intubation as last resort — high risk in severe asthma.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "resp-022", topic: "Respiratory", subtopic: "Smoking Cessation",
    stem: "A 50-year-old male smoker (30 pack-years) wants to quit. He has tried willpower alone twice and nicotine patches once without success. He has depression managed with sertraline. What is the most effective pharmacotherapy?",
    options: [
      { label: "A", text: "Nicotine replacement therapy (NRT) patch alone" },
      { label: "B", text: "Combination NRT (patch + lozenge)" },
      { label: "C", text: "Varenicline (Champix)" },
      { label: "D", text: "Bupropion (Zyban)" },
      { label: "E", text: "Nortriptyline" },
    ],
    correctAnswer: "C",
    explanation: "Varenicline is the most effective single pharmacotherapy for smoking cessation (OR ~3x vs placebo). Partial agonist at α4β2 nAChRs — reduces cravings and withdrawal, blocks nicotine reward. Bupropion has a seizure risk, may interact with sertraline (serotonin). Combination NRT also effective. Monitor mood changes on varenicline, though serious psychiatric events are rare.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "resp-023", topic: "Respiratory", subtopic: "COVID-19/Viral Pneumonia",
    stem: "A 62-year-old man with diabetes is hospitalised with COVID-19 pneumonia. SpO2 91% on 4 L/min O2 via nasal prongs. CRP 220, D-dimer 4.5. He is not on ICU. Which medication has proven mortality benefit in this scenario?",
    options: [
      { label: "A", text: "Hydroxychloroquine" },
      { label: "B", text: "Azithromycin" },
      { label: "C", text: "Dexamethasone 6 mg daily for 10 days" },
      { label: "D", text: "Convalescent plasma" },
      { label: "E", text: "Ivermectin" },
    ],
    correctAnswer: "C",
    explanation: "RECOVERY trial: dexamethasone 6 mg/day × 10 days reduced 28-day mortality in COVID-19 patients requiring oxygen or ventilation. Number needed to treat: 8 for ventilated patients, 25 for those on O2 only. No benefit (possible harm) without oxygen requirement. Remdesivir reduces time to recovery. IL-6 inhibitors (tocilizumab) for rapid oxygen escalation.",
    reference: "amc", difficulty: "medium",
  },
];
