import type { MCQuestion } from "./questions";

export const gastroQuestions: MCQuestion[] = [
  {
    id: "gi-001", topic: "Gastroenterology", subtopic: "Liver Disease",
    stem: "A 45-year-old male presents with jaundice, ascites, and asterixis. He has been drinking 12 standard drinks daily for 20 years. INR 1.8, bilirubin 180, albumin 22. Child-Pugh score is 10. What is the Child-Pugh class and prognosis?",
    options: [
      { label: "A", text: "Class A — 1-year survival 100%" },
      { label: "B", text: "Class B — 1-year survival 80%" },
      { label: "C", text: "Class C — 1-year survival 45%" },
      { label: "D", text: "Class C — 1-year survival 10%" },
      { label: "E", text: "Class B — 1-year survival 60%" },
    ],
    correctAnswer: "C",
    explanation: "Child-Pugh score 10 = Class C (10–15). 1-year survival ~45%, 2-year ~35%. Factors: bilirubin, albumin, INR, ascites, encephalopathy. Class C patients should be considered for liver transplantation if abstinent from alcohol. This patient has likely decompensated alcoholic cirrhosis.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "gi-002", topic: "Gastroenterology", subtopic: "Liver Disease",
    stem: "A patient with cirrhosis develops new-onset ascites. Paracentesis is performed. SAAG (serum-ascites albumin gradient) is 1.2 g/dL. What does this indicate and what is the most likely cause?",
    options: [
      { label: "A", text: "SAAG <1.1 — exudate, likely peritoneal carcinomatosis" },
      { label: "B", text: "SAAG ≥1.1 — transudate, portal hypertension" },
      { label: "C", text: "SAAG <1.1 — spontaneous bacterial peritonitis" },
      { label: "D", text: "SAAG ≥1.1 — tuberculous peritonitis" },
      { label: "E", text: "SAAG is not useful in cirrhosis" },
    ],
    correctAnswer: "B",
    explanation: "SAAG ≥1.1 g/dL indicates portal hypertension (96% accuracy) — causes: cirrhosis, heart failure, Budd-Chiari. SAAG <1.1 = low portal pressure — causes: peritoneal carcinomatosis, TB, nephrotic syndrome, pancreatitis. SAAG = serum albumin minus ascites albumin. This patient's cirrhosis with SAAG 1.2 confirms portal hypertensive ascites.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "gi-003", topic: "Gastroenterology", subtopic: "Liver Disease",
    stem: "A 50-year-old man with known cirrhosis (Child-Pugh A) has an AFP of 850 ng/mL and ultrasound showing a 2.8 cm hepatic nodule with arterial enhancement and washout on contrast CT. What is the most appropriate management?",
    options: [
      { label: "A", text: "Liver biopsy to confirm HCC" },
      { label: "B", text: "Surgical resection or locoregional therapy (TACE/ablation)" },
      { label: "C", text: "Chemotherapy (sorafenib)" },
      { label: "D", text: "Repeat AFP in 3 months" },
      { label: "E", text: "Referral for liver transplantation immediately" },
    ],
    correctAnswer: "B",
    explanation: "HCC diagnosis: in cirrhotic patient, arterial enhancement + washout on CT/MRI = diagnostic for HCC — no biopsy required (LIRADS 5). Milan criteria (single lesion <5cm or ≤3 lesions <3cm, no vascular invasion, no metastases) met here. Surgical resection if adequate liver reserve (Child-Pugh A, no portal hypertension). Liver transplant if outside resection criteria but within Milan criteria.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "gi-004", topic: "Gastroenterology", subtopic: "IBD",
    stem: "A 28-year-old woman presents with 6 weeks of bloody diarrhoea (8 times/day), abdominal cramps, and fever 38.2°C. Colonoscopy shows continuous inflammation from rectum to splenic flexure, with ulceration and friability. Biopsy shows crypt abscesses. What is the diagnosis?",
    options: [
      { label: "A", text: "Crohn's disease" },
      { label: "B", text: "Ulcerative colitis (UC)" },
      { label: "C", text: "Infectious colitis" },
      { label: "D", text: "Ischaemic colitis" },
      { label: "E", text: "Microscopic colitis" },
    ],
    correctAnswer: "B",
    explanation: "UC: continuous from rectum proximally, mucosal/submucosal inflammation, bloody diarrhoea, crypt abscesses, pseudopolyps. Crohn's: skip lesions, transmural, rectal sparing, cobblestone, fistulas, RLQ > LLQ. Infectious colitis: stool culture positive. Severity (Truelove-Witts): mild <4 stools/day, moderate 4–6, severe >6 + systemic features.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-005", topic: "Gastroenterology", subtopic: "IBD",
    stem: "A 32-year-old man with known Crohn's disease presents with weight loss, diarrhoea, and a tender right iliac fossa mass. CT shows terminal ileal thickening with a 4 cm abscess. What is the most appropriate management?",
    options: [
      { label: "A", text: "Immediate surgery for bowel resection" },
      { label: "B", text: "High-dose oral prednisolone" },
      { label: "C", text: "CT-guided abscess drainage + IV antibiotics" },
      { label: "D", text: "Anti-TNF therapy (infliximab)" },
      { label: "E", text: "Colonoscopy to assess extent" },
    ],
    correctAnswer: "C",
    explanation: "Abdominal abscess in Crohn's: CT-guided percutaneous drainage + IV antibiotics (metronidazole + ciprofloxacin or co-amoxiclav). Drain first, then definitive surgical resection or anti-TNF therapy once sepsis controlled. Anti-TNF contraindicated in undrained sepsis. Steroids should not be used in the presence of abscess.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-006", topic: "Gastroenterology", subtopic: "Colorectal Cancer",
    stem: "A 58-year-old man presents with 3 months of change in bowel habit (alternating constipation/diarrhoea), and a positive faecal occult blood test. He has no family history. What is the gold-standard investigation?",
    options: [
      { label: "A", text: "Flexible sigmoidoscopy" },
      { label: "B", text: "CT colonography" },
      { label: "C", text: "Colonoscopy" },
      { label: "D", text: "Faecal calprotectin" },
      { label: "E", text: "MRI pelvis" },
    ],
    correctAnswer: "C",
    explanation: "Colonoscopy is gold standard for colorectal cancer investigation: visualises the entire colon, allows biopsy, polypectomy. Red-flag symptoms (change in bowel habit, rectal bleeding, weight loss, anaemia, abdominal mass) warrant urgent colonoscopy. FOBT positive → colonoscopy within 30 days (National Bowel Cancer Screening Program). CT colonography for those unable to tolerate colonoscopy.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "gi-007", topic: "Gastroenterology", subtopic: "Peptic Ulcer",
    stem: "A 50-year-old man tests positive for H. pylori on CLO test during OGD for epigastric pain. A 12 mm duodenal ulcer is found. What is the first-line eradication regimen in Australia?",
    options: [
      { label: "A", text: "Omeprazole + amoxicillin + clarithromycin × 7 days" },
      { label: "B", text: "Omeprazole + metronidazole × 14 days" },
      { label: "C", text: "Quadruple therapy: PPI + bismuth + metronidazole + tetracycline × 14 days" },
      { label: "D", text: "PPI alone for 8 weeks" },
      { label: "E", text: "Omeprazole + amoxicillin + clarithromycin + metronidazole × 7 days (concomitant)" },
    ],
    correctAnswer: "A",
    explanation: "Australian first-line H. pylori eradication: PPI + amoxicillin 1g BD + clarithromycin 500mg BD × 7 days (triple therapy). Confirm eradication with urea breath test 4 weeks post-treatment. If clarithromycin resistance suspected or first-line fails → quadruple bismuth therapy. Always continue PPI for 4–8 weeks total for duodenal ulcer healing.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-008", topic: "Gastroenterology", subtopic: "Pancreatitis",
    stem: "A 40-year-old woman with gallstones presents with severe epigastric pain radiating to the back, vomiting, and fever. Lipase is 4500 U/L. CT at 72 hours shows 40% pancreatic necrosis. What scoring system predicts severity and what does a score ≥8 imply?",
    options: [
      { label: "A", text: "Ranson criteria — score ≥8 = mild disease" },
      { label: "B", text: "APACHE II — score ≥8 = severe, high mortality" },
      { label: "C", text: "Glasgow criteria — score ≥8 = moderate" },
      { label: "D", text: "Child-Pugh — for liver involvement" },
      { label: "E", text: "CURB-65 — for respiratory involvement" },
    ],
    correctAnswer: "B",
    explanation: "APACHE II ≥8 = severe acute pancreatitis with high mortality. Other scores used: Ranson criteria (≥3 at 48h = severe), Glasgow (≥3 = severe), BISAP score, Revised Atlanta Classification. CT Severity Index (Balthazar) uses CT findings. Pancreatic necrosis >30% with organ failure = severe AP requiring ICU. Early IV fluids (goal-directed) are cornerstone of management.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "gi-009", topic: "Gastroenterology", subtopic: "GORD",
    stem: "A 45-year-old obese woman has heartburn and regurgitation for 2 years, worse after meals and at night. She responds well to omeprazole. Endoscopy shows Barrett's oesophagus (confirmed on biopsy as specialised intestinal metaplasia, no dysplasia). What surveillance is recommended?",
    options: [
      { label: "A", text: "No surveillance needed" },
      { label: "B", text: "Endoscopy every 6 months" },
      { label: "C", text: "Endoscopy every 2 years" },
      { label: "D", text: "Immediate ablative therapy (RFA)" },
      { label: "E", text: "Prophylactic oesophagectomy" },
    ],
    correctAnswer: "C",
    explanation: "Barrett's oesophagus without dysplasia: endoscopic surveillance every 2–3 years (British Society of Gastroenterology guidelines; some guidelines allow 3–5 years for short-segment). With low-grade dysplasia: 6-monthly. High-grade dysplasia → endoscopic ablation (radiofrequency ablation). Oesophagectomy only for T1b cancer. Continue PPI lifelong.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-010", topic: "Gastroenterology", subtopic: "Colorectal Cancer",
    stem: "A 45-year-old man has a first-degree relative (father) diagnosed with colorectal cancer at age 55. At what age should he begin colonoscopic screening?",
    options: [
      { label: "A", text: "40 years old" },
      { label: "B", text: "45 years old" },
      { label: "C", text: "50 years old" },
      { label: "D", text: "55 years old" },
      { label: "E", text: "No screening until symptoms develop" },
    ],
    correctAnswer: "A",
    explanation: "Family history risk stratification (Cancer Council Australia): one first-degree relative with CRC ≥55 years = slightly increased risk → colonoscopy at 50 or 10 years before the youngest affected relative (whichever is earlier). One FDR with CRC <55 years or two FDRs = moderately increased risk → colonoscopy at 40, then 5-yearly. This patient: FDR 55 → start at 45 (10 yrs before). Answer A (40) would apply if father was diagnosed at 50.",
    reference: "racgp-redbook", difficulty: "hard",
  },
  {
    id: "gi-011", topic: "Gastroenterology", subtopic: "Hepatitis",
    stem: "A 35-year-old woman presents with fatigue, jaundice, and RUQ tenderness. Serology: HBsAg positive, HBeAg positive, anti-HBc IgM positive, anti-HBs negative, HBV DNA 2.5 × 10⁸ IU/mL. ALT 1200 U/L. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Chronic hepatitis B, immune active phase" },
      { label: "B", text: "Acute hepatitis B" },
      { label: "C", text: "Resolved hepatitis B" },
      { label: "D", text: "Occult hepatitis B" },
      { label: "E", text: "Vaccinated, no infection" },
    ],
    correctAnswer: "B",
    explanation: "Acute HBV: HBsAg + anti-HBc IgM + HBeAg + high viral load. Anti-HBc IgM = acute or recent infection (≤6 months). Anti-HBs negative (not yet seroconverting). Chronic HBV: HBsAg persists >6 months + anti-HBc IgG (not IgM). Resolved: anti-HBs + anti-HBc, no HBsAg. Vaccinated: anti-HBs only (no anti-HBc).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-012", topic: "Gastroenterology", subtopic: "Hepatitis",
    stem: "A 40-year-old man with chronic hepatitis B (HBsAg positive for 10 years) has HBV DNA 28,000 IU/mL, ALT 85 U/L (2× ULN). Biopsy shows moderate inflammation (grade 2) and fibrosis (stage 2). What is the appropriate management?",
    options: [
      { label: "A", text: "Observe — no treatment unless cirrhosis develops" },
      { label: "B", text: "Interferon-alpha monotherapy for 48 weeks" },
      { label: "C", text: "Entecavir or tenofovir disoproxil fumarate (TDF)" },
      { label: "D", text: "Lamivudine (first choice due to low cost)" },
      { label: "E", text: "Liver transplantation assessment" },
    ],
    correctAnswer: "C",
    explanation: "Chronic HBV with significant fibrosis (stage 2+) and active replication → treatment indicated. First-line oral antivirals: entecavir or tenofovir (TDF/TAF) — high barrier to resistance. Lamivudine has high resistance rates (avoid). Interferon for selected patients (younger, high ALT, low viral load, no cirrhosis). Treat indefinitely for cirrhotic patients; consider stopping in non-cirrhotic after HBeAg seroconversion.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-013", topic: "Gastroenterology", subtopic: "Haemochromatosis",
    stem: "A 45-year-old man of European background presents with fatigue, joint pains, and bronze skin. Fasting transferrin saturation is 72% (normal <45%). Ferritin 1850 µg/L. LFTs elevated. What is the most likely diagnosis and treatment?",
    options: [
      { label: "A", text: "Anaemia of chronic disease — iron infusion" },
      { label: "B", text: "Hereditary haemochromatosis (HFE gene C282Y) — venesection" },
      { label: "C", text: "Secondary haemosiderosis — chelation therapy" },
      { label: "D", text: "Thalassaemia major — transfusion" },
      { label: "E", text: "Wilson's disease — D-penicillamine" },
    ],
    correctAnswer: "B",
    explanation: "Hereditary haemochromatosis: transferrin saturation >45% (key screening marker), elevated ferritin, bronze skin, arthropathy (MCP joints particularly), liver disease, DM (bronze diabetes), hypogonadism, cardiomyopathy. HFE gene C282Y homozygote. Treatment: therapeutic venesection (phlebotomy) 1 unit/week until ferritin <50 µg/L, then 3–4 monthly maintenance. Screen first-degree relatives.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-014", topic: "Gastroenterology", subtopic: "Coeliac Disease",
    stem: "A 28-year-old woman presents with iron deficiency anaemia, bloating, and diarrhoea. Anti-TTG IgA antibody is 8x ULN. IgA level is normal. She is currently eating gluten. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Start gluten-free diet immediately" },
      { label: "B", text: "HLA-DQ2/DQ8 genetic testing" },
      { label: "C", text: "Duodenal biopsy (upper endoscopy)" },
      { label: "D", text: "Anti-endomysial antibody (EMA)" },
      { label: "E", text: "Trial of lactose-free diet" },
    ],
    correctAnswer: "C",
    explanation: "Positive anti-TTG IgA → confirm with duodenal biopsy (Marsh classification: villous atrophy). Biopsy must be done while eating gluten. Normal IgA excludes IgA deficiency as confounder. Do NOT start GFD before biopsy (will normalise serology and histology, making diagnosis difficult). GFD is lifelong treatment and requires confirmation.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-015", topic: "Gastroenterology", subtopic: "Acute Abdomen",
    stem: "A 70-year-old woman on warfarin presents with sudden severe abdominal pain, bloody diarrhoea, and AF. Her INR is 3.2. Lactate is 4.5 mmol/L. CT shows bowel wall thickening in the distribution of the superior mesenteric artery. What is the diagnosis?",
    options: [
      { label: "A", text: "Ischaemic colitis (venous)" },
      { label: "B", text: "Acute mesenteric ischaemia (arterial embolism)" },
      { label: "C", text: "Clostridium difficile colitis" },
      { label: "D", text: "Diverticulitis with microperforation" },
      { label: "E", text: "Acute severe ulcerative colitis" },
    ],
    correctAnswer: "B",
    explanation: "AF → cardioembolism → SMA embolism = acute mesenteric ischaemia. Classic: sudden severe abdominal pain 'out of proportion to findings', bloody diarrhoea, AF, elevated lactate. CT angiography is diagnostic. Requires urgent surgical/vascular intervention — embolectomy or catheter-directed thrombolysis. High mortality if bowel infarction occurs. Anticoagulate with UFH immediately.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "gi-016", topic: "Gastroenterology", subtopic: "Constipation",
    stem: "A 70-year-old woman presents with constipation, abdominal bloating, and pencil-thin stools for 2 months. She has lost 4 kg. Rectal examination reveals a mass. CEA is elevated. What is the first investigation priority?",
    options: [
      { label: "A", text: "Colonoscopy with biopsy" },
      { label: "B", text: "Barium enema" },
      { label: "C", text: "CT abdomen and pelvis" },
      { label: "D", text: "Stool culture for C. difficile" },
      { label: "E", text: "Flexible sigmoidoscopy" },
    ],
    correctAnswer: "A",
    explanation: "Red flag constipation: age >50, change in bowel habit, weight loss, rectal mass, elevated CEA → urgent investigation for colorectal cancer. Colonoscopy allows direct visualisation, biopsy, and staging of rectal mass. CT for staging after histological diagnosis. Refer urgently — 2-week wait pathway.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "gi-017", topic: "Gastroenterology", subtopic: "Diverticular Disease",
    stem: "A 65-year-old man presents with left iliac fossa pain, fever 38.5°C, and elevated WCC. CT shows pericolic fat stranding and a 2 cm pericolic abscess. No free air or peritonitis. What is the appropriate management?",
    options: [
      { label: "A", text: "Emergency laparotomy and Hartmann's procedure" },
      { label: "B", text: "IV antibiotics + CT-guided percutaneous drainage" },
      { label: "C", text: "Oral antibiotics alone as outpatient" },
      { label: "D", text: "Colonoscopy to confirm diverticulitis" },
      { label: "E", text: "IV antibiotics without drainage — will resolve spontaneously" },
    ],
    correctAnswer: "B",
    explanation: "Hinchey Stage II diverticular abscess (pericolic/pelvic): IV antibiotics + CT-guided percutaneous drainage if technically feasible. Surgery reserved for: peritonitis (Hinchey III/IV), failure to respond to drainage, recurrence after 2 episodes. Colonoscopy after 6–8 weeks (NOT during acute phase — perforation risk). Oral antibiotics appropriate for uncomplicated Hinchey I.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-018", topic: "Gastroenterology", subtopic: "Rectal Bleeding",
    stem: "A 25-year-old man presents with painless bright red rectal bleeding noted on wiping after defaecation. The bleeding is on the surface of the stool. No family history. Proctoscopy shows internal haemorrhoids. What is first-line management?",
    options: [
      { label: "A", text: "Haemorrhoidectomy" },
      { label: "B", text: "Rubber band ligation" },
      { label: "C", text: "Dietary fibre + increased fluid intake + sitz baths" },
      { label: "D", text: "Colonoscopy" },
      { label: "E", text: "Topical corticosteroids" },
    ],
    correctAnswer: "C",
    explanation: "Grade I–II internal haemorrhoids: first-line = conservative management (high-fibre diet ≥25 g/day, adequate fluid intake, sitz baths, avoid straining). If conservative fails: rubber band ligation (most effective outpatient procedure, grade I–III). Haemorrhoidectomy for grade III–IV or failed banding. Colonoscopy only if red flags present or age >45.",
    reference: "murtagh", difficulty: "easy",
  },
  {
    id: "gi-019", topic: "Gastroenterology", subtopic: "Gallstones",
    stem: "A 45-year-old obese woman presents with episodic RUQ pain lasting 30–60 minutes after fatty meals. Ultrasound shows multiple gallstones. LFTs and bilirubin are normal. The pain has occurred 5 times in 6 months. What is the recommended management?",
    options: [
      { label: "A", text: "Low-fat diet and watchful waiting" },
      { label: "B", text: "Ursodeoxycholic acid for stone dissolution" },
      { label: "C", text: "Laparoscopic cholecystectomy" },
      { label: "D", text: "ERCP for stone extraction" },
      { label: "E", text: "Open cholecystectomy" },
    ],
    correctAnswer: "C",
    explanation: "Symptomatic cholelithiasis (biliary colic ≥2 episodes): laparoscopic cholecystectomy is definitive treatment. Prevents recurrence and complications (cholecystitis, choledocholithiasis, gallstone pancreatitis, cholangitis). ERCP for choledocholithiasis (CBD stones). Ursodeoxycholic acid for high surgical risk patients (elderly, comorbidities). Dietary modification does not prevent attacks reliably.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "gi-020", topic: "Gastroenterology", subtopic: "Acute Cholangitis",
    stem: "A 68-year-old woman presents with Charcot's triad: RUQ pain, fever, and jaundice. LFTs: ALP 450, GGT 380, bilirubin 85, ALT 120. Ultrasound shows CBD dilation 12 mm. What is the appropriate management?",
    options: [
      { label: "A", text: "IV antibiotics, then elective ERCP in 4–6 weeks" },
      { label: "B", text: "IV antibiotics + urgent ERCP within 24–48 hours" },
      { label: "C", text: "Emergency laparotomy and CBD exploration" },
      { label: "D", text: "IV antibiotics alone — ERCP not required" },
      { label: "E", text: "Percutaneous transhepatic cholangiography (PTC)" },
    ],
    correctAnswer: "B",
    explanation: "Acute cholangitis: Charcot's triad (pain + fever + jaundice). Reynolds' pentad + confusion + septic shock = severe. Management: IV antibiotics (piperacillin-tazobactam or ciprofloxacin + metronidazole) + urgent ERCP within 24–48h for biliary decompression and stone extraction. Delay increases mortality. ERCP is gold standard for choledocholithiasis.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-021", topic: "Gastroenterology", subtopic: "Jaundice",
    stem: "A 55-year-old man presents with painless progressive jaundice, dark urine, pale stools, and 8 kg weight loss over 6 weeks. Bilirubin 320 µmol/L, ALP 680 U/L, CA 19-9 markedly elevated. CT shows a mass in the pancreatic head with dilated CBD. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Gallstone choledocholithiasis" },
      { label: "B", text: "Primary sclerosing cholangitis" },
      { label: "C", text: "Pancreatic adenocarcinoma" },
      { label: "D", text: "Ampullary carcinoma" },
      { label: "E", text: "Cholangiocarcinoma" },
    ],
    correctAnswer: "C",
    explanation: "Pancreatic head cancer: painless obstructive jaundice (Courvoisier's sign — palpable non-tender gallbladder), weight loss, dark urine, pale stools, elevated CA 19-9. 70–80% of pancreatic cancers are in the head. Only 15–20% are resectable (Whipple's procedure). Poor prognosis: median survival 6–12 months. Courvoisier's law: gallstone jaundice = contracted gallbladder; cancer = distended gallbladder.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "gi-022", topic: "Gastroenterology", subtopic: "IBS",
    stem: "A 30-year-old woman has 12 months of abdominal bloating, cramping, and alternating diarrhoea and constipation. Symptoms improve after defaecation. Examination and investigations (FBC, CRP, coeliac serology, stool MCS) are all normal. What is the diagnosis and initial management?",
    options: [
      { label: "A", text: "Ulcerative colitis — start 5-ASA" },
      { label: "B", text: "IBS — reassurance, dietary modification, low-FODMAP diet" },
      { label: "C", text: "Microscopic colitis — colonoscopy with biopsy" },
      { label: "D", text: "Small intestinal bacterial overgrowth — rifaximin" },
      { label: "E", text: "Coeliac disease — gluten-free diet empirically" },
    ],
    correctAnswer: "B",
    explanation: "IBS (Rome IV criteria): recurrent abdominal pain ≥1 day/week for 3 months, related to defaecation or change in frequency/form. Normal investigations exclude organic cause. First-line: reassurance, dietary advice (regular meals, reduce caffeine, alcohol, spicy food), low-FODMAP diet (effective in 70%). Pharmacotherapy: antispasmodics, loperamide for diarrhoea-predominant.",
    reference: "murtagh", difficulty: "easy",
  },
  {
    id: "gi-023", topic: "Gastroenterology", subtopic: "Upper GI Bleed",
    stem: "A 65-year-old man with peptic ulcer disease presents with haematemesis. After resuscitation, OGD shows a bleeding duodenal ulcer with visible vessel (Forrest IA). What endoscopic treatment is performed and what medication reduces rebleeding?",
    options: [
      { label: "A", text: "Injection sclerotherapy + H2 blocker" },
      { label: "B", text: "Dual haemostatic therapy (injection + thermal/clip) + high-dose IV PPI" },
      { label: "C", text: "Thermal coagulation alone + oral omeprazole" },
      { label: "D", text: "Injection adrenaline alone is sufficient" },
      { label: "E", text: "No endoscopic treatment — PPI alone" },
    ],
    correctAnswer: "B",
    explanation: "High-risk stigmata (Forrest I-II): active bleeding or non-bleeding visible vessel → dual endoscopic therapy (adrenaline injection + thermal/mechanical clip). Adrenaline alone has high rebleed rate. Post-endoscopy: high-dose IV PPI (omeprazole 80 mg bolus then 8 mg/hr infusion for 72h) reduces rebleeding by 50%. H. pylori eradication mandatory. NSAID/anticoagulant review.",
    reference: "amc", difficulty: "medium",
  },
];
