import type { MCQuestion } from "./questions";

export const psychiatryQuestions: MCQuestion[] = [
  {
    id: "psych-001", topic: "Psychiatry", subtopic: "Depression",
    stem: "A 42-year-old woman presents with 6 weeks of low mood, anhedonia, poor sleep, fatigue, poor concentration, and passive suicidal ideation. She has no prior psychiatric history. Physical examination and thyroid function are normal. What is the first-line treatment for moderate depression?",
    options: [
      { label: "A", text: "Cognitive behavioural therapy (CBT) alone" },
      { label: "B", text: "SSRI + CBT (combined therapy)" },
      { label: "C", text: "SSRI alone" },
      { label: "D", text: "Tricyclic antidepressant (amitriptyline)" },
      { label: "E", text: "Benzodiazepine for 4 weeks while mood improves" },
    ],
    correctAnswer: "B",
    explanation: "Moderate depression: combined SSRI + CBT has best evidence (superior to either alone). SSRI alone or CBT alone are each effective for mild-moderate depression. TCAs have equivalent efficacy but higher side effect and overdose risk — not first-line. Benzodiazepines should not be used as antidepressants. First-line SSRIs: sertraline, escitalopram, fluoxetine.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "psych-002", topic: "Psychiatry", subtopic: "Depression",
    stem: "A 38-year-old man on sertraline 100 mg/day for 6 weeks has partial response — mood 'somewhat better' but still not at baseline. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Switch to a different SSRI immediately" },
      { label: "B", text: "Optimise dose (increase to 200 mg) and reassess at 4 weeks" },
      { label: "C", text: "Add lithium augmentation" },
      { label: "D", text: "Add atypical antipsychotic (quetiapine)" },
      { label: "E", text: "Refer directly to psychiatrist" },
    ],
    correctAnswer: "B",
    explanation: "Partial SSRI response at 6 weeks with maximum dose not yet reached: increase to maximum dose (sertraline 200 mg). Allow 4 weeks at each dose change. If inadequate response after maximum dose → switch to another SSRI or SNRI. Augmentation (lithium, atypical antipsychotic, or combining with mirtazapine) is for treatment-resistant depression after ≥2 adequate trials.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-003", topic: "Psychiatry", subtopic: "Suicide Risk",
    stem: "A 28-year-old man presents to ED after an impulsive overdose of 20 paracetamol tablets 4 hours ago. He states he 'didn't really want to die', has social support, and expresses regret. After medical clearance, what is the priority in psychiatric assessment?",
    options: [
      { label: "A", text: "Discharge with GP follow-up letter" },
      { label: "B", text: "Comprehensive risk assessment: intent, plan, access to means, protective factors" },
      { label: "C", text: "Mandatory inpatient psychiatric admission" },
      { label: "D", text: "Commence antidepressant before discharge" },
      { label: "E", text: "Refer to social work only" },
    ],
    correctAnswer: "B",
    explanation: "After any overdose/self-harm: comprehensive psychiatric risk assessment is mandatory before any disposition decision. Assess: lethality of attempt, intent (wanted to die vs impulsive), current suicidal ideation, plan and access to means, mental state, social supports, precipitating factors, protective factors. Do NOT automatically admit all — risk-stratify. Safe discharge requires: safety plan, reduced access to means, follow-up arranged.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-004", topic: "Psychiatry", subtopic: "Psychosis",
    stem: "A 22-year-old man is brought by his parents. Over 4 weeks he has become increasingly suspicious, hearing voices commenting on his actions, and believes neighbours are conspiring against him. He has no insight. He has been using cannabis daily. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Substance-induced psychotic disorder (cannabis only)" },
      { label: "B", text: "Bipolar I disorder with psychotic features" },
      { label: "C", text: "Schizophreniform disorder (duration 1–6 months)" },
      { label: "D", text: "Brief psychotic disorder (<1 month)" },
      { label: "E", text: "Delusional disorder" },
    ],
    correctAnswer: "C",
    explanation: "Schizophreniform disorder: schizophrenia criteria met but duration 1–6 months. Positive symptoms: hallucinations (auditory 3rd person), persecutory delusions, disorganised thinking. Cannabis is a trigger but not sole cause (genetic vulnerability). Diagnosis provisional until 6 months — if persists → schizophrenia. Start antipsychotic: risperidone or olanzapine. Early intervention improves long-term outcome.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-005", topic: "Psychiatry", subtopic: "Bipolar",
    stem: "A 35-year-old woman with bipolar I disorder on lithium (level 0.7 mmol/L) presents with manic episode: elevated mood, decreased sleep, grandiosity, racing thoughts, spending all savings. She refuses admission. What is the most appropriate treatment?",
    options: [
      { label: "A", text: "Increase lithium dose" },
      { label: "B", text: "Add valproate + consider involuntary admission if no insight" },
      { label: "C", text: "Start antidepressant (SSRI)" },
      { label: "D", text: "Benzodiazepine alone for sedation" },
      { label: "E", text: "Discharge and review in 1 week" },
    ],
    correctAnswer: "B",
    explanation: "Acute mania: first-line is valproate or quetiapine (rapid-acting). Add short-term benzodiazepine for agitation/sleep. SSRIs can precipitate/worsen mania — avoid. Lithium effective for prevention but slow onset for acute episodes. If patient lacks insight and risk to self (financial ruin, sexual disinhibition) or others → consider involuntary admission under Mental Health Act. Immediate safety assessment critical.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-006", topic: "Psychiatry", subtopic: "Anxiety",
    stem: "A 32-year-old woman has generalised anxiety disorder (GAD) — persistent worry, muscle tension, sleep disturbance, and irritability for >6 months. First-line treatment has failed. What is the second-line pharmacotherapy for GAD?",
    options: [
      { label: "A", text: "Diazepam long-term" },
      { label: "B", text: "SNRI (venlafaxine or duloxetine)" },
      { label: "C", text: "Buspirone" },
      { label: "D", text: "Quetiapine low dose" },
      { label: "E", text: "Propranolol" },
    ],
    correctAnswer: "B",
    explanation: "GAD treatment: first-line SSRI (sertraline/escitalopram) + CBT. If SSRI fails → try SNRI (venlafaxine, duloxetine) which have strong evidence for GAD. Buspirone: modest evidence, slow onset. Benzodiazepines: only short-term use (2–4 weeks) — risk of dependence. Pregabalin: effective for GAD, particularly in comorbid depression/pain. Quetiapine: off-label, used in specialist settings.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-007", topic: "Psychiatry", subtopic: "PTSD",
    stem: "A 35-year-old male veteran presents with nightmares, flashbacks, hypervigilance, emotional numbing, and avoidance of triggers since returning from deployment 8 months ago. He has significant alcohol use to 'self-medicate'. What is first-line treatment for PTSD?",
    options: [
      { label: "A", text: "Benzodiazepines for sleep and anxiety" },
      { label: "B", text: "Trauma-focused CBT (TF-CBT) or EMDR" },
      { label: "C", text: "SSRI alone without psychotherapy" },
      { label: "D", text: "Propranolol to reduce physiological arousal" },
      { label: "E", text: "Residential rehabilitation for alcohol first" },
    ],
    correctAnswer: "B",
    explanation: "PTSD: first-line = trauma-focused psychological therapy (TF-CBT or EMDR — Eye Movement Desensitization and Reprocessing). Both have strong evidence from RCTs. SSRIs (sertraline, paroxetine) are first-line pharmacotherapy. Benzodiazepines not recommended in PTSD — worsen outcomes and increase substance use. Address comorbid alcohol use (often co-occurs), but trauma therapy should not be delayed.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-008", topic: "Psychiatry", subtopic: "Substance Use",
    stem: "A 40-year-old man presents requesting help to stop drinking. He drinks 10 standard drinks/day (>5 years). His AUDIT score is 26. He has morning shakes that resolve with a drink. He was admitted 2 years ago for withdrawal seizures. What is the most important consideration?",
    options: [
      { label: "A", text: "Start naltrexone for craving reduction" },
      { label: "B", text: "Medically supervised alcohol withdrawal — risk of seizures and delirium tremens" },
      { label: "C", text: "Abrupt cessation is safe if motivated" },
      { label: "D", text: "Refer to AA immediately" },
      { label: "E", text: "Thiamine 100 mg orally for 1 week" },
    ],
    correctAnswer: "B",
    explanation: "High-risk alcohol withdrawal (prior seizure, high daily intake, morning shakes = physiological dependence): managed medically, usually inpatient. Benzodiazepine (diazepam or chlordiazepoxide) prevents seizures and DTs. CIWA-Ar protocol for symptom-triggered dosing. IV/IM thiamine FIRST (100–200 mg TDS) before any glucose — prevents Wernicke encephalopathy. Delirium tremens peaks 48–72h after last drink — potentially fatal.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-009", topic: "Psychiatry", subtopic: "Schizophrenia",
    stem: "A 30-year-old man with schizophrenia is non-compliant with oral risperidone due to side effects and repeatedly relapses. His positive symptoms respond well to risperidone when taken. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Switch to clozapine" },
      { label: "B", text: "Depot (long-acting injectable) risperidone or paliperidone" },
      { label: "C", text: "Add an antidepressant" },
      { label: "D", text: "Increase oral dose to ensure compliance" },
      { label: "E", text: "Psychotherapy alone" },
    ],
    correctAnswer: "B",
    explanation: "Non-compliance is a leading cause of relapse in schizophrenia. Long-acting injectable (LAI/depot) antipsychotics eliminate daily compliance issue. Risperidone LAI (Risperdal Consta) or paliperidone palmitate (Invega Sustenna) monthly injection. Clozapine for treatment-resistant schizophrenia (failed ≥2 antipsychotics). Requires REMS monitoring for agranulocytosis.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-010", topic: "Psychiatry", subtopic: "Delirium",
    stem: "A 78-year-old man is 2 days post-hip replacement. The night nurses report he is confused, agitated, and pulling out his IV line. He is orientated to person only. His urine is cloudy. Temperature 37.8°C. WBC 14.5. What is the most likely diagnosis and initial management priority?",
    options: [
      { label: "A", text: "Dementia exacerbation — increase antipsychotic dose" },
      { label: "B", text: "Delirium — identify and treat underlying cause (UTI)" },
      { label: "C", text: "Sedation with haloperidol immediately" },
      { label: "D", text: "Restraints for patient safety" },
      { label: "E", text: "Psychiatric review for acute psychosis" },
    ],
    correctAnswer: "B",
    explanation: "Delirium: acute, fluctuating course, inattention, disorganised thinking/altered consciousness. Postoperative delirium common in elderly. Priority: identify and treat precipitating cause (infection, pain, medication, urinary retention, dehydration, hypoxia). UTI likely here. Non-pharmacological: reorientation, ensure glasses/hearing aids, maintain sleep-wake cycle, avoid restraints. Antipsychotics (haloperidol low dose) only for severe agitation threatening safety.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "psych-011", topic: "Psychiatry", subtopic: "Eating Disorders",
    stem: "A 16-year-old girl presents with weight 42 kg, height 165 cm (BMI 15.4). She has amenorrhoea, lanugo, dental erosions, parotid enlargement, and calluses on her knuckles (Russell's sign). What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Anorexia nervosa" },
      { label: "B", text: "Bulimia nervosa with AN features (mixed presentation)" },
      { label: "C", text: "ARFID (avoidant restrictive food intake disorder)" },
      { label: "D", text: "Anorexia nervosa — binge/purge subtype" },
      { label: "E", text: "Hypothyroidism" },
    ],
    correctAnswer: "D",
    explanation: "AN binge/purge subtype: low weight + purging behaviours (Russell's sign = calluses on knuckles from self-induced vomiting, dental erosions, parotid enlargement). AN restricting subtype: only restriction. Bulimia: normal weight (BMI >18.5) + binge-purge cycles. Medical risks of AN: refeeding syndrome (low K+, Mg2+, PO4 on refeeding), cardiac arrhythmias, bone loss. Multidisciplinary treatment; inpatient if BMI <14 or medical compromise.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "psych-012", topic: "Psychiatry", subtopic: "OCD",
    stem: "A 24-year-old woman has 3 hours/day checking door locks and stove (compulsions). She has recurrent thoughts of causing harm to her baby despite wanting no such thing (intrusive ego-dystonic thoughts). She is distressed. What is first-line treatment?",
    options: [
      { label: "A", text: "Psychodynamic psychotherapy" },
      { label: "B", text: "ERP (Exposure Response Prevention therapy) + high-dose SSRI" },
      { label: "C", text: "Clomipramine only" },
      { label: "D", text: "Reassurance that thoughts are normal" },
      { label: "E", text: "Report to child protection immediately" },
    ],
    correctAnswer: "B",
    explanation: "OCD: intrusive ego-dystonic thoughts (obsessions) + repetitive behaviours/mental acts (compulsions) to reduce anxiety. First-line: ERP (CBT with exposure and response prevention) ± high-dose SSRI (fluoxetine up to 60 mg, fluvoxamine, sertraline, paroxetine). Clomipramine (TCA) equally effective but worse side effect profile — use if SSRIs fail. Important: intrusive thoughts in OCD ≠ intent to harm — do not report to child protection without further assessment.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-013", topic: "Psychiatry", subtopic: "Personality Disorders",
    stem: "A 25-year-old woman presents after cutting her wrists in response to her boyfriend ending their relationship. She describes a pattern of intense unstable relationships, identity disturbance, chronic emptiness, and repeated self-harm. What is the diagnosis and evidence-based treatment?",
    options: [
      { label: "A", text: "Major depressive disorder — SSRI" },
      { label: "B", text: "Borderline personality disorder — Dialectical Behaviour Therapy (DBT)" },
      { label: "C", text: "Histrionic personality disorder — CBT" },
      { label: "D", text: "Bipolar II disorder — mood stabiliser" },
      { label: "E", text: "Schizotypal personality disorder — antipsychotic" },
    ],
    correctAnswer: "B",
    explanation: "BPD (DSM-5): 5 of 9 criteria including emotional instability, impulsivity, unstable relationships, identity disturbance, chronic emptiness, suicidal/self-harm behaviour. DBT (Dialectical Behaviour Therapy) has strongest evidence — reduces self-harm, suicidality, hospitalisation. Mentalization-Based Therapy (MBT) also effective. No pharmacotherapy specifically for BPD — treat comorbidities (depression, PTSD). Long-term therapeutic relationship crucial.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-014", topic: "Psychiatry", subtopic: "ADHD",
    stem: "A 32-year-old accountant presents with chronic difficulties with attention, organisation, forgetting appointments, and impulsivity since childhood. ADHD Adult Rating Scale is in the clinically significant range. He has no comorbid psychiatric illness. What is the first-line pharmacotherapy for adult ADHD?",
    options: [
      { label: "A", text: "Dexamphetamine (stimulant)" },
      { label: "B", text: "Methylphenidate (Ritalin)" },
      { label: "C", text: "Atomoxetine (non-stimulant)" },
      { label: "D", text: "Either methylphenidate or dexamphetamine — both are first-line" },
      { label: "E", text: "Bupropion" },
    ],
    correctAnswer: "D",
    explanation: "Adult ADHD: stimulants (methylphenidate or dexamphetamine) are equally first-line. Choice depends on patient preference, comorbidities, and formulary. Atomoxetine (SNRI): non-stimulant, second-line or preferred if substance use disorder/tics. Requires specialist (psychiatrist or paediatrician) for prescription of stimulants in Australia. Always combine with psychoeducation and organisational strategies.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "psych-015", topic: "Psychiatry", subtopic: "Somatoform",
    stem: "A 45-year-old woman presents with multiple unexplained physical symptoms: chronic pain, fatigue, headaches, and GI complaints for 5 years. All investigations are repeatedly normal. She has frequent ED visits and multiple specialist referrals. What is the diagnosis and most important management principle?",
    options: [
      { label: "A", text: "Factitious disorder — confront the patient" },
      { label: "B", text: "Somatic symptom disorder — validated via consistent GP, CBT, scheduled visits" },
      { label: "C", text: "Continue investigations until a cause is found" },
      { label: "D", text: "Refer to psychiatry and discharge from GP care" },
      { label: "E", text: "Start opioids for pain management" },
    ],
    correctAnswer: "B",
    explanation: "Somatic symptom disorder (DSM-5): physical symptoms + excessive thoughts/feelings/behaviours about symptoms, causing significant distress. Key management: one consistent GP (avoid multiple providers), regular scheduled visits (not crisis-driven), explore psychosocial context, CBT (most evidence), low-dose antidepressants for pain/mood, avoid unnecessary investigations and opioids. Maintain therapeutic relationship.",
    reference: "amc", difficulty: "medium",
  },
];
