import type { MCQuestion } from "./questions";

export const neurologyQuestions: MCQuestion[] = [
  {
    id: "neuro-001", topic: "Neurology", subtopic: "Stroke",
    stem: "A 70-year-old man presents with sudden onset right-sided weakness and expressive aphasia. CT head is normal. Onset was 90 minutes ago. BP 168/95. He is on warfarin (INR 1.6) for AF. What is the most appropriate management?",
    options: [
      { label: "A", text: "IV tPA (alteplase) is contraindicated due to warfarin" },
      { label: "B", text: "IV alteplase if INR <1.7, then consider mechanical thrombectomy" },
      { label: "C", text: "Mechanical thrombectomy only — no thrombolysis" },
      { label: "D", text: "Aspirin 300 mg loading dose" },
      { label: "E", text: "Heparin infusion for cardioembolic stroke" },
    ],
    correctAnswer: "B",
    explanation: "IV alteplase can be given if INR ≤1.7 (acceptable coagulation status). CT shows no haemorrhage. Time window: up to 4.5 hours for thrombolysis. CTA/MRI if thrombectomy candidate (large vessel occlusion). Do not give antiplatelet or anticoagulant within 24h of thrombolysis. Maintain BP <185/110 before thrombolysis.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "neuro-002", topic: "Neurology", subtopic: "Stroke",
    stem: "A 65-year-old woman presents with a TIA — 30-minute episode of right-sided arm weakness and slurred speech, now resolved. ABCD² score is 5. What is the most appropriate management?",
    options: [
      { label: "A", text: "Discharge with follow-up in 4 weeks" },
      { label: "B", text: "Admit for urgent investigation and dual antiplatelet therapy" },
      { label: "C", text: "Start aspirin and lifestyle advice only" },
      { label: "D", text: "Start warfarin immediately" },
      { label: "E", text: "MRI brain in 3 months" },
    ],
    correctAnswer: "B",
    explanation: "TIA is a medical emergency. Risk of early stroke after TIA is 10–20% at 7 days. ABCD² ≥4 = high risk. Admit for urgent investigation (MRI brain, carotid imaging, echo, ECG/Holter) and start dual antiplatelet (aspirin 300 mg + clopidogrel 300 mg loading for 21 days, then clopidogrel alone) or aspirin alone. Treat modifiable risk factors urgently.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-003", topic: "Neurology", subtopic: "Epilepsy",
    stem: "A 28-year-old woman with juvenile myoclonic epilepsy (JME) presents for medication review. She wants to start a family. She is on valproate 1000 mg/day with good seizure control. What is the most appropriate advice?",
    options: [
      { label: "A", text: "Continue valproate — most effective for JME and safe in pregnancy" },
      { label: "B", text: "Switch to lamotrigine or levetiracetam before conception" },
      { label: "C", text: "Stop all AEDs — seizure risk in pregnancy low" },
      { label: "D", text: "Reduce valproate dose by 50%" },
      { label: "E", text: "Switch to carbamazepine" },
    ],
    correctAnswer: "B",
    explanation: "Valproate in pregnancy: highest teratogenicity risk (neural tube defects 1–2%, facial dysmorphia, cognitive impairment — 'fetal valproate syndrome'). Must be avoided in women of childbearing potential unless no alternatives. Switch to lamotrigine or levetiracetam for JME preconceptually. Carbamazepine also teratogenic. All women on AEDs: high-dose folic acid 5 mg/day from pre-conception.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "neuro-004", topic: "Neurology", subtopic: "Epilepsy",
    stem: "A 25-year-old man has a first unprovoked generalised tonic-clonic seizure. MRI and EEG are normal. He is a truck driver. What is the most appropriate management regarding driving?",
    options: [
      { label: "A", text: "He may continue driving immediately" },
      { label: "B", text: "Cease commercial driving — may resume after 12 months seizure-free on treatment" },
      { label: "C", text: "Cease all driving for 3 months, then reassess" },
      { label: "D", text: "No driving restrictions for a first seizure" },
      { label: "E", text: "Driving restricted only if EEG is abnormal" },
    ],
    correctAnswer: "B",
    explanation: "Australian driving regulations (Austroads): after first unprovoked seizure — private vehicle: 6 months off driving (or 3 months if EEG/imaging normal and specialist review normal). Commercial/heavy vehicle (>4.5 tonne, bus): 12 months seizure-free + AED treatment confirmed effective. Mandatory reporting to licensing authority in most states.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-005", topic: "Neurology", subtopic: "Parkinson's Disease",
    stem: "A 68-year-old man presents with resting tremor (right hand, 'pill-rolling'), bradykinesia, and rigidity. He also has a festinant gait. Which pathological finding is characteristic of Parkinson's disease?",
    options: [
      { label: "A", text: "Tau protein deposits (neurofibrillary tangles)" },
      { label: "B", text: "TDP-43 aggregates" },
      { label: "C", text: "Alpha-synuclein Lewy bodies in substantia nigra" },
      { label: "D", text: "Prion protein plaques" },
      { label: "E", text: "SOD1 mutations in motor neurons" },
    ],
    correctAnswer: "C",
    explanation: "Parkinson's disease: alpha-synuclein aggregation → Lewy bodies in dopaminergic neurons of substantia nigra pars compacta → dopamine deficiency → striatal dysfunction. Motor features: TRAP (tremor, rigidity, akinesia/bradykinesia, postural instability). Resting tremor is the hallmark. Treatment: levodopa/carbidopa (gold standard), dopamine agonists (pramipexole), MAO-B inhibitors (selegiline).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-006", topic: "Neurology", subtopic: "Parkinson's Disease",
    stem: "A 72-year-old man with Parkinson's disease on levodopa/carbidopa develops visual hallucinations and delusions over 3 weeks. He remains well orientated. Which antipsychotic is MOST appropriate?",
    options: [
      { label: "A", text: "Haloperidol" },
      { label: "B", text: "Risperidone" },
      { label: "C", text: "Clozapine or quetiapine" },
      { label: "D", text: "Olanzapine" },
      { label: "E", text: "Prochlorperazine" },
    ],
    correctAnswer: "C",
    explanation: "Antipsychotics in Parkinson's: most typical and many atypical antipsychotics worsen Parkinsonism (dopamine blockade). Safe options: clozapine (most evidence, requires monitoring for agranulocytosis) or quetiapine (commonly used, fewer extrapyramidal effects). Avoid haloperidol, risperidone, olanzapine. Also consider: exclude Lewy body dementia, reduce levodopa dose, treat infections.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "neuro-007", topic: "Neurology", subtopic: "Multiple Sclerosis",
    stem: "A 30-year-old woman presents with an episode of right-sided optic neuritis (painful visual loss, reduced colour vision, RAPD). 6 months later she has an episode of limb paraesthesiae lasting 2 weeks. MRI brain shows 4 periventricular T2 lesions. What is the diagnosis?",
    options: [
      { label: "A", text: "Neuromyelitis optica (NMO)" },
      { label: "B", text: "Relapsing-remitting multiple sclerosis (RRMS)" },
      { label: "C", text: "Clinically isolated syndrome — not yet MS" },
      { label: "D", text: "Primary progressive MS" },
      { label: "E", text: "Conversion disorder" },
    ],
    correctAnswer: "B",
    explanation: "McDonald criteria for MS: ≥2 attacks disseminated in space (optic neuritis + limb symptoms) + time (6 months apart) + MRI showing dissemination in space and time. RRMS = most common (85%). NMO: anti-AQP4 antibody, optic neuritis + transverse myelitis. Treatment: high-dose IV methylprednisolone for acute relapse; disease-modifying therapy (interferons, natalizumab) to reduce relapses.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-008", topic: "Neurology", subtopic: "Headache",
    stem: "A 35-year-old woman has unilateral throbbing headaches lasting 4–72 hours, preceded by visual zigzag lines for 20 minutes, associated with nausea and photophobia. She has 4 attacks per month. What is the most appropriate prophylactic treatment?",
    options: [
      { label: "A", text: "Amitriptyline 10–25 mg nocte" },
      { label: "B", text: "Propranolol 40–80 mg BD" },
      { label: "C", text: "Topiramate 25–50 mg daily" },
      { label: "D", text: "Valproate 500 mg BD" },
      { label: "E", text: "Any of the above are appropriate first-line" },
    ],
    correctAnswer: "E",
    explanation: "Migraine prophylaxis (≥4 attacks/month, significant disability): first-line options include propranolol, topiramate, amitriptyline, or valproate (avoid valproate in women of childbearing age). Choice depends on comorbidities: propranolol if hypertension/anxiety, topiramate if obesity (weight loss), amitriptyline if depression/insomnia. CGRP antagonists (erenumab, fremanezumab) for refractory cases. Acute: triptans (sumatriptan).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-009", topic: "Neurology", subtopic: "Dementia",
    stem: "A 75-year-old man has a 2-year history of progressive memory loss, personality change, and getting lost. MMSE 18/30. MRI shows bilateral temporal-parietal atrophy. What is the most likely diagnosis and medication to slow progression?",
    options: [
      { label: "A", text: "Vascular dementia — aspirin and BP control" },
      { label: "B", text: "Alzheimer's disease — donepezil" },
      { label: "C", text: "Lewy body dementia — rivastigmine" },
      { label: "D", text: "Frontotemporal dementia — memantine" },
      { label: "E", text: "Normal pressure hydrocephalus — ventriculoperitoneal shunt" },
    ],
    correctAnswer: "B",
    explanation: "Alzheimer's disease: gradual onset, memory loss first (hippocampal), temporal-parietal atrophy, amyloid plaques + tau tangles. Treatment: cholinesterase inhibitors (donepezil, rivastigmine, galantamine) for mild-moderate AD — improve cognition, ADLs, behaviour modestly. Memantine (NMDA antagonist) for moderate-severe. Lewy body: fluctuating cognition + parkinsonism + visual hallucinations. FTD: personality/language first.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-010", topic: "Neurology", subtopic: "Neuropathy",
    stem: "A 55-year-old man with T2DM (HbA1c 9.2%) presents with burning pain and paraesthesiae in both feet, worse at night. Examination shows loss of vibration and proprioception in a stocking distribution. What is the diagnosis and first-line treatment for pain?",
    options: [
      { label: "A", text: "Peripheral vascular disease — vascular review" },
      { label: "B", text: "Diabetic peripheral neuropathy — pregabalin or duloxetine" },
      { label: "C", text: "Spinal stenosis — MRI lumbar spine" },
      { label: "D", text: "Hypothyroid neuropathy — TSH" },
      { label: "E", text: "B12 deficiency — B12 supplementation" },
    ],
    correctAnswer: "B",
    explanation: "Diabetic peripheral neuropathy: symmetric distal 'glove and stocking' pattern, small fibre (burning/pain) + large fibre (vibration/proprioception loss). Optimise glycaemic control. Neuropathic pain: duloxetine (SNRI, first-line) or pregabalin/gabapentin. Amitriptyline an alternative. Topical capsaicin or lidocaine for local pain. Screen for foot ulcers, falls risk.",
    reference: "amc", difficulty: "easy",
  },
  {
    id: "neuro-011", topic: "Neurology", subtopic: "Motor Neuron Disease",
    stem: "A 60-year-old man presents with progressive limb weakness, muscle wasting, fasciculations, and hyperreflexia. No sensory symptoms. He has slurred speech. Brain and spine MRI are normal. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Multiple sclerosis" },
      { label: "B", text: "Amyotrophic lateral sclerosis (ALS/MND)" },
      { label: "C", text: "Myasthenia gravis" },
      { label: "D", text: "Syringomyelia" },
      { label: "E", text: "Spinal cord compression" },
    ],
    correctAnswer: "B",
    explanation: "ALS/MND: combined upper (hyperreflexia, spasticity, upgoing plantar) + lower (fasciculations, wasting, weakness) motor neuron signs without sensory involvement. El Escorial criteria for diagnosis. Only disease-modifying drug: riluzole (extends survival 2–3 months). Multidisciplinary palliative approach. Bulbar involvement (dysarthria, dysphagia) = poor prognosis.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-012", topic: "Neurology", subtopic: "Meningitis",
    stem: "A 20-year-old woman presents with fever, severe headache, neck stiffness, and photophobia. She is confused. CSF shows: WBC 850 cells/µL (predominantly PMNs), protein 2.5 g/L, glucose 1.2 mmol/L (serum glucose 6.5). Gram stain shows Gram-negative diplococci. What organism is this?",
    options: [
      { label: "A", text: "Streptococcus pneumoniae" },
      { label: "B", text: "Neisseria meningitidis" },
      { label: "C", text: "Listeria monocytogenes" },
      { label: "D", text: "Haemophilus influenzae" },
      { label: "E", text: "Cryptococcus neoformans" },
    ],
    correctAnswer: "B",
    explanation: "Neisseria meningitidis: Gram-negative diplococci, predominantly in young adults, associated with non-blanching petechial rash. CSF bacterial meningitis: neutrophilia, high protein, low glucose (<0.5 serum glucose ratio). Treatment: IV benzylpenicillin or cefotaxime. Prophylaxis for contacts: rifampicin or ciprofloxacin. Meningococcal vaccine available. Listeria: elderly, immunosuppressed.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-013", topic: "Neurology", subtopic: "Guillain-Barré Syndrome",
    stem: "A 35-year-old man presents with ascending weakness over 4 days, starting in his legs. He had a Campylobacter gastroenteritis 2 weeks ago. Reflexes are absent. CSF shows albuminocytological dissociation (high protein, normal WBC). What is the diagnosis and treatment?",
    options: [
      { label: "A", text: "MS — high-dose methylprednisolone" },
      { label: "B", text: "GBS — IV immunoglobulin or plasmapheresis + monitor FVC" },
      { label: "C", text: "Hypokalemic periodic paralysis — IV potassium" },
      { label: "D", text: "Botulism — antitoxin" },
      { label: "E", text: "Spinal cord compression — urgent MRI and decompression" },
    ],
    correctAnswer: "B",
    explanation: "GBS: acute ascending flaccid paralysis, areflexia, post-infectious (Campylobacter, CMV, EBV, Zika). Albuminocytological dissociation hallmark. Nerve conduction: demyelinating (slowed conduction, conduction block). Treatment: IVIg 2 g/kg over 5 days OR plasmapheresis (equally effective). Steroids not effective. Monitor FVC — intubate if FVC <20 mL/kg or rapid decline.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-014", topic: "Neurology", subtopic: "Vertigo",
    stem: "A 50-year-old woman presents with episodic vertigo lasting 30–60 seconds, provoked by turning her head in bed or looking up. Dix-Hallpike test is positive on the right. No hearing loss or tinnitus. What is the diagnosis and treatment?",
    options: [
      { label: "A", text: "Ménière's disease — betahistine and low-salt diet" },
      { label: "B", text: "BPPV — Epley manoeuvre" },
      { label: "C", text: "Vestibular neuritis — prochlorperazine" },
      { label: "D", text: "Acoustic neuroma — MRI" },
      { label: "E", text: "Cerebellar stroke — urgent CT" },
    ],
    correctAnswer: "B",
    explanation: "BPPV: brief (seconds–minutes) positional vertigo, positive Dix-Hallpike (rotatory nystagmus), no hearing loss. Most common cause of vertigo. Caused by otolith crystals in semicircular canals. Treatment: Epley manoeuvre (particle repositioning) — 80% success rate, resolves immediately. Ménière's: episodic hearing loss + tinnitus + vertigo, lasting hours. Vestibular neuritis: continuous vertigo days-weeks, no hearing loss.",
    reference: "murtagh", difficulty: "easy",
  },
  {
    id: "neuro-015", topic: "Neurology", subtopic: "Spinal Cord",
    stem: "A 65-year-old man has progressively worsening leg weakness and difficulty walking. He has upper motor neuron signs in both legs (hyperreflexia, clonus, extensor plantar responses) and loss of proprioception. Bladder dysfunction is present. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Parkinson's disease" },
      { label: "B", text: "Cervical spondylotic myelopathy" },
      { label: "C", text: "Peripheral neuropathy" },
      { label: "D", text: "Bilateral hip osteoarthritis" },
      { label: "E", text: "Cauda equina syndrome" },
    ],
    correctAnswer: "B",
    explanation: "Cervical myelopathy: UMN signs in legs (spastic gait, hyperreflexia) + LMN signs in arms at level of compression + proprioception loss (posterior column) + bladder dysfunction. Most common non-traumatic cord disease in adults >55. Cervical spondylosis is the most common cause. Urgent MRI cervical spine. Surgical decompression to prevent progression.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-016", topic: "Neurology", subtopic: "Headache",
    stem: "A 55-year-old woman presents with severe unilateral periorbital pain with ipsilateral lacrimation, rhinorrhoea, and ptosis, occurring at the same time each day for 3 weeks. Pain lasts 45–90 minutes. What is this condition and treatment?",
    options: [
      { label: "A", text: "Migraine — sumatriptan" },
      { label: "B", text: "Cluster headache — 100% O2 + subcutaneous sumatriptan" },
      { label: "C", text: "Trigeminal neuralgia — carbamazepine" },
      { label: "D", text: "Temporal arteritis — steroids" },
      { label: "E", text: "Cavernous sinus thrombosis — anticoagulation" },
    ],
    correctAnswer: "B",
    explanation: "Cluster headache: severe unilateral periorbital pain + ipsilateral autonomic features (lacrimation, rhinorrhoea, ptosis, miosis, conjunctival injection). Attacks 15 min–3 hours, up to 8/day in clusters lasting weeks-months. Acute treatment: 100% high-flow O2 (inhaled 12–15 L/min for 15 min) and/or subcutaneous sumatriptan. Prophylaxis: verapamil (first-line). Prednisolone short course.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "neuro-017", topic: "Neurology", subtopic: "Status Epilepticus",
    stem: "A 40-year-old man has been seizing for 20 minutes. IV access established. He has already received lorazepam 4 mg without resolution. What is the next treatment?",
    options: [
      { label: "A", text: "Repeat lorazepam 4 mg IV" },
      { label: "B", text: "IV levetiracetam, valproate, or phenytoin (second-line)" },
      { label: "C", text: "Immediate general anaesthesia" },
      { label: "D", text: "IM midazolam" },
      { label: "E", text: "IV diazepam" },
    ],
    correctAnswer: "B",
    explanation: "Status epilepticus management: Benzodiazepines first-line (lorazepam IV, or IM midazolam if no IV access). After 2 benzodiazepine doses fail (refractory at 20 min): second-line IV AED — levetiracetam 60 mg/kg (max 4500 mg), valproate 40 mg/kg, or phenytoin 20 mg/kg (avoid in cardiac disease). If still seizing at 40 min → anaesthesia (thiopentone, propofol) with intubation.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "neuro-018", topic: "Neurology", subtopic: "Myasthenia Gravis",
    stem: "A 35-year-old woman presents with bilateral ptosis, diplopia, and fatigable proximal limb weakness that worsens at the end of the day. Tensilon (edrophonium) test is positive. AChR antibodies are detected. What is the standard treatment?",
    options: [
      { label: "A", text: "Neostigmine infusion only" },
      { label: "B", text: "Pyridostigmine (Mestinon) + immunosuppression (prednisolone/azathioprine)" },
      { label: "C", text: "Plasma exchange alone" },
      { label: "D", text: "Anticholinergics (atropine)" },
      { label: "E", text: "Thymectomy immediately without medication" },
    ],
    correctAnswer: "B",
    explanation: "MG: acetylcholine receptor antibodies block NMJ. Treatment: pyridostigmine (acetylcholinesterase inhibitor) for symptomatic relief + immunosuppression (prednisolone, azathioprine) for long-term. Thymectomy for non-elderly AChR+ generalised MG (improves remission rates). Plasma exchange or IVIg for myasthenic crisis. Avoid: aminoglycosides, beta-blockers, magnesium (worsen MG).",
    reference: "amc", difficulty: "medium",
  },
];
