import type { MCQuestion } from "./questions";

export const cardiovascularQuestions: MCQuestion[] = [
  {
    id: "cv-001", topic: "Cardiovascular", subtopic: "Atrial Fibrillation",
    stem: "A 72-year-old man is incidentally found to have an irregularly irregular pulse. ECG confirms AF. He has no prior history of stroke, hypertension, diabetes or heart failure. His CHA₂DS₂-VASc score is 1 (age 65–74). What is the most appropriate management regarding anticoagulation?",
    options: [
      { label: "A", text: "Aspirin 100 mg daily" },
      { label: "B", text: "Warfarin targeting INR 2–3" },
      { label: "C", text: "Rivaroxaban 20 mg daily" },
      { label: "D", text: "No antithrombotic therapy — score too low" },
      { label: "E", text: "Anticoagulation decision based on shared decision-making" },
    ],
    correctAnswer: "E",
    explanation: "CHA₂DS₂-VASc = 1 in a male is a 'grey zone' — Australian guidelines recommend shared decision-making. Anticoagulation is not mandated but can be considered. For females with score 1, no therapy is recommended. Score ≥2 in males warrants anticoagulation.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-002", topic: "Cardiovascular", subtopic: "Atrial Fibrillation",
    stem: "A 65-year-old woman with hypertension and type 2 diabetes is found to have persistent AF. Her CHA₂DS₂-VASc score is 4. Which anticoagulant is preferred over warfarin according to current guidelines?",
    options: [
      { label: "A", text: "Aspirin + clopidogrel" },
      { label: "B", text: "Dabigatran, rivaroxaban, or apixaban (DOAC)" },
      { label: "C", text: "Warfarin only — DOACs not indicated in AF" },
      { label: "D", text: "Heparin infusion" },
      { label: "E", text: "No anticoagulation as she has hypertension" },
    ],
    correctAnswer: "B",
    explanation: "DOACs (dabigatran, rivaroxaban, apixaban, edoxaban) are preferred over warfarin for non-valvular AF with CHA₂DS₂-VASc ≥2 in females or ≥2 in males. They have equivalent/superior efficacy, less intracranial bleeding, and no need for INR monitoring.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-003", topic: "Cardiovascular", subtopic: "Atrial Fibrillation",
    stem: "A 55-year-old man with new-onset AF (duration unknown) presents to ED. BP 110/70, HR 140. He is haemodynamically stable. What is the most appropriate acute management?",
    options: [
      { label: "A", text: "Immediate DC cardioversion" },
      { label: "B", text: "IV digoxin for rate control" },
      { label: "C", text: "Anticoagulate then consider cardioversion at 4 weeks if duration unknown" },
      { label: "D", text: "Rate control with IV metoprolol or diltiazem" },
      { label: "E", text: "Amiodarone infusion immediately" },
    ],
    correctAnswer: "D",
    explanation: "For haemodynamically stable AF with unknown duration, initial priority is rate control (target HR <110 at rest). IV metoprolol or diltiazem are first-line. If duration unknown >48h, anticoagulate for 3-4 weeks before elective cardioversion (or TOE-guided cardioversion). Immediate cardioversion only for haemodynamic compromise.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-004", topic: "Cardiovascular", subtopic: "Heart Failure",
    stem: "A 68-year-old woman with HFrEF (EF 30%) is optimally treated with ACEi, beta-blocker, and spironolactone. Her eGFR is 55 and potassium is 4.8. Which additional medication has the strongest evidence to reduce mortality?",
    options: [
      { label: "A", text: "Digoxin" },
      { label: "B", text: "Ivabradine" },
      { label: "C", text: "Sacubitril-valsartan (ARNI)" },
      { label: "D", text: "SGLT2 inhibitor (empagliflozin or dapagliflozin)" },
      { label: "E", text: "Nitrates + hydralazine" },
    ],
    correctAnswer: "C",
    explanation: "Sacubitril-valsartan (ARNI) replaces ACEi/ARB in symptomatic HFrEF and reduces mortality by 20% (PARADIGM-HF). Replace ACEi with sacubitril-valsartan if tolerated. SGLT2i are also now recommended in HFrEF but the question asks about the 'strongest evidence to reduce mortality' in addition to current therapy — ARNI is the answer here.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-005", topic: "Cardiovascular", subtopic: "Heart Failure",
    stem: "A 75-year-old man presents with bilateral ankle oedema, orthopnoea, and exertional dyspnoea. CXR shows cardiomegaly and bilateral pleural effusions. BNP is 850 ng/L. Echo shows EF 55%. What is the diagnosis?",
    options: [
      { label: "A", text: "Heart failure with reduced ejection fraction (HFrEF)" },
      { label: "B", text: "Heart failure with preserved ejection fraction (HFpEF)" },
      { label: "C", text: "Constrictive pericarditis" },
      { label: "D", text: "Nephrotic syndrome" },
      { label: "E", text: "Liver cirrhosis with ascites" },
    ],
    correctAnswer: "B",
    explanation: "HFpEF: clinical HF with EF ≥50%. Common in elderly, hypertensive women. Treatment focuses on symptom management (diuretics), BP control, rate control. No proven mortality benefit from standard HFrEF medications. BNP >400 supports HF diagnosis.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-006", topic: "Cardiovascular", subtopic: "Aortic Stenosis",
    stem: "An 80-year-old man has severe aortic stenosis (valve area 0.8 cm²). He develops syncope on exertion. Echo shows EF 50%. What is the most appropriate management?",
    options: [
      { label: "A", text: "Start ACE inhibitor and monitor" },
      { label: "B", text: "Surgical aortic valve replacement (SAVR)" },
      { label: "C", text: "TAVI (transcatheter aortic valve implantation)" },
      { label: "D", text: "Balloon valvuloplasty as definitive therapy" },
      { label: "E", text: "Medical management with diuretics" },
    ],
    correctAnswer: "C",
    explanation: "Severe AS with symptoms (syncope, angina, dyspnoea) = class I indication for valve replacement. In an 80-year-old, TAVI is preferred over SAVR due to high surgical risk. TAVI is the standard for intermediate-high risk patients. Balloon valvuloplasty has high restenosis rate — not definitive.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-007", topic: "Cardiovascular", subtopic: "Hypertension",
    stem: "A 48-year-old man with hypertension (BP 155/95 on 2 occasions) has no end-organ damage. He has microalbuminuria on urine ACR. Which drug class is most appropriate as first-line?",
    options: [
      { label: "A", text: "Calcium channel blocker (amlodipine)" },
      { label: "B", text: "Beta-blocker (atenolol)" },
      { label: "C", text: "ACE inhibitor (perindopril)" },
      { label: "D", text: "Thiazide diuretic (indapamide)" },
      { label: "E", text: "Alpha-blocker (prazosin)" },
    ],
    correctAnswer: "C",
    explanation: "ACEi are first-line when microalbuminuria (ACR >2.5 in males, >3.5 in females) is present — they are renoprotective beyond BP lowering by reducing intraglomerular pressure. This applies especially to diabetic nephropathy but also non-diabetic CKD with proteinuria.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "cv-008", topic: "Cardiovascular", subtopic: "Hypertension",
    stem: "A 62-year-old man with hypertension has BP 170/100 despite maximum-dose amlodipine and perindopril. His potassium is 3.2 and aldosterone-renin ratio is elevated. What is the most likely diagnosis and next step?",
    options: [
      { label: "A", text: "White-coat hypertension — ambulatory BP monitoring" },
      { label: "B", text: "Primary aldosteronism — CT adrenals + adrenal vein sampling" },
      { label: "C", text: "Renal artery stenosis — Doppler ultrasound" },
      { label: "D", text: "Phaeochromocytoma — 24h urinary catecholamines" },
      { label: "E", text: "Essential hypertension — add third agent" },
    ],
    correctAnswer: "B",
    explanation: "Resistant hypertension + hypokalaemia + elevated aldosterone-renin ratio (ARR >30) = primary aldosteronism (Conn's syndrome). It is the most common cause of secondary hypertension. Confirm with fludrocortisone suppression test, then CT adrenals. Adrenal vein sampling differentiates unilateral (adenoma → surgery) from bilateral (hyperplasia → spironolactone).",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-009", topic: "Cardiovascular", subtopic: "Acute Coronary Syndrome",
    stem: "A 60-year-old man presents with 2 hours of central chest pain. ECG shows new LBBB. Troponin I is 0.8 µg/L (normal <0.04). What is the MOST appropriate immediate management?",
    options: [
      { label: "A", text: "Admit for observation and serial troponins" },
      { label: "B", text: "Aspirin + anticoagulation + urgent PCI" },
      { label: "C", text: "Aspirin + ticagrelor + thrombolysis" },
      { label: "D", text: "CT coronary angiography" },
      { label: "E", text: "Echo to assess wall motion abnormality" },
    ],
    correctAnswer: "B",
    explanation: "New LBBB + chest pain = STEMI equivalent. Requires urgent reperfusion — PCI within 90 minutes (primary PCI) is gold standard. Aspirin 300 mg + anticoagulation (heparin) + P2Y12 inhibitor (ticagrelor or prasugrel). Thrombolysis if PCI not available within 120 minutes.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-010", topic: "Cardiovascular", subtopic: "Acute Coronary Syndrome",
    stem: "A 55-year-old man with NSTEMI is treated with aspirin, ticagrelor, heparin, and statin. He undergoes PCI with drug-eluting stent. How long should dual antiplatelet therapy (DAPT) continue?",
    options: [
      { label: "A", text: "4 weeks" },
      { label: "B", text: "3 months" },
      { label: "C", text: "6 months" },
      { label: "D", text: "12 months" },
      { label: "E", text: "Lifelong" },
    ],
    correctAnswer: "D",
    explanation: "DAPT (aspirin + P2Y12 inhibitor) for 12 months post-ACS/PCI with drug-eluting stent — reduces stent thrombosis and recurrent ischaemic events. After 12 months, continue aspirin monotherapy lifelong. Shorter duration if high bleeding risk.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-011", topic: "Cardiovascular", subtopic: "Hypertension",
    stem: "A 45-year-old woman is found to have BP 145/92 on 3 occasions. She has no other risk factors. BMI 28, non-smoker. What is the 10-year cardiovascular risk using Framingham and appropriate first step?",
    options: [
      { label: "A", text: "High risk — start antihypertensives immediately" },
      { label: "B", text: "Lifestyle modification for 3–6 months, reassess" },
      { label: "C", text: "Start low-dose aspirin" },
      { label: "D", text: "Ambulatory BP monitoring to confirm diagnosis" },
      { label: "E", text: "Statin therapy is the priority" },
    ],
    correctAnswer: "D",
    explanation: "Before labelling hypertension, confirm with ambulatory BP monitoring (ABPM) or home BP monitoring (HBPM) — particularly when clinic BP is borderline. Stage 1 HT (140–159/90–99) in low-risk patients can be managed with lifestyle modification for 3–6 months before drug therapy if ABPM confirms elevation.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "cv-012", topic: "Cardiovascular", subtopic: "Cardiac Arrhythmia",
    stem: "A 25-year-old man presents with sudden palpitations and presyncope. ECG shows delta waves and a short PR interval. Which condition does this describe and what is the risk?",
    options: [
      { label: "A", text: "Long QT syndrome — risk of torsades de pointes" },
      { label: "B", text: "WPW syndrome — risk of rapid AF with VF degeneration" },
      { label: "C", text: "Brugada syndrome — risk of VF during fever" },
      { label: "D", text: "HOCM — risk of sudden death on exertion" },
      { label: "E", text: "First-degree heart block — benign, no risk" },
    ],
    correctAnswer: "B",
    explanation: "WPW (Wolff-Parkinson-White): delta wave + short PR + wide QRS due to accessory pathway (Bundle of Kent). Risk: pre-excited AF — impulses travel via accessory pathway → very rapid ventricular rate → VF and sudden death. Treatment: radiofrequency ablation. Avoid AV nodal blockers (digoxin, verapamil) in WPW-AF.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-013", topic: "Cardiovascular", subtopic: "Pericarditis",
    stem: "A 30-year-old man presents with sharp pleuritic chest pain relieved by leaning forward, fever, and a pericardial friction rub. ECG shows diffuse saddle-shaped ST elevation. What is the most likely diagnosis and first-line treatment?",
    options: [
      { label: "A", text: "STEMI — urgent PCI" },
      { label: "B", text: "Acute pericarditis — aspirin + colchicine" },
      { label: "C", text: "Aortic dissection — urgent CT angiography" },
      { label: "D", text: "Pulmonary embolism — anticoagulation" },
      { label: "E", text: "Myocarditis — steroids" },
    ],
    correctAnswer: "B",
    explanation: "Acute pericarditis: sharp positional pain + friction rub + diffuse concave (saddle-shaped) ST elevation + PR depression. First-line: aspirin 750–1000 mg TDS + colchicine 0.5 mg BD for 3 months (reduces recurrence by 50%). NSAIDs alternative. Restrict strenuous activity for 3 months.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-014", topic: "Cardiovascular", subtopic: "DVT/PE",
    stem: "A 35-year-old woman on OCP returns from a 20-hour flight with right calf pain and swelling. Wells score is 2 (moderate probability). D-dimer is elevated. What is the next appropriate step?",
    options: [
      { label: "A", text: "Treat empirically with LMWH — no further imaging needed" },
      { label: "B", text: "Compression ultrasound of the leg" },
      { label: "C", text: "CT pulmonary angiogram" },
      { label: "D", text: "Start warfarin immediately" },
      { label: "E", text: "Discharge with leg elevation and review in 48h" },
    ],
    correctAnswer: "B",
    explanation: "Wells score 2 = moderate probability. With elevated D-dimer, DVT cannot be excluded clinically. Compression duplex ultrasound is the gold-standard initial imaging for suspected DVT. If negative with high clinical suspicion, repeat in 7 days. OCP is a significant risk factor — withhold if DVT confirmed.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-015", topic: "Cardiovascular", subtopic: "DVT/PE",
    stem: "A 60-year-old man presents with pleuritic chest pain, hypoxia (SpO2 89%), HR 118, BP 88/60. CTPA confirms massive PE. What is the most important initial management step beyond oxygen and IV access?",
    options: [
      { label: "A", text: "LMWH (enoxaparin)" },
      { label: "B", text: "IV unfractionated heparin" },
      { label: "C", text: "Systemic thrombolysis (alteplase)" },
      { label: "D", text: "Surgical embolectomy" },
      { label: "E", text: "IVC filter insertion" },
    ],
    correctAnswer: "C",
    explanation: "Massive PE (haemodynamic instability: sustained hypotension or shock) = systemic thrombolysis is first-line if no absolute contraindications. Alteplase 100 mg over 2 hours. Surgical embolectomy or catheter-directed thrombolysis if thrombolysis contraindicated. UFH or LMWH alone insufficient for massive PE with shock.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-016", topic: "Cardiovascular", subtopic: "Infective Endocarditis",
    stem: "A 40-year-old IV drug user presents with fever, new pansystolic murmur, and splinter haemorrhages. Blood cultures grow Staphylococcus aureus. Which valve is MOST commonly affected in IVDU-related endocarditis?",
    options: [
      { label: "A", text: "Aortic valve" },
      { label: "B", text: "Mitral valve" },
      { label: "C", text: "Tricuspid valve" },
      { label: "D", text: "Pulmonary valve" },
      { label: "E", text: "Aortic + mitral together" },
    ],
    correctAnswer: "C",
    explanation: "IVDU endocarditis classically affects the tricuspid valve (right-sided endocarditis) — organisms injected IV travel directly to right heart. S. aureus is the most common pathogen. Presents with pulmonary septic emboli (multiple cavitating lesions on CXR). Left-sided endocarditis more common with structural heart disease.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-017", topic: "Cardiovascular", subtopic: "Cardiac Risk Factors",
    stem: "A 50-year-old male with T2DM, hypertension, and a 5-year history of smoking (20/day) presents for a check-up. His absolute 5-year CVD risk using the Australian CVD risk calculator is 18%. What is the most appropriate management?",
    options: [
      { label: "A", text: "Lifestyle advice only — medication not yet indicated" },
      { label: "B", text: "Start antihypertensive only" },
      { label: "C", text: "High-intensity statin + antihypertensive + lifestyle changes" },
      { label: "D", text: "Aspirin 100 mg daily" },
      { label: "E", text: "Refer to cardiologist" },
    ],
    correctAnswer: "C",
    explanation: "Absolute CVD risk ≥15% = high risk → both antihypertensive and statin therapy recommended regardless of individual BP/cholesterol levels (treat the overall risk). High-intensity statin (atorvastatin 40–80 mg). Aspirin not routinely recommended for primary prevention (net harm). Lifestyle modification always co-prescribed.",
    reference: "racgp-redbook", difficulty: "hard",
  },
  {
    id: "cv-018", topic: "Cardiovascular", subtopic: "Peripheral Arterial Disease",
    stem: "A 65-year-old smoker presents with calf pain on walking 200 m that resolves with rest. ABI is 0.65 bilaterally. What is this symptom called and first-line treatment?",
    options: [
      { label: "A", text: "Rest pain — urgent vascular surgery referral" },
      { label: "B", text: "Intermittent claudication — supervised exercise programme" },
      { label: "C", text: "Critical limb ischaemia — IV heparin" },
      { label: "D", text: "Venous claudication — compression stockings" },
      { label: "E", text: "Neurogenic claudication — spinal decompression" },
    ],
    correctAnswer: "B",
    explanation: "Intermittent claudication: calf pain on exertion, relieved by rest. ABI 0.4–0.9 = PAD. First-line: supervised exercise programme (30 min 3x/week) has strongest evidence for improving walking distance. Plus risk factor modification: smoking cessation, statin, antiplatelet, BP control. Cilostazol can be added. Revascularisation if lifestyle-limiting despite 3 months exercise.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-019", topic: "Cardiovascular", subtopic: "Abdominal Aortic Aneurysm",
    stem: "A 70-year-old male ex-smoker is found to have an AAA of 4.5 cm on ultrasound during a screening programme. He is asymptomatic. What is the most appropriate management?",
    options: [
      { label: "A", text: "Urgent surgical repair" },
      { label: "B", text: "Surveillance ultrasound every 3 months" },
      { label: "C", text: "Annual surveillance ultrasound" },
      { label: "D", text: "Endovascular repair (EVAR)" },
      { label: "E", text: "CT angiography to plan immediate repair" },
    ],
    correctAnswer: "C",
    explanation: "AAA management: <3cm = no surveillance; 3–3.9cm = every 3 years; 4–4.9cm = 12-monthly ultrasound; 5–5.4cm = 6-monthly; ≥5.5cm in males = consider repair. This patient has 4.5cm → annual surveillance. Repair threshold: ≥5.5cm males, ≥5.0cm females, or rapid expansion >1cm/year, or symptomatic.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-020", topic: "Cardiovascular", subtopic: "Aortic Dissection",
    stem: "A 55-year-old hypertensive man presents with sudden tearing chest pain radiating to his back. BP is 190/100 in the right arm and 160/90 in the left. CXR shows widened mediastinum. What is the immediate priority?",
    options: [
      { label: "A", text: "ECG and troponin" },
      { label: "B", text: "IV morphine and CT aorta with contrast" },
      { label: "C", text: "Immediate cardiac catheterisation" },
      { label: "D", text: "IV labetalol to reduce BP + urgent CT aorta" },
      { label: "E", text: "Thrombolysis for presumed STEMI" },
    ],
    correctAnswer: "D",
    explanation: "Aortic dissection: tearing pain, BP differential between arms, widened mediastinum. Immediate: IV labetalol (beta-blocker) to reduce dP/dt (target systolic 100–120). Then urgent CT aorta. Type A (ascending) = emergency surgery. Type B (descending) = medical management unless complications. Thrombolysis contraindicated — would cause haemorrhage.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-021", topic: "Cardiovascular", subtopic: "Cardiac Failure",
    stem: "A 60-year-old man with ischaemic cardiomyopathy (EF 25%) has recurrent VT despite optimal medical therapy. He is awaiting ICD. He presents with sustained VT causing hypotension. What is the most appropriate immediate treatment?",
    options: [
      { label: "A", text: "IV amiodarone bolus" },
      { label: "B", text: "IV lignocaine" },
      { label: "C", text: "Synchronised DC cardioversion" },
      { label: "D", text: "Unsynchronised defibrillation" },
      { label: "E", text: "IV adenosine" },
    ],
    correctAnswer: "C",
    explanation: "Haemodynamically unstable sustained VT (with pulse) → synchronised DC cardioversion. Unsynchronised shock (defibrillation) for VF or pulseless VT (part of CPR). Adenosine for SVT, not VT. Amiodarone/lignocaine are used for stable VT or post-cardioversion maintenance.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-022", topic: "Cardiovascular", subtopic: "Mitral Regurgitation",
    stem: "A 45-year-old woman is found to have moderate-severe mitral regurgitation. She is asymptomatic. Echo shows EF 62%, LV end-systolic diameter 40mm. What is the appropriate management?",
    options: [
      { label: "A", text: "Immediate surgical repair" },
      { label: "B", text: "ACE inhibitor to reduce afterload" },
      { label: "C", text: "Annual clinical and echo surveillance" },
      { label: "D", text: "Antibiotic prophylaxis for dental procedures" },
      { label: "E", text: "Diuretics to reduce preload" },
    ],
    correctAnswer: "C",
    explanation: "Asymptomatic MR with preserved LV function (EF >60%, LVESD <40mm) → watchful waiting with annual echo. Surgery indicated when: symptoms develop, EF <60%, or LVESD ≥40mm. ACEi not indicated in asymptomatic MR with normal LVEF. Antibiotic prophylaxis no longer recommended for MR (only for previous infective endocarditis).",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-023", topic: "Cardiovascular", subtopic: "Chest Pain",
    stem: "A 40-year-old woman presents with sharp chest pain reproducible on palpation of the chest wall, worsening on deep breathing. No risk factors for IHD. ECG normal, troponin negative. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "NSTEMI" },
      { label: "B", text: "Pulmonary embolism" },
      { label: "C", text: "Musculoskeletal chest pain (costochondritis)" },
      { label: "D", text: "Oesophageal spasm" },
      { label: "E", text: "Anxiety/panic disorder" },
    ],
    correctAnswer: "C",
    explanation: "Musculoskeletal chest pain: reproducible on palpation, positional, pleuritic, normal ECG/troponin. Costochondritis (Tietze syndrome) is common, benign. Treatment: NSAIDs, heat, reassurance. Always exclude cardiac and PE causes first, especially if risk factors present.",
    reference: "murtagh", difficulty: "easy",
  },
  {
    id: "cv-024", topic: "Cardiovascular", subtopic: "STEMI",
    stem: "A 50-year-old man is brought in with STEMI. The nearest PCI-capable centre is 3 hours away. His pain onset was 2 hours ago. What is the best reperfusion strategy?",
    options: [
      { label: "A", text: "Transfer immediately for primary PCI despite 3-hour delay" },
      { label: "B", text: "Thrombolysis now, then transfer for angiography within 24 hours" },
      { label: "C", text: "Medical management only — too late for reperfusion" },
      { label: "D", text: "Thrombolysis only — no need for subsequent PCI" },
      { label: "E", text: "Wait for troponin result before deciding" },
    ],
    correctAnswer: "B",
    explanation: "If primary PCI cannot be performed within 120 minutes of first medical contact, thrombolysis is indicated (within 12 hours of symptom onset). 'Pharmaco-invasive' strategy: thrombolyse, then transfer for angiography within 3–24 hours (or immediately if thrombolysis fails). This is current guideline recommendation when PCI delay >120 min.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-025", topic: "Cardiovascular", subtopic: "Hyperlipidaemia",
    stem: "A 55-year-old man has a fasting lipid profile: TC 7.2, LDL 4.8, HDL 0.9, TG 3.5 mmol/L. He has hypertension but no diabetes or prior CVD. His 5-year CVD risk is 12%. Which medication is most appropriate?",
    options: [
      { label: "A", text: "Ezetimibe monotherapy" },
      { label: "B", text: "Fibrate (gemfibrozil)" },
      { label: "C", text: "High-intensity statin (atorvastatin 40–80 mg)" },
      { label: "D", text: "Niacin" },
      { label: "E", text: "No medication — lifestyle only at this risk level" },
    ],
    correctAnswer: "C",
    explanation: "5-year CVD risk 10–15% = intermediate-high risk. High LDL 4.8 + multiple risk factors = statin indicated. High-intensity statin (atorvastatin 40–80 mg, rosuvastatin 20–40 mg) is first-line. Fibrates for isolated hypertriglyceridaemia (>5.6 mmol/L) or added to statin. Ezetimibe added if LDL target not met on statin.",
    reference: "racgp-redbook", difficulty: "medium",
  },
  {
    id: "cv-026", topic: "Cardiovascular", subtopic: "Hypertensive Emergency",
    stem: "A 58-year-old man presents with BP 220/130, headache, and blurred vision. Fundoscopy shows papilloedema. Creatinine has risen from 80 to 190 µmol/L. What is the target for BP reduction in the first hour?",
    options: [
      { label: "A", text: "Normalise BP immediately to <140/90" },
      { label: "B", text: "Reduce by 25% in the first hour, then gradually to 160/100 over 2–6 hours" },
      { label: "C", text: "Oral antihypertensives and review in 24 hours" },
      { label: "D", text: "Reduce to 120/80 within 2 hours" },
      { label: "E", text: "No treatment — auto-regulatory response will resolve" },
    ],
    correctAnswer: "B",
    explanation: "Hypertensive emergency (target organ damage): reduce MAP by no more than 25% in the first hour to avoid ischaemia from over-rapid reduction. Then target 160/100 over next 2–6 hours. Use IV labetalol, nitroprusside, or hydralazine. Too-rapid reduction → watershed infarcts, renal failure, blindness.",
    reference: "amc", difficulty: "hard",
  },
  {
    id: "cv-027", topic: "Cardiovascular", subtopic: "Acute Cardiac Tamponade",
    stem: "A trauma patient develops hypotension, muffled heart sounds, and raised JVP. BP is 80/60 and heart sounds are distant. ECG shows electrical alternans. What is the most likely diagnosis and immediate management?",
    options: [
      { label: "A", text: "Tension pneumothorax — needle decompression" },
      { label: "B", text: "Cardiac tamponade — pericardiocentesis" },
      { label: "C", text: "Haemothorax — chest drain" },
      { label: "D", text: "Aortic rupture — emergency surgery" },
      { label: "E", text: "Massive PE — thrombolysis" },
    ],
    correctAnswer: "B",
    explanation: "Beck's triad: hypotension + raised JVP + muffled heart sounds = cardiac tamponade. Electrical alternans (alternating QRS axis) on ECG is pathognomonic. Immediate pericardiocentesis (needle drainage) is life-saving. Tension pneumothorax has tracheal deviation and absent breath sounds — key differentiator.",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-028", topic: "Cardiovascular", subtopic: "Congenital Heart Disease",
    stem: "A 30-year-old woman is found to have a fixed splitting of S2 on routine examination. She has a soft ejection systolic murmur at the left upper sternal border. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Ventricular septal defect (VSD)" },
      { label: "B", text: "Atrial septal defect (ASD)" },
      { label: "C", text: "Patent ductus arteriosus (PDA)" },
      { label: "D", text: "Pulmonary stenosis" },
      { label: "E", text: "Aortic stenosis" },
    ],
    correctAnswer: "B",
    explanation: "ASD: fixed splitting of S2 (pathognomonic), ejection systolic murmur at pulmonary area due to increased flow, right heart dilation. Left-to-right shunt. Associations: Down syndrome. Complications: paradoxical embolism, Eisenmenger syndrome. Close if significant shunt (Qp:Qs >1.5).",
    reference: "amc", difficulty: "medium",
  },
  {
    id: "cv-029", topic: "Cardiovascular", subtopic: "Syncope",
    stem: "A 25-year-old man faints in a crowded shopping centre. He had prodromal nausea, pallor, and diaphoresis before losing consciousness for 30 seconds. Rapid recovery, no confusion. Normal ECG. What is the most likely cause?",
    options: [
      { label: "A", text: "Epileptic seizure" },
      { label: "B", text: "Vasovagal syncope" },
      { label: "C", text: "Orthostatic hypotension" },
      { label: "D", text: "Cardiac arrhythmia" },
      { label: "E", text: "Hypoglycaemia" },
    ],
    correctAnswer: "B",
    explanation: "Vasovagal syncope: most common cause in young patients. Triggered by prolonged standing, heat, crowding, fear, pain. Prodrome: nausea, pallor, diaphoresis. Brief loss of consciousness, rapid recovery, no post-ictal confusion. Normal ECG. Treatment: avoid triggers, increase salt/fluid intake, compression stockings, physical counter-pressure manoeuvres.",
    reference: "murtagh", difficulty: "easy",
  },
  {
    id: "cv-030", topic: "Cardiovascular", subtopic: "Bradyarrhythmias",
    stem: "A 70-year-old woman has frequent syncopal episodes. Holter monitor shows complete heart block (third-degree AV block). She is currently haemodynamically stable. What is the definitive management?",
    options: [
      { label: "A", text: "IV atropine long-term" },
      { label: "B", text: "Permanent pacemaker implantation" },
      { label: "C", text: "Beta-blocker withdrawal if applicable" },
      { label: "D", text: "Digoxin therapy" },
      { label: "E", text: "Watchful waiting with Holter monitoring" },
    ],
    correctAnswer: "B",
    explanation: "Complete (third-degree) heart block with symptoms (syncope, presyncope, heart failure) = class I indication for permanent pacemaker. Temporary pacing for acute management if haemodynamically unstable. Atropine for temporary stabilisation only. The underlying cause (ischaemia, drugs, infiltration) should also be addressed.",
    reference: "amc", difficulty: "easy",
  },
,
  {
    id: "cv-b2-001",
    topic: "Cardiovascular",
    subtopic: "Atrial Fibrillation",
    stem: "A 72-year-old man presents to his GP with a 3-day history of palpitations and mild dyspnoea. He has a background of hypertension and type 2 diabetes. ECG shows absent P waves with an irregularly irregular rhythm at 110 bpm. His CHA₂DS₂-VASc score is calculated to be 4. He has no contraindications to anticoagulation. What is the most appropriate initial management for stroke prevention?",
    options: [
      { label: "A", text: "Aspirin 100 mg daily" },
      { label: "B", text: "Warfarin with target INR 2–3" },
      { label: "C", text: "Apixaban 5 mg twice daily" },
      { label: "D", text: "Clopidogrel 75 mg daily" },
      { label: "E", text: "No anticoagulation required at this score" },
    ],
    correctAnswer: "C",
    explanation: "This patient has a CHA₂DS₂-VASc score of 4 (age ≥65 = 1, hypertension = 1, diabetes = 1, male sex = 0, plus age 72 contributes via the age ≥75 category partially — reassessing: hypertension 1, diabetes 1, age 65–74 = 1, male = 0, total = 3 minimum), which clearly exceeds the Australian threshold of ≥2 for men, mandating anticoagulation. Direct oral anticoagulants (DOACs) such as apixaban are now the preferred first-line agents over warfarin per the National Heart Foundation of Australia and Cardiac Society of Australia and New Zealand (NHFA/CSANZ) 2018 AF guidelines, due to superior safety profiles and non-inferiority in stroke prevention. Aspirin is no longer recommended for stroke prevention in AF as it has inadequate efficacy and similar bleeding risk to warfarin. Warfarin remains acceptable if DOACs are contraindicated or not tolerated.",
    reference: "NHFA/CSANZ Atrial Fibrillation Guidelines 2018; Therapeutic Guidelines Cardiovascular",
    difficulty: "easy",
  },
  {
    id: "cv-b2-002",
    topic: "Cardiovascular",
    subtopic: "Heart Failure",
    stem: "A 65-year-old woman with known ischaemic cardiomyopathy (EF 30%) is on optimal medical therapy including carvedilol 25 mg twice daily, ramipril 10 mg daily, and spironolactone 25 mg daily. She remains in NYHA class III despite this regimen. Her QRS duration on ECG is 155 ms with left bundle branch block morphology. Her renal function and electrolytes are within normal limits. What is the most appropriate next step in management?",
    options: [
      { label: "A", text: "Increase spironolactone to 50 mg daily" },
      { label: "B", text: "Add digoxin 125 mcg daily" },
      { label: "C", text: "Refer for cardiac resynchronisation therapy (CRT)" },
      { label: "D", text: "Add ivabradine if heart rate >70 bpm in sinus rhythm" },
      { label: "E", text: "Switch ramipril to sacubitril/valsartan" },
    ],
    correctAnswer: "C",
    explanation: "This patient meets the indications for cardiac resynchronisation therapy (CRT): EF ≤35%, NYHA class III, QRS duration ≥150 ms with LBBB morphology, despite optimal medical therapy. CRT has been shown to reduce mortality, hospitalisation, and improve symptoms in this population. Sacubitril/valsartan (option E) is also an important consideration in HFrEF but is contraindicated within 36 hours of ACE inhibitor use and requires a transition period; however, CRT addresses the mechanical dyssynchrony which is the primary issue here with a QRS of 155 ms LBBB. Ivabradine is appropriate for sinus rhythm with HR >70 bpm on maximal beta-blocker dose, but CRT takes precedence given the structural indication. Australian Heart Foundation guidelines align with ESC recommendations endorsing CRT as Class I indication in this scenario.",
    reference: "NHFA/CSANZ Heart Failure Guidelines 2018; Therapeutic Guidelines Cardiovascular",
    difficulty: "medium",
  },
  {
    id: "cv-b2-003",
    topic: "Cardiovascular",
    subtopic: "STEMI/NSTEMI",
    stem: "A 58-year-old man presents to the emergency department with severe crushing central chest pain radiating to his left arm for 90 minutes. He is diaphoretic and pale. BP 95/60 mmHg, HR 110 bpm. ECG shows 3 mm ST elevation in leads II, III, and aVF with reciprocal ST depression in I and aVL. The nearest PCI-capable centre is 45 minutes away. He has no contraindications to thrombolysis. What is the most appropriate immediate management?",
    options: [
      { label: "A", text: "Transfer immediately to PCI centre without thrombolysis" },
      { label: "B", text: "Administer tenecteplase and transfer for rescue PCI if needed" },
      { label: "C", text: "Administer tenecteplase and discharge once stable" },
      { label: "D", text: "Commence heparin infusion and urgent cardiology review" },
      { label: "E", text: "Administer aspirin and nitrates, await cardiology review" },
    ],
    correctAnswer: "A",
    explanation: "This patient has an inferior STEMI requiring urgent reperfusion. Current Australian guidelines (NHFA/CSANZ) recommend primary PCI as the preferred reperfusion strategy if it can be achieved within 120 minutes of first medical contact (door-to-balloon time). With a 45-minute transfer time, primary PCI is achievable well within this window, making immediate transfer to a PCI-capable centre the most appropriate management. Thrombolysis (pharmaco-invasive strategy) is indicated when PCI cannot be performed within 120 minutes of first medical contact. The patient requires loading doses of aspirin (300 mg) and a P2Y12 inhibitor (ticagrelor or prasugrel) prior to transfer, and heparin should be administered, but the primary decision is to pursue PCI.",
    reference: "NHFA/CSANZ STEMI Guidelines 2016; Therapeutic Guidelines Cardiovascular",
    difficulty: "easy",
  },
  {
    id: "cv-b2-004",
    topic: "Cardiovascular",
    subtopic: "Hypertension",
    stem: "A 48-year-old Aboriginal Australian man is found to have a blood pressure of 158/96 mmHg on three separate occasions over 6 weeks. He has no end-organ damage, no diabetes, and his cardiovascular risk score is 12% at 5 years. He is a non-smoker and BMI is 29 kg/m². Renal function and electrolytes are normal. He has no contraindications to medications. What is the most appropriate initial pharmacological management?",
    options: [
      { label: "A", text: "Amlodipine 5 mg daily" },
      { label: "B", text: "Metoprolol 50 mg twice daily" },
      { label: "C", text: "Perindopril 5 mg daily" },
      { label: "D", text: "Hydrochlorothiazide 25 mg daily" },
      { label: "E", text: "Spironolactone 25 mg daily" },
    ],
    correctAnswer: "A",
    explanation: "Aboriginal and Torres Strait Islander peoples have a higher prevalence of hypertension and cardiovascular disease. Australian guidelines (RACGP, Heart Foundation) recommend a lower threshold for pharmacological treatment in this population given their elevated cardiovascular risk. For the general hypertensive patient, first-line agents include ACE inhibitors, calcium channel blockers, or thiazide diuretics. However, ACE inhibitors (such as perindopril) are generally preferred in diabetes or CKD, while calcium channel blockers (amlodipine) are well-tolerated and effective first-line agents across all populations including Indigenous Australians. Beta-blockers are no longer considered first-line for uncomplicated hypertension per current Australian guidelines. Amlodipine is a reasonable first-line choice here given the patient's profile.",
    reference: "Heart Foundation Hypertension Guidelines 2016; RACGP Clinical Guidelines for Aboriginal and Torres Strait Islander Health",
    difficulty: "medium",
  },
  {
    id: "cv-b2-005",
    topic: "Cardiovascular",
    subtopic: "Valvular Disease",
    stem: "A 68-year-old woman presents with progressive exertional dyspnoea and pre-syncope over 6 months. On examination, she has a slow-rising carotid pulse, a narrow pulse pressure (110/90 mmHg), and a harsh ejection systolic murmur at the right upper sternal border radiating to the carotids. Echocardiography reveals an aortic valve area of 0.7 cm² and a mean gradient of 52 mmHg, with preserved LV systolic function (EF 60%). What is the most appropriate management?",
    options: [
      { label: "A", text: "Commence ACE inhibitor and reassess in 6 months" },
      { label: "B", text: "Aortic balloon valvuloplasty as definitive therapy" },
      { label: "C", text: "Surgical aortic valve replacement (SAVR)" },
      { label: "D", text: "Transcatheter aortic valve implantation (TAVI) as first choice regardless of surgical risk" },
      { label: "E", text: "Annual echocardiographic surveillance without intervention" },
    ],
    correctAnswer: "C",
    explanation: "This patient has severe aortic stenosis (AVA <1.0 cm², mean gradient >40 mmHg) with symptomatic presentation (dyspnoea and pre-syncope), which is a Class I indication for aortic valve replacement. In a 68-year-old with preserved LV function and no stated high surgical risk, surgical aortic valve replacement (SAVR) remains the standard of care. TAVI is the preferred option for high or prohibitive surgical risk patients, and has expanding indications into intermediate-risk patients, but SAVR is first-line for low-to-moderate surgical risk patients under 75 years. Balloon valvuloplasty is only a bridge to definitive therapy in haemodynamically unstable patients. Medical management does not alter the natural history of severe symptomatic AS.",
    reference: "Therapeutic Guidelines Cardiovascular; 2017 AHA/ACC Valvular Heart Disease Guidelines; NHFA position statement",
    difficulty: "medium",
  },
  {
    id: "cv-b2-006",
    topic: "Cardiovascular",
    subtopic: "Peripheral Arterial Disease",
    stem: "A 62-year-old male smoker with type 2 diabetes and hypertension presents with cramping pain in his right calf after walking 200 metres, which is relieved by rest. On examination, right foot pulses are absent and the ankle-brachial index (ABI) on the right is 0.55. He has no rest pain or tissue loss. What is the most appropriate initial management strategy?",
    options: [
      { label: "A", text: "Urgent surgical revascularisation" },
      { label: "B", text: "Supervised exercise program, smoking cessation, antiplatelet therapy, and statin" },
      { label: "C", text: "Warfarin anticoagulation to prevent arterial thrombosis" },
      { label: "D", text: "Refer for urgent vascular surgery review for amputation planning" },
      { label: "E", text: "Nifedipine for vasodilation and repeat ABI in 3 months" },
    ],
    correctAnswer: "B",
    explanation: "This patient has intermittent claudication representing Fontaine stage IIa/IIb peripheral arterial disease. The cornerstone of management for stable claudication (no rest pain, no tissue loss) is best medical therapy comprising supervised exercise rehabilitation (which improves walking distance), smoking cessation, antiplatelet therapy (aspirin or clopidogrel), and high-intensity statin therapy for cardiovascular risk reduction. These measures address both symptom management and the high cardiovascular event risk associated with PAD. Revascularisation is reserved for patients who fail conservative measures or develop critical limb ischaemia (rest pain, ulceration, gangrene — Fontaine III/IV). Warfarin is not indicated for PAD without additional indication. Calcium channel blockers have no established role in PAD.",
    reference: "Therapeutic Guidelines Cardiovascular; Heart Foundation PAD Guidelines; RACGP",
    difficulty: "easy",
  },
  {
    id: "cv-b2-007",
    topic: "Cardiovascular",
    subtopic: "DVT/PE",
    stem: "A 34-year-old woman presents to the ED with sudden onset pleuritic chest pain and dyspnoea 10 days after a long-haul flight. She takes the combined oral contraceptive pill. HR 108 bpm, BP 118/76 mmHg, O₂ saturation 94% on room air. ECG shows sinus tachycardia. CT pulmonary angiography confirms bilateral pulmonary emboli. She has no contraindications to anticoagulation. What is the most appropriate anticoagulation regimen?",
    options: [
      { label: "A", text: "Unfractionated heparin infusion followed by warfarin for 3 months" },
      { label: "B", text: "Rivaroxaban 15 mg twice daily for 21 days, then 20 mg daily for at least 3 months" },
      { label: "C", text: "Fondaparinux 7.5 mg subcutaneously daily for 3 months" },
      { label: "D", text: "Aspirin 300 mg loading then 100 mg daily for 6 months" },
      { label: "E", text: "Low molecular weight heparin for 10 days then no further anticoagulation" },
    ],
    correctAnswer: "B",
    explanation: "This haemodynamically stable patient with confirmed PE should be commenced on anticoagulation. DOACs are now the preferred first-line treatment for PE in non-pregnant patients without severe renal impairment, as recommended by Australian guidelines (Therapeutic Guidelines, NHFA). Rivaroxaban as a single-drug approach (15 mg BD for 21 days, then 20 mg daily) is well-validated and avoids the need for parenteral anticoagulation bridging. The minimum treatment duration for a provoked PE (OCP + long-haul flight) is 3 months, after which risk-benefit reassessment is performed. The OCP should be ceased. Warfarin remains an acceptable alternative but requires bridging and INR monitoring. Aspirin has no role in acute PE treatment.",
    reference: "Therapeutic Guidelines Cardiovascular; Australian Commission on Safety and Quality in Health Care VTE Prevention Guidelines 2020",
    difficulty: "easy",
  },
  {
    id: "cv-b2-008",
    topic: "Cardiovascular",
    subtopic: "Arrhythmias",
    stem: "A 28-year-old woman presents with recurrent episodes of sudden onset palpitations lasting 20–30 minutes with abrupt termination. Episodes are associated with mild dyspnoea but no syncope. ECG during an episode shows a narrow complex regular tachycardia at 180 bpm. Vagal manoeuvres in the ED terminate the tachycardia, revealing a normal ECG with no delta waves. She has had four episodes in the past year. What is the most appropriate long-term management?",
    options: [
      { label: "A", text: "Long-term flecainide therapy" },
      { label: "B", text: "Long-term metoprolol or verapamil for rate control" },
      { label: "C", text: "Electrophysiology study and radiofrequency catheter ablation" },
      { label: "D", text: "Implantable loop recorder for diagnosis confirmation" },
      { label: "E", text: "Reassurance and teaching vagal manoeuvres only" },
    ],
    correctAnswer: "C",
    explanation: "This patient has recurrent symptomatic SVT (most likely AVNRT given narrow complex, regular, vagal-responsive tachycardia with normal sinus ECG and no pre-excitation). In a young patient with frequent symptomatic episodes significantly impacting quality of life, electrophysiology study with radiofrequency catheter ablation is the most appropriate long-term management, offering a cure rate of >95% with low complication rates. This is preferred over lifelong pharmacological therapy in young patients with recurrent SVT per Therapeutic Guidelines and NHFA recommendations. Medical therapy (beta-blockers, verapamil, or flecainide as 'pill-in-the-pocket') is an alternative for patients who decline ablation or have infrequent episodes. Reassurance alone is insufficient given the frequency and impact of episodes.",
    reference: "Therapeutic Guidelines Cardiovascular; 2019 ESC SVT Guidelines; NHFA",
    difficulty: "medium",
  },
  {
    id: "cv-b2-009",
    topic: "Cardiovascular",
    subtopic: "Cardiomyopathy",
    stem: "A 22-year-old male athlete collapses during a football match and is successfully resuscitated from ventricular fibrillation. He reports a history of exertional presyncope over 6 months but had not sought medical attention. His father died suddenly at age 35. ECG shows left ventricular hypertrophy pattern. Echocardiography reveals asymmetric septal hypertrophy of 22 mm, systolic anterior motion of the mitral valve, and an LVOT gradient of 60 mmHg at rest. What is the most important next step in management?",
    options: [
      { label: "A", text: "Beta-blocker therapy and return to competitive sport after 3 months" },
      { label: "B", text: "Implantable cardioverter-defibrillator (ICD) insertion" },
      { label: "C", text: "Surgical myectomy as the first-line treatment" },
      { label: "D", text: "Cardiac MRI to confirm diagnosis before any intervention" },
      { label: "E", text: "Verapamil for LVOT obstruction and annual follow-up" },
    ],
    correctAnswer: "B",
    explanation: "This young man has hypertrophic cardiomyopathy (HCM) complicated by a life-threatening arrhythmic event (aborted sudden cardiac death from VF). ICD implantation is a Class I indication in survivors of cardiac arrest due to VF or sustained VT in the context of HCM, as this represents the highest risk category. This takes precedence over other interventions and is the most important immediate next step. Beta-blockers and surgical myectomy address symptoms of LVOT obstruction but do not primarily prevent sudden death in the post-arrest setting. Disqualification from competitive sport is also mandatory given the risk. Family screening with echocardiography and genetic testing is also required given the autosomal dominant inheritance pattern.",
    reference: "2014 ESC HCM Guidelines; Therapeutic Guidelines Cardiovascular; NHFA HCM Position Statement",
    difficulty: "medium",
  },
  {
    id: "cv-b2-010",
    topic: "Cardiovascular",
    subtopic: "Aortic Disease",
    stem: "A 70-year-old man with a history of hypertension and smoking presents with sudden onset severe tearing chest pain radiating to his back. BP is 180/100 mmHg in the right arm and 140/85 mmHg in the left arm. He is diaphoretic. CXR shows widened mediastinum. The aortic regurgitation murmur is audible. CT aortogram confirms a Type A aortic dissection involving the ascending aorta. What is the most appropriate definitive management?",
    options: [
      { label: "A", text: "Urgent blood pressure control with IV labetalol and medical management" },
      { label: "B", text: "Emergency surgical repair of the ascending aorta" },
      { label: "C", text: "Endovascular stent grafting (TEVAR)" },
      { label: "D", text: "Thrombolysis to restore perfusion to compromised branches" },
      { label: "E", text: "Transfer to a cardiac catheterisation laboratory for coronary angiography first" },
    ],
    correctAnswer: "B",
    explanation: "Stanford Type A aortic dissection (involving the ascending aorta) is a surgical emergency with a mortality of approximately 1–2% per hour without treatment. Emergency open surgical repair is the definitive treatment, as Type A dissections carry high risk of rupture, cardiac tamponade, aortic regurgitation, coronary occlusion, and stroke. Medical management with BP control is essential as a bridge to surgery but is not definitive — it is used for Type B dissections (not involving ascending aorta) that are uncomplicated. TEVAR is the treatment for Type B dissections. Thrombolysis is absolutely contraindicated. Coronary angiography would cause dangerous delay.",
    reference: "Therapeutic Guidelines Cardiovascular; 2014 ESC Aortic Diseases Guidelines; NHFA",
    difficulty: "easy",
  },
  {
    id: "cv-b2-011",
    topic: "Cardiovascular",
    subtopic: "Atrial Fibrillation",
    stem: "A 55-year-old man with known AF is brought to the ED with rapid AF at 145 bpm for the past 8 hours. BP is 105/70 mmHg and he is feeling faint. He is on apixaban 5 mg twice daily and his last dose was 12 hours ago. Echocardiogram in the ED shows no intracardiac thrombus. The treating team plans DC cardioversion. What is the most appropriate pre-cardioversion anticoagulation management?",
    options: [
      { label: "A", text: "Delay cardioversion for 4 weeks of therapeutic anticoagulation before proceeding" },
      { label: "B", text: "Proceed with DC cardioversion now given onset <48 hours and therapeutic anticoagulation confirmed" },
      { label: "C", text: "Administer IV heparin bolus then proceed with cardioversion" },
      { label: "D", text: "Cardioversion is contraindicated — rate control only is appropriate" },
      { label: "E", text: "Administer rivaroxaban 20 mg stat and wait 4 hours before cardioversion" },
    ],
    correctAnswer: "B",
    explanation: "When AF duration is clearly <48 hours and the patient is already on therapeutic anticoagulation (confirmed by recent apixaban dose), cardioversion can be performed immediately without the need for a 3–4 week period of pre-cardioversion anticoagulation or TOE to exclude LAA thrombus. The haemodynamic compromise (hypotension, near-syncope) makes urgent rhythm control the priority. Post-cardioversion anticoagulation for at least 4 weeks is mandatory due to risk of post-cardioversion atrial stunning and thrombus formation, regardless of subsequent rhythm. This approach is consistent with NHFA/CSANZ AF guidelines and Therapeutic Guidelines. Waiting 4 weeks is appropriate only when AF duration is ≥48 hours or unknown without TOE.",
    reference: "NHFA/CSANZ Atrial Fibrillation Guidelines 2018; Therapeutic Guidelines Cardiovascular",
    difficulty: "medium",
  },
  {
    id: "cv-b2-012",
    topic: "Cardiovascular",
    subtopic: "Heart Failure",
    stem: "A 78-year-old woman presents with 2 weeks of worsening dyspnoea and bilateral ankle oedema. She has no known cardiac history. Examination reveals elevated JVP, bibasal crackles, and pitting oedema to the knees. ECG shows sinus rhythm. BNP is 850 pg/mL. Echocardiography reveals LV ejection fraction of 62%, grade II diastolic dysfunction, left atrial enlargement, and mildly increased LV wall thickness. What is the most appropriate diagnosis?",
    options: [
      { label: "A", text: "Heart failure with reduced ejection fraction (HFrEF)" },
      { label: "B", text: "Heart failure with preserved ejection fraction (HFpEF)" },
      { label: "C", text: "Constrictive pericarditis" },
      { label: "D", text: "Hypertrophic cardiomyopathy with diastolic dysfunction" },
      { label: "E", text: "High-output cardiac failure" },
    ],
    correctAnswer: "B",
    explanation: "Heart failure with preserved ejection fraction (HFpEF) is defined as heart failure symptoms with an EF ≥50%, evidence of diastolic dysfunction, elevated filling pressures (reflected by elevated BNP and left atrial enlargement), and exclusion of other causes. This patient meets all criteria: symptoms and signs of fluid overload, EF 62%, grade II diastolic dysfunction, elevated BNP. HFpEF is particularly common in elderly women with hypertension and is increasingly recognised as a distinct entity. Management focuses on diuresis for congestion, treatment of comorbidities (hypertension, AF, diabetes), and exercise rehabilitation, as no therapy has been proven to reduce mortality in HFpEF. Constrictive pericarditis would show pericardial abnormalities on imaging.",
    reference: "NHFA/CSANZ Heart Failure Guidelines 2018; Therapeutic Guidelines Cardiovascular",
    difficulty: "medium",
  },
  {
    id: "cv-b2-013",
    topic: "Cardiovascular",
    subtopic: "STEMI/NSTEMI",
    stem: "A 65-year-old woman with hypertension and dyslipidaemia presents with 2 hours of central chest pain and diaphoresis. ECG shows 1.5 mm ST depression and T-wave inversion in V4–V6 and lateral leads. Troponin I at 3 hours is 0.45 ng/mL (reference <0.04 ng/mL). She is haemodynamically stable. She receives aspirin, ticagrelor, heparin, and atorvastatin. Her GRACE score is 145. What is the most appropriate next step in her management?",
    options: [
      { label: "A", text: "Coronary angiography within 24 hours (early invasive strategy)" },
      { label: "B", text: "Conservative strategy with exercise stress test prior to discharge" },
      { label: "C", text: "Immediate (within 2 hours) coronary angiography" },
      { label: "D", text: "Thrombolysis with tenecteplase" },
      { label: "E", text: "Coronary angiography within 72 hours only if symptoms recur" },
    ],
    correctAnswer: "A",
    explanation: "This patient has a high-risk NSTEMI (GRACE score ≥140 indicating high 6-month mortality risk, elevated troponin, dynamic ECG changes). Current Australian guidelines (NHFA/CSANZ NSTEACS Guidelines 2016) recommend an early invasive strategy (coronary angiography within 24 hours) for high-risk NSTEACS, as this reduces adverse cardiovascular events. Immediate angiography (within 2 hours, option C) is reserved for very high-risk features such as haemodynamic instability, refractory chest pain, life-threatening arrhythmias, or mechanical complications. Thrombolysis is contraindicated in NSTEMI/NSTEACS. Conservative management is only appropriate for low-risk presentations. The GRACE score ≥140 specifically stratifies this patient into the high-risk category requiring early angiography.",
    reference: "NHFA/CSANZ NSTEACS Guidelines 2016; Therapeutic Guidelines Cardiovascular",
    difficulty: "medium",
  },
  {
    id: "cv-b2-014",
    topic: "Cardiovascular",
    subtopic: "Hypertension",
    stem: "A 52-year-old woman presents to the ED with a severe headache and visual blurring. BP is 235/130 mmHg. Fundoscopy reveals papilloedema and flame haemorrhages. Creatinine is 185 µmol/L (baseline 90 µmol/L), and urinalysis shows 2+ protein and 2+ haematuria. Her urine pregnancy test is negative. She is drowsy but oriented. What is the most appropriate initial management target for blood pressure in the first hour?",
    options: [
      { label: "A", text: "Reduce BP to <120/80 mmHg immediately with IV nitroprusside" },
      { label: "B", text: "Reduce mean arterial pressure by no more than 25% in the first hour" },
      { label: "C", text: "Reduce BP to <140/90 mmHg within the first 24 hours with oral antihypertensives" },
      { label: "D", text: "Reduce BP to <160/100 mmHg over 24–48 hours with oral amlodipine" },
      { label: "E", text: "Administer sublingual nifedipine for rapid BP reduction" },
    ],
    correctAnswer: "B",
    explanation: "This patient has hypertensive emergency (hypertensive encephalopathy with end-organ damage — retinopathy, acute kidney injury, neurological symptoms). The key principle in managing hypertensive emergencies is to avoid overly rapid reduction in blood pressure, which can precipitate cerebral, coronary, or renal ischaemia due to impaired autoregulation. International and Australian guidelines recommend reducing MAP by no more than 25% in the first hour, targeting 160/100 mmHg over 2–6 hours, then normalising over 24–48 hours. IV agents such as labetalol, hydralazine, or nicardipine are preferred for controlled reduction. Sublingual nifedipine is dangerous due to unpredictable and rapid BP drops and is contraindicated. Aggressive immediate normalisation risks stroke or myocardial infarction.",
    reference: "Therapeutic Guidelines Cardiovascular; Heart Foundation Hypertension Guidelines; 2018 ESC/ESH Hypertension Guidelines",
    difficulty: "medium",
  },
  {
    id: "cv-b2-015",
    topic: "Cardiovascular",
    subtopic: "Valvular Disease",
    stem: "A 35-year-old woman who is 28 weeks pregnant presents with increasing dyspnoea on minimal exertion. She emigrated from India 5 years ago. On examination, there is a low-pitched mid-diastolic murmur at the apex with a loud S1 and an opening snap. HR is 95 bpm in atrial fibrillation. Echocardiography confirms severe mitral stenosis with MVA of 0.9 cm² and mean gradient of 14 mmHg, with no significant subvalvular disease. What is the most appropriate management?",
    options: [
      { label: "A", text: "Urgent caesarean section to relieve haemodynamic burden" },
      { label: "B", text: "Beta-blocker for rate control and anticoagulation with LMWH, reassess post-delivery" },
      { label: "C", text: "Percutaneous mitral balloon commissurotomy (PMBC)" },
      { label: "D", text: "Commence digoxin and warfarin and plan elective mitral valve replacement post-delivery" },
      { label: "E", text: "Urgent open mitral valve replacement during pregnancy" },
    ],
    correctAnswer: "C",
    explanation: "Severe symptomatic mitral stenosis in pregnancy is associated with significant maternal and fetal morbidity. This patient has haemodynamically severe MS (MVA <1.0 cm²) with symptoms at 28 weeks. In patients with favourable valve anatomy (no significant subvalvular disease, pliable leaflets, no MR) who remain symptomatic despite medical therapy, percutaneous mitral balloon commissurotomy (PMBC) is the procedure of choice during pregnancy — it can be performed from the second trimester with appropriate shielding to reduce fetal radiation exposure. Rate control with beta-blockers (metoprolol preferred — safe in pregnancy) and anticoagulation with LMWH (for AF) should be optimised, but definitive intervention is needed given MVA 0.9 cm². Open valve surgery carries high fetal mortality (15–30%) and is reserved for cases where PMBC fails. Caesarean section alone does not address the valvular pathology.",
    reference: "2018 ESC Guidelines on Valvular Heart Disease in Pregnancy; Therapeutic Guidelines Cardiovascular; NHFA",
    difficulty: "hard",
  },
  {
    id: "cv-b2-016",
    topic: "Cardiovascular",
    subtopic: "DVT/PE",
    stem: "A 45-year-old man presents with right calf pain and swelling for 5 days following a long-haul flight. Examination reveals right calf tenderness and mild erythema. His Wells score for DVT is 3 (high probability). D-dimer is elevated at 2.8 µg/mL. Duplex ultrasound confirms an isolated right popliteal vein DVT. He has no history of VTE, malignancy, or thrombophilia. He works in an office job. What is the most appropriate management?",
    options: [
      { label: "A", text: "Anticoagulation for 3 months with apixaban or rivaroxaban" },
      { label: "B", text: "Compression stockings alone — anticoagulation not indicated for distal DVT" },
      { label: "C", text: "Anticoagulation for 6 months with warfarin (INR 2–3)" },
      { label: "D", text: "Repeat ultrasound in 1 week — treat only if propagation to proximal veins" },
      { label: "E", text: "Thrombolysis due to the DVT burden" },
    ],
    correctAnswer: "A",
    explanation: "This patient has a confirmed proximal DVT (popliteal vein is classified as proximal, not distal/calf vein). Proximal DVT requires anticoagulation to prevent PE and thrombus propagation. Current Australian guidelines (Therapeutic Guidelines, ASTH) recommend 3 months of anticoagulation for a provoked proximal DVT (triggered by a transient risk factor — long-haul flight). DOACs (apixaban or rivaroxaban) are preferred first-line agents over warfarin due to ease of use, no INR monitoring, and comparable efficacy and safety. Note: the popliteal vein is proximal — distal DVTs (calf veins: peroneal, posterior tibial, muscular) have a different management algorithm. Thrombolysis is not indicated for uncomplicated DVT without phlegmasia.",
    reference: "Therapeutic Guidelines Cardiovascular; Australasian Society of Thrombosis and Haemostasis (ASTH) VTE Guidelines; ACCP 2016",
    difficulty: "medium",
  },
  {
    id: "cv-b2-017",
    topic: "Cardiovascular",
    subtopic: "Arrhythmias",
    stem: "A 58-year-old man is admitted following an episode of syncope. ECG shows a PR interval of 320 ms, and Holter monitor captures episodic complete heart block (CHB) with a ventricular escape rate of 35 bpm lasting several seconds, correlating with his syncopal episodes. He has no reversible causes (normal electrolytes, thyroid function, no offending medications). Echo shows normal LV function. What is the most appropriate management?",
    options: [
      { label: "A", text: "Cease beta-blockers and repeat Holter in 4 weeks" },
      { label: "B", text: "Permanent pacemaker implantation" },
      { label: "C", text: "Atropine 0.6 mg IV as long-term therapy" },
      { label: "D", text: "Theophylline for long-term chronotropic support" },
      { label: "E", text: "ICD implantation for sudden death prevention" },
    ],
    correctAnswer: "B",
    explanation: "This patient has symptomatic complete heart block (CHB) causing syncope with a slow escape rhythm, with no reversible cause identified. Permanent pacemaker (PPM) implantation is a Class I (Guideline Level A) indication in symptomatic complete heart block regardless of the underlying cause, per both Australian and international guidelines (Therapeutic Guidelines, 2018 ESC Pacing Guidelines). The choice of pacemaker mode depends on further evaluation but typically a dual-chamber (DDD) pacemaker is preferred to maintain AV synchrony. ICD is indicated for malignant ventricular arrhythmias causing cardiac arrest — CHB is a bradyarrhythmia not requiring ICD unless concurrent VT/VF is documented. Atropine is only a temporising measure in acute settings. There are no medications mentioned to cease.",
    reference: "Therapeutic Guidelines Cardiovascular; 2018 ESC Guidelines on Cardiac Pacing; NHFA",
    difficulty: "easy",
  },
  {
    id: "cv-b2-018",
    topic: "Cardiovascular",
    subtopic: "Cardiomyopathy",
    stem: "A 38-year-old woman presents with 3 months of progressive dyspnoea, orthopnoea, and peripheral oedema. She delivered her first child 8 weeks ago and had no cardiac history prior to pregnancy. Echocardiography reveals a globally dilated left ventricle with LVEF of 28% and no evidence of valvular disease or regional wall motion abnormalities. Coronary angiography is normal. Cardiac MRI shows diffuse gadolinium enhancement in a mid-myocardial pattern. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Postpartum hypertensive cardiomyopathy" },
      { label: "B", text: "Peripartum cardiomyopathy" },
      { label: "C", text: "Viral myocarditis" },
      { label: "D", text: "Familial dilated cardiomyopathy" },
      { label: "E", text: "Stress (Takotsubo) cardiomyopathy" },
    ],
    correctAnswer: "B",
    explanation: "Peripartum cardiomyopathy (PPCM) is defined as unexplained LV systolic dysfunction (EF <45%) presenting in the last month of pregnancy or within 5 months post-delivery, in the absence of pre-existing heart disease or identifiable cause. This patient fits the definition precisely: presentation 8 weeks post-partum, dilated LV with severely reduced EF, normal coronaries, and no prior cardiac history. The mid-myocardial gadolinium enhancement pattern on CMR is consistent with PPCM. Management follows HFrEF principles but with caution regarding teratogenic medications if breastfeeding (ACE inhibitors avoided during breastfeeding — use hydralazine/nitrates instead; bromocriptine may be considered to inhibit prolactin). Recovery of LV function occurs in approximately 50% of patients. Viral myocarditis is possible but the clinical context makes PPCM the primary diagnosis.",
    reference: "2019 ESC Position Statement on PPCM; NHFA Heart Failure Guidelines 2018; Therapeutic Guidelines",
    difficulty: "medium",
  },
  {
    id: "cv-b2-019",
    topic: "Cardiovascular",
    subtopic: "Peripheral Arterial Disease",
    stem: "A 75-year-old man with known PAD, type 2 diabetes, and hypertension presents with a 48-hour history of sudden onset severe right foot pain at rest, with pallor and paraesthesiae. His right foot is cold, pale, and pulseless. Motor function is intact. ABI cannot be obtained on the right. Urgent CT angiography reveals acute occlusion of the right popliteal artery. What is the most appropriate classification and initial management?",
    options: [
      { label: "A", text: "Rutherford Class I — commence best medical therapy and reassess in 24 hours" },
      { label: "B", text: "Rutherford Class IIa — urgent vascular surgery referral, systemic heparin, and catheter-directed thrombolysis or surgical embolectomy" },
      { label: "C", text: "Rutherford Class III — primary amputation without revascularisation attempt" },
      { label: "D", text: "Rutherford Class IIb — immediate surgical fasciotomy as first priority" },
      { label: "E", text: "Commence IV thrombolysis with alteplase without vascular surgery involvement" },
    ],
    correctAnswer: "B",
    explanation: "This patient has acute limb ischaemia (ALI). The Rutherford classification guides urgency: Class IIa (marginally threatened) is characterised by rest pain, sensory loss, no motor deficit, and an audible Doppler signal — requiring urgent intervention but limb viable for hours. This patient has rest pain, pallor, paraesthesiae, pulseless, cold foot, but intact motor function — consistent with Rutherford IIa/IIb. The critical distinction is intact motor function (IIa/IIb) vs. complete motor/sensory loss (Class III — irreversible). Initial management includes systemic anticoagulation with unfractionated heparin and urgent vascular surgery referral for catheter-directed thrombolysis, mechanical thrombectomy, or surgical embolectomy depending on cause and anatomy. Fasciotomy is performed post-revascularisation for compartment syndrome, not as initial treatment. Class III (irreversible ischaemia with fixed mottling, paralysis) requires amputation.",
    reference: "Therapeutic Guidelines Cardiovascular; SVS 2019 ALI Guidelines; NHFA PAD Guidelines",
    difficulty: "hard",
  },
  {
    id: "cv-b2-020",
    topic: "Cardiovascular",
    subtopic: "Aortic Disease",
    stem: "A 68-year-old male ex-smoker with hypertension attends for a routine health check. He is asymptomatic. Abdominal ultrasound performed for a different indication incidentally identifies an infrarenal abdominal aortic aneurysm measuring 4.2 cm in maximum diameter. BP is well-controlled at 128/78 mmHg on perindopril. He is otherwise well. What is the most appropriate management?",
    options: [
      { label: "A", text: "Refer for immediate endovascular aortic repair (EVAR)" },
      { label: "B", text: "Ultrasound surveillance every 12 months, optimise cardiovascular risk factors" },
      { label: "C", text: "CT angiography for operative planning and urgent surgical referral" },
      { label: "D", text: "Refer for open surgical repair given the patient's age and risk factors" },
      { label: "E", text: "Ultrasound in 3 years — no action required at this size" },
    ],
    correctAnswer: "B",
    explanation: "Abdominal aortic aneurysms (AAA) are managed based on size and symptoms. The threshold for elective repair in Australian practice (consistent with international guidelines) is ≥5.5 cm in men or ≥5.0 cm in women, rapid growth (>1 cm/year), or symptoms (pain, tenderness). This patient has a 4.2 cm asymptomatic AAA, which is below the intervention threshold. The most appropriate management is regular ultrasound surveillance (annual at 4.0–4.9 cm is standard) combined with optimisation of cardiovascular risk factors (smoking cessation — already achieved, BP control, antiplatelet therapy for cardiovascular risk reduction, statin therapy). Three-yearly surveillance is appropriate for smaller aneurysms (3.0–3.9 cm). Immediate repair is not indicated and carries unnecessary procedural risk below the threshold.",
    reference: "Therapeutic Guidelines Cardiovascular; Vascular Society of Australia and New Zealand (VSANZ) AAA Guidelines; NHFA",
    difficulty: "easy",
  }
];
