export interface RecallItem {
  number: number;
  title: string;
  tags: string[];
  tasks: string[];
}

export interface RecallMonth {
  month: string;
  year: number;
  category: "Medicine & Surgery" | "Psychiatry" | "Paediatrics" | "Counselling" | "PE";
  items: RecallItem[];
}

export const recalls: RecallMonth[] = [
  // ── MEDICINE & SURGERY ──────────────────────────────────────────────────────
  {
    month: "March",
    year: 2025,
    category: "Medicine & Surgery",
    items: [
      { number: 1,  title: "DVT post-flight", tags: ["Vascular","DVT","OCP"], tasks: ["Hx","PEFE","Dx","DDx"] },
      { number: 2,  title: "UTI in diabetic male on empagliflozin", tags: ["Urology","Diabetes","Pharmacology"], tasks: ["Hx","Dx","Mx"] },
      { number: 3,  title: "OSA — tiredness", tags: ["Respiratory","Sleep"], tasks: ["Hx","Dx","Mx"] },
      { number: 4,  title: "Malignant melanoma — explain biopsy report", tags: ["Dermatology","Oncology"], tasks: ["Counselling","Mx"] },
      { number: 5,  title: "Medication chart — tramadol + citalopram interaction, re-chart opioids with AMH", tags: ["Pharmacology","Prescribing"], tasks: ["Medication review","Re-chart"] },
      { number: 6,  title: "27yo palpitations — worried about heart attack, high coffee, FHx MI", tags: ["Cardiovascular","Psychiatry"], tasks: ["Hx","PEFE","Dx","Reassurance"] },
      { number: 7,  title: "Penile ulcer — MSM, painless, LN groin, photo given", tags: ["STI","Dermatology"], tasks: ["Hx","Dx","Mx"] },
      { number: 8,  title: "Urinary retention — BPH", tags: ["Urology"], tasks: ["Hx","PEFE","Dx"] },
      { number: 9,  title: "AKI — vomiting, HTN, CKD, gout, triple whammy", tags: ["Renal","Pharmacology"], tasks: ["Hx","Dx","Mx"] },
      { number: 10, title: "DM neuropathy — pins/needles, HbA1c >10, HTN, dyslipidaemia, EtOH", tags: ["Neurology","Diabetes"], tasks: ["PEFE","Dx","DDx","Mx"] },
      { number: 11, title: "Neck pain radiating to L arm — cervical radiculopathy", tags: ["Neurology","MSK"], tasks: ["Hx","Dx"] },
      { number: 12, title: "17yo unwell in rural — DKA", tags: ["Endocrinology","Emergency","Paediatrics"], tasks: ["Hx","PEFE","Dx"] },
      { number: 13, title: "27M abdominal pain + vomiting, EtOH history", tags: ["Gastroenterology","Alcohol"], tasks: ["Hx","Dx","DDx"] },
      { number: 14, title: "16M horse fall — CT findings, lower limb neuro exam", tags: ["Trauma","Neurology","Paediatrics"], tasks: ["PE","Neuro exam","Interpretation"] },
      { number: 15, title: "Heart failure — CVS exam, orthopnoea, discharge planning", tags: ["Cardiovascular"], tasks: ["PEFE","Discharge planning"] },
      { number: 16, title: "Eye pain/redness — bacterial conjunctivitis", tags: ["Ophthalmology"], tasks: ["Hx","Dx","DDx"] },
      { number: 17, title: "Post-lap chole — fever + crackles, Dx pneumonia, wants discharge", tags: ["Surgery","Respiratory"], tasks: ["Dx","Mx","Discharge"] },
      { number: 18, title: "Chest pain — biliary colic likely", tags: ["Gastroenterology","Cardiovascular"], tasks: ["Hx","Dx","DDx"] },
      { number: 19, title: "Tension headache", tags: ["Neurology"], tasks: ["Hx","Dx","Mx"] },
      { number: 20, title: "COPD — swelling legs, tiotropium/salbutamol/amlodipine, JVP+, hepatomegaly → heart failure", tags: ["Respiratory","Cardiovascular"], tasks: ["PEFE","Dx"] },
      { number: 21, title: "AF — explain Dx/Mx", tags: ["Cardiovascular"], tasks: ["Counselling","Mx"] },
      { number: 22, title: "Thyroid cancer — explain Ix/Mx", tags: ["Endocrinology","Oncology"], tasks: ["Counselling","Ix","Mx"] },
      { number: 23, title: "Haemoptysis — Hx/CT/Dx/DDx (bronchiectasis)", tags: ["Respiratory","Oncology"], tasks: ["Hx","Ix","Dx","DDx"] },
      { number: 24, title: "Leg pain — Dx/DDx (PAD)", tags: ["Vascular"], tasks: ["Hx","Dx","DDx"] },
      { number: 25, title: "Urinary problem — BPH, Hx/Dx with reasons", tags: ["Urology"], tasks: ["Hx","Dx"] },
      { number: 26, title: "Haemochromatosis — counselling, genetic risks & testing", tags: ["Gastroenterology","Genetics"], tasks: ["Counselling","Ix"] },
      { number: 27, title: "HIV male — fever, tachycardia, Hx/Dx/Ix", tags: ["Infectious Disease"], tasks: ["Hx","Dx","Ix"] },
      { number: 28, title: "Female neck lump — Hx/Dx/DDx", tags: ["Surgery","Endocrinology"], tasks: ["Hx","Dx","DDx"] },
      { number: 29, title: "OA knee — counsel on non-pharm + pharm with SE", tags: ["Rheumatology"], tasks: ["Counselling","Mx"] },
      { number: 30, title: "72F foot ulcer + fall, lives alone, refused aged care, psychosocial Mx", tags: ["Geriatrics","Diabetes","Social"], tasks: ["Psychosocial Hx","Mx plan"] },
      { number: 31, title: "Hypoglycaemia in diabetic", tags: ["Endocrinology","Emergency"], tasks: ["Dx","Mx"] },
      { number: 32, title: "Bowel obstruction — phone call, vomiting, no stool/urine, lives alone", tags: ["Surgery","Emergency"], tasks: ["Phone Mx"] },
      { number: 33, title: "Pneumonia — explain CXR to patient", tags: ["Respiratory"], tasks: ["Explain CXR","Counselling"] },
      { number: 34, title: "Tremor — Parkinsonism DDx", tags: ["Neurology"], tasks: ["Dx","DDx"] },
      { number: 35, title: "57F chest pain ×2h, pale & sweaty — ECG/Hx/PEFE/Dx", tags: ["Cardiovascular","Emergency"], tasks: ["Hx","PEFE","ECG","Dx","DDx"] },
    ],
  },
  {
    month: "April",
    year: 2025,
    category: "Medicine & Surgery",
    items: [
      { number: 1,  title: "ISBAR — call vascular reg for leaking AAA (ED resident)", tags: ["Vascular","Emergency","Communication"], tasks: ["ISBAR handover"] },
      { number: 2,  title: "Paracetamol OD — Hx, PEFE card, Ix", tags: ["Emergency","Pharmacology","Psychiatry"], tasks: ["Hx","PEFE","Ix"] },
      { number: 3,  title: "62F urinary symptoms — UA + PEFE given, Dx/DDx", tags: ["Urology"], tasks: ["Dx","DDx"] },
      { number: 4,  title: "Asthma counselling — Hx + education", tags: ["Respiratory"], tasks: ["Hx","Counselling","Education"] },
      { number: 5,  title: "Trigeminal neuralgia — MRI: vascular compression, carbamazepine started", tags: ["Neurology","Pharmacology"], tasks: ["Hx","Explain Mx","SE"] },
      { number: 6,  title: "Lymphedema post-mastectomy — swelling arm, on tamoxifen, no cancer signs", tags: ["Oncology","Surgery"], tasks: ["Dx","DDx","Ix","Mx"] },
      { number: 7,  title: "Pathological fracture — T5 fracture found, Hx, Dx, ? Surgery", tags: ["Oncology","Surgery"], tasks: ["Hx","Dx"] },
      { number: 8,  title: "Cellulitis — gardener, diabetic, leg red/ulcerated, photo", tags: ["Dermatology","Infectious Disease"], tasks: ["PE","Dx"] },
      { number: 9,  title: "RUQ pain — Murphy+, rebound+, PEFE given → PE, Dx", tags: ["Gastroenterology","Surgery"], tasks: ["PE","Dx"] },
      { number: 10, title: "Sleep disturbance — 52yo non-binary 'they', Hx + PEFE, Dx/DDx", tags: ["Psychiatry","Respiratory"], tasks: ["Hx","PEFE","Dx","DDx"] },
      { number: 11, title: "Tension headache — 30yo, stress at work", tags: ["Neurology","Psychiatry"], tasks: ["Hx","PEFE","Dx"] },
      { number: 12, title: "Headache — meningitis (Kernig & Brudzinski +ve)", tags: ["Neurology","Infectious Disease","Emergency"], tasks: ["Dx","Mx"] },
      { number: 13, title: "Medication chart — eGFR 60, dose adjustments", tags: ["Pharmacology","Renal"], tasks: ["Medication review","Prescribing"] },
      { number: 14, title: "Hereditary spherocytosis", tags: ["Haematology","Genetics"], tasks: ["Hx","Dx","Ix","Counselling"] },
      { number: 15, title: "Medication chart", tags: ["Pharmacology"], tasks: ["Medication review"] },
      { number: 16, title: "LLQ pain — diverticulitis", tags: ["Gastroenterology","Surgery"], tasks: ["Hx","Dx","Mx"] },
      { number: 17, title: "Triple whammy case — NSAID + ACEi + diuretic", tags: ["Pharmacology","Renal"], tasks: ["Medication review","Mx"] },
      { number: 18, title: "Coeliac disease", tags: ["Gastroenterology"], tasks: ["Hx","Ix","Dx","Mx"] },
      { number: 19, title: "Chest trauma — focused exam, Dx/DDx", tags: ["Emergency","Respiratory"], tasks: ["PE","Dx","DDx"] },
      { number: 20, title: "Middle-aged woman — abdominal pain + fever ×3w, jaundice, pale stool, post-lap chole", tags: ["Gastroenterology","Surgery"], tasks: ["Hx","PEFE","Ix"] },
      { number: 21, title: "Middle-aged woman — pain post 20km bike ride, hip tenderness → stress fracture", tags: ["MSK","Sports"], tasks: ["Dx with reason"] },
      { number: 22, title: "Hand exam — chef with trauma, explain XR, Dx/DDx", tags: ["MSK","Surgery"], tasks: ["PE","XR interpretation","Dx"] },
      { number: 23, title: "Recurrent falls — on prednisolone for PMR, urine +++ glucose → DM, falls risk", tags: ["Endocrinology","Geriatrics","Pharmacology"], tasks: ["Dx","Falls Mx"] },
      { number: 24, title: "Menorrhagia — 12mo, US normal, Hb 10, Dx: DUB, Mx", tags: ["Gynaecology"], tasks: ["Dx","Mx"] },
      { number: 25, title: "Facial pain — oral ulcer ×4w, white indurated edge → SCC DDx", tags: ["Dermatology","Oncology"], tasks: ["Dx","DDx"] },
      { number: 26, title: "Seizures — tonic-clonic 5mo ago, Hx febrile seizures, carbamazepine, driving licence advice", tags: ["Neurology","Legal"], tasks: ["Counselling","Legal advice"] },
      { number: 27, title: "Dizziness — 60F, post-URTI, TH crystal+, Hx, Dx/DDx", tags: ["ENT","Neurology"], tasks: ["Hx","Dx","DDx"] },
      { number: 28, title: "Gout recurrence — 50M, 5 flares in 18mo, stopped allopurinol", tags: ["Rheumatology"], tasks: ["Hx","triggers","Mx"] },
      { number: 29, title: "Weight gain — 50–60M, HbA1c 5.7, AST 54, TG 2.2 → NAFLD/metabolic syndrome", tags: ["Endocrinology","Gastroenterology"], tasks: ["Hx","Dx","DDx"] },
      { number: 30, title: "Pancreatitis — epigastric radiating to back, EtOH, fatty meal", tags: ["Gastroenterology"], tasks: ["Hx","Ix"] },
      { number: 31, title: "Dental abscess — 20M, poor dentition, on methadone", tags: ["Dentistry","Substance Use"], tasks: ["Hx","Dx","DDx"] },
      { number: 32, title: "OSA — 50M, snoring, HTN, PE, Dx", tags: ["Respiratory","Cardiovascular"], tasks: ["PE","Dx"] },
      { number: 33, title: "Foot exam — talar tilt+, Dx/DDx (ankle ligament injury)", tags: ["MSK","Sports"], tasks: ["PE","Dx","DDx"] },
      { number: 34, title: "SOB + cough — ACE inhibitor side effect", tags: ["Pharmacology","Respiratory"], tasks: ["Dx","Mx"] },
      { number: 35, title: "Haematuria — enlarged prostate, aspirin, travel", tags: ["Urology","Oncology"], tasks: ["Hx","Dx","DDx"] },
      { number: 36, title: "Functional neuropathy — stiff dorsiflexed ankle, normal sensation, exam", tags: ["Neurology"], tasks: ["PE","Dx"] },
    ],
  },
  {
    month: "May",
    year: 2025,
    category: "Medicine & Surgery",
    items: [
      { number: 1,  title: "Colle's fracture in cast — severe pain overnight, paracetamol not helping → compartment syndrome", tags: ["Surgery","Emergency","MSK"], tasks: ["Hx","PE","Dx","Mx"] },
      { number: 2,  title: "ISBAR handover — upper GI bleed, melaena, on diclofenac, Hb 100", tags: ["Gastroenterology","Emergency","Communication"], tasks: ["ISBAR handover"] },
      { number: 3,  title: "SOB + bilateral LL swelling — 67yo F, Hx, PE card, Dx", tags: ["Cardiovascular","Respiratory"], tasks: ["Hx","PE","Dx"] },
      { number: 4,  title: "Dark urine — 52yo F ×2wks, Hx, Dx/DDx", tags: ["Gastroenterology","Renal","Haematology"], tasks: ["Hx","Dx","DDx"] },
      { number: 5,  title: "Shakes — 52yo M, Hx, Dx/DDx (alcohol withdrawal vs essential tremor vs Parkinson's)", tags: ["Neurology","Alcohol"], tasks: ["Hx","Dx","DDx"] },
      { number: 6,  title: "Bike accident — rib fractures + lung contusion, discharge counselling", tags: ["Trauma","Respiratory"], tasks: ["Counselling","Discharge"] },
      { number: 7,  title: "Anal lump — picture + proctoscopy findings", tags: ["Surgery","Gastroenterology"], tasks: ["Dx","DDx"] },
      { number: 8,  title: "52yo M post-travel — nausea/vomiting, gastroenteritis", tags: ["Gastroenterology","Infectious Disease"], tasks: ["Hx","Dx"] },
      { number: 9,  title: "SCC biopsy result — explain implications & management", tags: ["Dermatology","Oncology"], tasks: ["Counselling","Mx"] },
      { number: 10, title: "DM patient — lipid report counselling", tags: ["Endocrinology","Cardiovascular"], tasks: ["Counselling"] },
      { number: 11, title: "MVA — GCS scoring (E2V3M3)", tags: ["Emergency","Neurology"], tasks: ["GCS","Neuro assessment"] },
      { number: 12, title: "55yo M palpitations → AF on ECG", tags: ["Cardiovascular"], tasks: ["Hx","ECG interpretation","Dx"] },
      { number: 13, title: "Young male smoker — submandibular lump, malignancy concern", tags: ["Surgery","Oncology","ENT"], tasks: ["Hx","Dx","DDx"] },
      { number: 14, title: "Burning feet — diabetic neuropathy", tags: ["Neurology","Endocrinology"], tasks: ["Hx","Dx","Mx"] },
      { number: 15, title: "Police-brought male — alcohol intoxication + MSE", tags: ["Psychiatry","Alcohol","Emergency"], tasks: ["Hx","MSE","Mx"] },
      { number: 16, title: "Young male — hip pain, overuse injury", tags: ["MSK","Sports"], tasks: ["Hx","Dx","DDx"] },
      { number: 17, title: "Abdominal pain — gallstones", tags: ["Gastroenterology","Surgery"], tasks: ["Hx","Dx"] },
      { number: 18, title: "Finger pain — RA vs psoriatic arthritis", tags: ["Rheumatology"], tasks: ["Hx","Dx","DDx"] },
      { number: 19, title: "Difficulty walking on anticoagulation — ? stroke", tags: ["Neurology","Cardiovascular"], tasks: ["Hx","Dx","Mx"] },
      { number: 20, title: "Red eyes — conjunctivitis, photo given", tags: ["Ophthalmology"], tasks: ["Dx","DDx","Mx"] },
      { number: 21, title: "Rectal bleeding — travel history, DRE, Ix", tags: ["Gastroenterology","Infectious Disease"], tasks: ["Hx","Ix","Dx"] },
      { number: 22, title: "Abdominal pain 36wk pregnant — Dx and Ix", tags: ["Obstetrics","Emergency"], tasks: ["Dx","Ix"] },
      { number: 23, title: "Smoker wants to quit — counselling", tags: ["Preventive","Respiratory"], tasks: ["Counselling"] },
      { number: 24, title: "SOB — Hx, Dx", tags: ["Respiratory","Cardiovascular"], tasks: ["Hx","Dx"] },
      { number: 25, title: "Abdominal exam — appendicitis", tags: ["Surgery","Gastroenterology"], tasks: ["PE","Dx"] },
      { number: 26, title: "Adolescent girl — painful leg, nodules on shin → erythema nodosum", tags: ["Dermatology","Rheumatology","Paediatrics"], tasks: ["Dx","DDx"] },
      { number: 27, title: "Acute otitis media", tags: ["ENT","Paediatrics","Infectious Disease"], tasks: ["Hx","Dx","Mx"] },
      { number: 28, title: "Child — FBA coin/battery ingestion", tags: ["Paediatrics","Emergency"], tasks: ["Hx","Mx"] },
      { number: 29, title: "EBV — child with hepatosplenomegaly", tags: ["Paediatrics","Infectious Disease","Haematology"], tasks: ["Hx","Dx","Ix"] },
      { number: 30, title: "Lumbar canal stenosis", tags: ["Neurology","MSK"], tasks: ["Hx","Dx","Mx"] },
      { number: 31, title: "RUQ pain, hepatomegaly, weight loss", tags: ["Gastroenterology","Oncology"], tasks: ["Hx","Dx","DDx"] },
    ],
  },
  {
    month: "June",
    year: 2025,
    category: "Medicine & Surgery",
    items: [
      { number: 1, title: "Right inguinal hernia — 50yo male, worse on standing, reduces lying", tags: ["Surgery"], tasks: ["Hx","PEFE","Dx","DDx"] },
      { number: 2, title: "Thunderclap headache — photophobia, vomiting, middle-aged male", tags: ["Neurology","Emergency"], tasks: ["Hx","Dx","DDx","Ix"] },
      { number: 3, title: "Wrist swelling post-fall — XR with scaphoid fracture", tags: ["MSK","Surgery"], tasks: ["Hx","PE","Dx","Mx"] },
      { number: 4, title: "Bilateral leg swelling — 60yo F on amlodipine, no SOB", tags: ["Cardiovascular","Pharmacology"], tasks: ["Hx","Dx","DDx"] },
      { number: 5, title: "Young male — chest pain on exertion, FHx sudden cardiac death", tags: ["Cardiovascular","Emergency"], tasks: ["Hx","PEFE","Dx","DDx"] },
    ],
  },

  // ── PSYCHIATRY ──────────────────────────────────────────────────────────────
  {
    month: "March–August",
    year: 2025,
    category: "Psychiatry",
    items: [
      { number: 1,  title: "Depression — 35F, low mood, anhedonia, insomnia, work stress", tags: ["Depression"], tasks: ["MSE","Hx","Dx","Mx"] },
      { number: 2,  title: "Panic disorder — 28M, palpitations, sweating, fear of dying", tags: ["Anxiety"], tasks: ["Hx","Dx","DDx","Mx"] },
      { number: 3,  title: "Psychosis — 22M, first episode, hearing voices, cannabis use", tags: ["Psychosis","Substance Use"], tasks: ["MSE","Hx","Dx","Mx"] },
      { number: 4,  title: "Suicidal ideation — 40F, recent job loss, Hx of depression", tags: ["Suicide","Depression"], tasks: ["Risk assessment","Mx"] },
      { number: 5,  title: "Bipolar disorder — 30M, elevated mood, grandiosity, decreased sleep", tags: ["Bipolar"], tasks: ["MSE","Hx","Dx","Mx"] },
      { number: 6,  title: "Dementia — 75M, memory loss, MMSE 18/30, family concerned", tags: ["Dementia","Geriatrics"], tasks: ["MSE","Cognitive assessment","Dx","Mx"] },
      { number: 7,  title: "Alcohol dependence — CAGE+ve, AUDIT score, withdrawal risk", tags: ["Alcohol","Substance Use"], tasks: ["Hx","Dx","Mx"] },
      { number: 8,  title: "OCD — 25F, hand washing, intrusive thoughts, 3 hours/day", tags: ["OCD"], tasks: ["Hx","Dx","Mx"] },
      { number: 9,  title: "PTSD — 38M, veteran, nightmares, hypervigilance, avoidance", tags: ["PTSD"], tasks: ["Hx","MSE","Dx","Mx"] },
      { number: 10, title: "Eating disorder — 17F, BMI 16, amenorrhoea, lanugo", tags: ["Eating Disorder","Paediatrics"], tasks: ["Hx","PE","Dx","Mx"] },
      { number: 11, title: "ADHD adult — 32M, difficulty concentrating at work, childhood history", tags: ["ADHD"], tasks: ["Hx","Dx","Mx"] },
      { number: 12, title: "Borderline PD — 26F, self-harm, unstable relationships, emotional dysregulation", tags: ["Personality Disorder"], tasks: ["Risk assessment","Mx"] },
      { number: 13, title: "Somatisation — 45F, multiple physical complaints, normal investigations", tags: ["Somatoform"], tasks: ["Hx","Dx","Mx"] },
      { number: 14, title: "Schizophrenia — non-compliance with antipsychotics, relapse prevention", tags: ["Schizophrenia"], tasks: ["Hx","Mx","Counselling"] },
      { number: 15, title: "May recalls — May Psychiatry Recalls 2025", tags: ["Psychiatry"], tasks: ["MSE","Hx","Dx","Mx"] },
    ],
  },

  // ── PAEDIATRICS ─────────────────────────────────────────────────────────────
  {
    month: "2025",
    year: 2025,
    category: "Paediatrics",
    items: [
      { number: 1,  title: "Febrile convulsion — 2yo, 5-min tonic-clonic, temperature 39.2", tags: ["Neurology","Fever"], tasks: ["Hx","Dx","Counselling"] },
      { number: 2,  title: "Failure to thrive — 9mo, weight below 3rd centile, feeding issues", tags: ["Nutrition","Development"], tasks: ["Hx","PE","Ix","Dx"] },
      { number: 3,  title: "Bronchiolitis — 4mo infant, wheeze, tachycardia, SpO2 92%", tags: ["Respiratory","Infectious Disease"], tasks: ["Hx","PE","Dx","Mx"] },
      { number: 4,  title: "Meningococcal disease — 6yo, non-blanching rash, fever, stiff neck", tags: ["Infectious Disease","Emergency"], tasks: ["Dx","Emergency Mx"] },
      { number: 5,  title: "Autism spectrum disorder — 3yo, no words, poor eye contact, repetitive behaviours", tags: ["Development","Neurology"], tasks: ["Hx","Dx","Counselling"] },
      { number: 6,  title: "Kawasaki disease — 2yo, fever >5 days, cracked lips, strawberry tongue, rash", tags: ["Cardiovascular","Immunology"], tasks: ["Dx","Ix","Mx"] },
      { number: 7,  title: "Intussusception — 10mo, intermittent screaming, redcurrant jelly stool", tags: ["Surgery","Gastroenterology","Emergency"], tasks: ["Dx","Ix","Mx"] },
      { number: 8,  title: "Childhood asthma — exercise-triggered wheeze, management plan", tags: ["Respiratory"], tasks: ["Hx","Dx","Mx","Counselling"] },
      { number: 9,  title: "Type 1 DM — new presentation 8yo, polyuria, polydipsia, weight loss", tags: ["Endocrinology"], tasks: ["Hx","Dx","Mx"] },
      { number: 10, title: "Child abuse — 2yo bruising in unusual sites, inconsistent history", tags: ["Child Protection","Social"], tasks: ["Hx","PE","Mx","Reporting"] },
      { number: 11, title: "Developmental delay — 18mo, not walking, global delay", tags: ["Development","Neurology"], tasks: ["Hx","PE","Ix","Dx"] },
      { number: 12, title: "Pyloric stenosis — 4wk male, projectile vomiting, olive-shaped mass", tags: ["Surgery","Gastroenterology"], tasks: ["Dx","Ix","Mx"] },
    ],
  },

  // ── COUNSELLING ─────────────────────────────────────────────────────────────
  {
    month: "2025",
    year: 2025,
    category: "Counselling",
    items: [
      { number: 1,  title: "Breaking bad news — new cancer diagnosis", tags: ["Oncology","Communication"], tasks: ["SPIKES framework"] },
      { number: 2,  title: "Consent for procedure — informed consent, risks/benefits", tags: ["Ethics","Communication"], tasks: ["Consent","Counselling"] },
      { number: 3,  title: "Smoking cessation — 5As framework, NRT options", tags: ["Preventive","Respiratory"], tasks: ["5As","Counselling"] },
      { number: 4,  title: "Alcohol reduction — FRAMES, brief intervention", tags: ["Alcohol","Preventive"], tasks: ["Brief intervention"] },
      { number: 5,  title: "Contraception counselling — options, reliability, SE", tags: ["Gynaecology","Preventive"], tasks: ["Counselling"] },
      { number: 6,  title: "Pre-pregnancy counselling — folic acid, medications review, rubella", tags: ["Obstetrics","Preventive"], tasks: ["Counselling"] },
      { number: 7,  title: "STI counselling — HIV result, partner notification", tags: ["Infectious Disease","Communication"], tasks: ["Counselling","Partner notification"] },
      { number: 8,  title: "Advance care planning — elderly patient, goals of care", tags: ["Palliative","Ethics"], tasks: ["ACP discussion"] },
      { number: 9,  title: "Childhood immunisation — parents refusing vaccines", tags: ["Paediatrics","Preventive"], tasks: ["Counselling","Evidence"] },
      { number: 10, title: "Domestic violence disclosure — safety planning", tags: ["Social","Communication"], tasks: ["Mx","Safety plan"] },
    ],
  },
];

export type RecallCategory = RecallMonth["category"];
