export interface Scenario {
  id: number;
  title: string;
  category: string;
  difficulty: "Easy" | "Medium" | "Hard";
  patientProfile: string;
  chiefComplaint: string;
  underlyingDiagnosis: string;
  redFlags: string[];
  murtaghPearls: string[];
  amcMarkingCriteria: string[];
  redBookGuidelines?: string[];
}

export const scenarios: Scenario[] = [
  {
    id: 1,
    title: "Chest Pain",
    category: "Cardiovascular",
    difficulty: "Medium",
    patientProfile: "55-year-old male, smoker, hypertensive",
    chiefComplaint: "central crushing chest pain radiating to left arm for 2 hours",
    underlyingDiagnosis: "Acute MI (STEMI)",
    redFlags: ["radiation to arm/jaw", "diaphoresis", "nausea", "hypotension"],
    murtaghPearls: [
      "Use SOCRATES for pain assessment",
      "Consider aortic dissection if tearing pain radiates to back",
      "ECG is essential — do not delay",
    ],
    amcMarkingCriteria: [
      "Appropriate history taking (SOCRATES)",
      "Identifies red flags",
      "Requests ECG and troponin",
      "Initiates emergency management: aspirin, GTN, oxygen",
      "Communicates clearly with patient",
    ],
    redBookGuidelines: [
      "Cardiovascular risk assessment in men >45",
      "Smoking cessation counselling",
    ],
  },
  {
    id: 2,
    title: "Shortness of Breath",
    category: "Respiratory",
    difficulty: "Hard",
    patientProfile: "68-year-old female with long-term smoking history",
    chiefComplaint: "worsening breathlessness over 3 days with productive cough",
    underlyingDiagnosis: "Acute exacerbation of COPD",
    redFlags: ["cyanosis", "accessory muscle use", "SpO2 < 88%", "altered consciousness"],
    murtaghPearls: [
      "Differentiate cardiac vs respiratory cause",
      "Assess severity: RR, SpO2, speech",
      "Steroid and bronchodilator are key",
    ],
    amcMarkingCriteria: [
      "Elicits smoking history and baseline function",
      "Identifies acute-on-chronic deterioration",
      "Requests CXR, spirometry review, ABG if severe",
      "Prescribes bronchodilators and systemic steroids",
    ],
  },
  {
    id: 3,
    title: "Abdominal Pain",
    category: "Gastroenterology",
    difficulty: "Medium",
    patientProfile: "32-year-old female",
    chiefComplaint: "right lower quadrant pain for 18 hours, nausea, low-grade fever",
    underlyingDiagnosis: "Appendicitis",
    redFlags: ["guarding", "rebound tenderness", "fever > 38.5", "peritonism"],
    murtaghPearls: [
      "Rovsing sign, psoas sign, obturator sign",
      "Always consider ectopic pregnancy in females of reproductive age",
      "Alvarado score for risk stratification",
    ],
    amcMarkingCriteria: [
      "Takes menstrual and sexual history",
      "Examines for peritoneal signs",
      "Orders FBC, CRP, beta-hCG, USS",
      "Surgical referral if high suspicion",
    ],
  },
  {
    id: 4,
    title: "Headache",
    category: "Neurology",
    difficulty: "Easy",
    patientProfile: "29-year-old male",
    chiefComplaint: "sudden severe headache 'worst of my life' with neck stiffness",
    underlyingDiagnosis: "Subarachnoid haemorrhage",
    redFlags: ["thunderclap onset", "neck stiffness", "photophobia", "vomiting", "LOC"],
    murtaghPearls: [
      "Thunderclap headache = SAH until proven otherwise",
      "CT head then LP if CT negative",
      "Kernig and Brudzinski signs",
    ],
    amcMarkingCriteria: [
      "Recognises thunderclap onset",
      "Assesses meningism",
      "Emergency referral/imaging",
      "Does not give analgesia and send home without investigation",
    ],
  },
  {
    id: 5,
    title: "Diabetes Follow-up",
    category: "Endocrinology",
    difficulty: "Easy",
    patientProfile: "58-year-old male, known T2DM on metformin",
    chiefComplaint: "routine follow-up, HbA1c 9.2%, feels 'a bit tired'",
    underlyingDiagnosis: "Poorly controlled T2DM with potential complications",
    redFlags: ["polyuria", "polydipsia", "weight loss", "foot changes", "vision changes"],
    murtaghPearls: [
      "Assess complications: retinopathy, nephropathy, neuropathy, feet",
      "Check BP, lipids, eGFR, urine ACR",
      "Motivational interviewing for lifestyle",
    ],
    amcMarkingCriteria: [
      "Reviews current medications and adherence",
      "Performs complication screen",
      "Adjusts treatment (consider SGLT2i or GLP-1)",
      "RACGP Red Book preventive activities",
      "Addresses cardiovascular risk",
    ],
    redBookGuidelines: [
      "Annual HbA1c, lipids, eGFR, urine ACR",
      "Biennial retinal screening",
      "Annual foot examination",
    ],
  },
  {
    id: 6,
    title: "Postnatal Depression",
    category: "Psychiatry",
    difficulty: "Hard",
    patientProfile: "28-year-old female, 6 weeks postpartum, first baby",
    chiefComplaint: "feels overwhelmed, not bonding with baby, tearful most days",
    underlyingDiagnosis: "Postnatal depression",
    redFlags: ["thoughts of harming self or baby", "psychosis", "severe functional impairment"],
    murtaghPearls: [
      "Use Edinburgh Postnatal Depression Scale (EPDS)",
      "Distinguish baby blues (< 2 weeks) vs PND vs postpartum psychosis",
      "Safety assessment is paramount",
    ],
    amcMarkingCriteria: [
      "Non-judgmental, empathic approach",
      "Administers or references EPDS",
      "Assesses safety (self-harm, harm to baby)",
      "Discusses treatment: psychotherapy, medication if needed",
      "Involves support network, GP follow-up plan",
    ],
    redBookGuidelines: [
      "EPDS screening at 6 weeks and 6 months postpartum",
      "Assess social support and domestic violence",
    ],
  },
  {
    id: 7,
    title: "Breaking Bad News",
    category: "Communication Skills",
    difficulty: "Hard",
    patientProfile: "36-year-old male office worker, joint pain and swelling for 3 months",
    chiefComplaint: "I've come for my blood test results — my joints have been so painful and swollen",
    underlyingDiagnosis: "Rheumatoid Arthritis (confirmed on bloods: elevated CRP, ESR, positive RF and anti-CCP)",
    redFlags: [
      "Bilateral symmetrical joint swelling",
      "Morning stiffness >1 hour",
      "Elevated inflammatory markers",
      "Positive rheumatoid factor",
    ],
    murtaghPearls: [
      "RA is the most common inflammatory arthritis; early DMARD therapy prevents joint destruction",
      "Use SPIKES framework for breaking bad news",
      "Check ICE (Ideas, Concerns, Expectations) before delivering results",
      "RA affects 1% of population; peak onset 40-60 but can occur at any age",
    ],
    amcMarkingCriteria: [
      "Introduces self, establishes rapport",
      "Elicits patient's current understanding and concerns",
      "Uses a warning shot before delivering diagnosis",
      "Explains diagnosis clearly in lay terms — autoimmune attack on joint linings",
      "Does not overwhelm with information in one sitting",
      "Addresses emotional response with empathy and pauses",
      "Explains treatment options: DMARDs, NSAIDs, physiotherapy",
      "Arranges follow-up with rheumatologist",
      "Provides written information or leaflet",
      "Checks patient understanding at end",
    ],
    redBookGuidelines: [
      "RACGP: refer to rheumatologist within 4-6 weeks of suspected RA",
      "Early treatment with DMARDs (methotrexate) reduces joint damage",
    ],
  },
  {
    id: 8,
    title: "Angry Patient",
    category: "Communication Skills",
    difficulty: "Medium",
    patientProfile: "45-year-old male, waiting 2 hours in ED with wrist pain after a fall",
    chiefComplaint: "I've been waiting here for two hours! This is ridiculous. I need to see a doctor NOW.",
    underlyingDiagnosis: "Distal radius fracture (Colles fracture) — but patient is understandably frustrated by wait",
    redFlags: [
      "Neurovascular compromise to hand (rare but serious)",
      "Open fracture",
      "High-energy mechanism suggesting other injuries",
    ],
    murtaghPearls: [
      "De-escalation: acknowledge feelings first, never be confrontational",
      "LEAP framework: Listen, Empathise, Apologise, Plan",
      "Never match the patient's anger — remain calm and non-defensive",
      "Triage explains wait: sicker patients seen first",
    ],
    amcMarkingCriteria: [
      "Introduces self by name and role",
      "Acknowledges patient's frustration without being dismissive",
      "Maintains calm, open body language throughout",
      "Explains triage system (patients seen by clinical need, not arrival time)",
      "Does not argue or become defensive",
      "Offers immediate pain relief as a concrete action",
      "Gives realistic timeframe and checks understanding",
      "Resolves to a mutually agreed plan",
      "Checks if patient has any other concerns",
    ],
  },
  {
    id: 9,
    title: "Warfarin Counselling",
    category: "Cardiovascular",
    difficulty: "Medium",
    patientProfile: "62-year-old woman, newly diagnosed atrial fibrillation, cardiologist has recommended warfarin",
    chiefComplaint: "The specialist said I need to take warfarin — I'm worried about the bleeding risks",
    underlyingDiagnosis: "Atrial fibrillation with CHA2DS2-VASc ≥2, requiring anticoagulation",
    redFlags: [
      "Signs of over-anticoagulation: prolonged bleeding, haematuria, haemoptysis",
      "Drug interactions (NSAIDs, antibiotics)",
      "Pregnancy — warfarin contraindicated in first trimester",
    ],
    murtaghPearls: [
      "Warfarin has narrow therapeutic index — INR target 2-3 for AF",
      "Check suitability: pregnancy, recent surgery, active bleeding, peptic ulcer",
      "Key interactions: NSAIDs (avoid), paracetamol (safe)",
      "Vitamin K foods affect INR — advise consistency not avoidance",
    ],
    amcMarkingCriteria: [
      "Elicits current understanding of warfarin and concerns (ICE)",
      "Confirms indication: AF with stroke risk factors",
      "Checks contraindications: pregnancy, bleeding history, peptic ulcer",
      "Explains mechanism: blood thinner to prevent clot/stroke",
      "Explains side effects: bleeding, jaundice, alopecia",
      "Advises on INR monitoring schedule",
      "Advises on drug interactions (avoid NSAIDs, check with pharmacist)",
      "Advises on alcohol, diet (consistent vitamin K intake)",
      "Explains warfarin booklet and when to seek urgent help",
      "Recommends MedicAlert bracelet for long-term use",
      "Advises dentist notification before procedures",
    ],
    redBookGuidelines: [
      "RACGP: warfarin with INR 2-3 for non-valvular AF; DOACs now preferred in many patients",
    ],
  },
  {
    id: 10,
    title: "COPD Exacerbation",
    category: "Respiratory",
    difficulty: "Hard",
    patientProfile: "67-year-old male ex-coal miner, 40 pack-year smoker, previous COPD diagnosis",
    chiefComplaint: "I've been getting more and more short of breath over the past week, and my cough has gotten much worse with green phlegm",
    underlyingDiagnosis: "Acute exacerbation of COPD (infective trigger — Haemophilus influenzae most common)",
    redFlags: [
      "Cyanosis",
      "Confusion or reduced consciousness (hypercapnic encephalopathy)",
      "Inability to complete sentences",
      "Use of accessory muscles",
      "Silent chest or paradoxical breathing",
      "SpO2 <88% on room air",
    ],
    murtaghPearls: [
      "COPD exacerbation: key triggers are infection (50%), air pollution, non-compliance with medication",
      "Target SpO2 88-92% in known COPD — avoid over-oxygenation (hypercapnic drive)",
      "Murtagh: occupational history vital — coal, asbestos, grain dust, isocyanates",
      "FEV1/FVC <0.7 post-bronchodilator confirms obstruction",
    ],
    amcMarkingCriteria: [
      "Takes full dyspnoea history using ONE RESPS mnemonic",
      "Elicits occupational history (coal mining, asbestos exposure)",
      "Quantifies smoking history in pack-years",
      "Asks about orthopnoea, PND, ankle swelling (heart failure differential)",
      "Enquires about previous admissions, home oxygen, nebulisers",
      "Identifies infective exacerbation: purulent sputum, fever",
      "Appropriate differentials: COPD exacerbation, pneumonia, heart failure, PE",
      "Management: controlled oxygen, bronchodilators, steroids, antibiotics",
      "Checks medication compliance and inhaler technique",
    ],
    redBookGuidelines: [
      "RACGP GOLD guidelines: exacerbation = increase in dyspnoea, cough or sputum beyond day-to-day variation",
      "Target SpO2 88-92% in exacerbation",
    ],
  },
  {
    id: 11,
    title: "Breast Lump",
    category: "Surgery",
    difficulty: "Hard",
    patientProfile: "42-year-old female nurse, noticed a painless lump in her right breast 3 weeks ago",
    chiefComplaint: "I found a lump in my breast three weeks ago and I'm terrified it might be cancer",
    underlyingDiagnosis: "Suspicious breast lump — requires urgent triple assessment (clinical exam, imaging, biopsy) to exclude carcinoma",
    redFlags: [
      "Hard, irregular, fixed lump",
      "Skin changes: peau d'orange, dimpling, tethering",
      "Nipple discharge or inversion",
      "Axillary lymphadenopathy",
      "BRCA1/2 family history",
    ],
    murtaghPearls: [
      "Triple assessment: clinical examination + imaging (USS/mammogram) + biopsy (FNA/core)",
      "Most common causes of breast lump by age: <35 fibroadenoma; 35-55 fibrocystic; >50 carcinoma",
      "Pain does NOT exclude malignancy",
      "Murtagh: any discrete breast lump in a woman >35 must be presumed malignant until proven otherwise",
    ],
    amcMarkingCriteria: [
      "Acknowledges patient's anxiety with empathy before history",
      "Elicits lump characteristics: duration, size change, pain, discharge",
      "Asks about skin or nipple changes",
      "Takes full menstrual and reproductive history (OCP, HRT, breastfeeding)",
      "Establishes family history of breast or ovarian cancer",
      "Examines systematically (or describes examination approach)",
      "Explains triple assessment process clearly",
      "Provides urgent referral to breast clinic (within 2 weeks if suspicious)",
      "Does not falsely reassure patient but avoids catastrophising",
    ],
    redBookGuidelines: [
      "RACGP: any new discrete breast lump warrants urgent referral for triple assessment",
      "Breast cancer screening: mammography 2-yearly for women aged 50-74",
    ],
  },
  {
    id: 12,
    title: "Epilepsy and Pregnancy",
    category: "Neurology",
    difficulty: "Hard",
    patientProfile: "28-year-old woman, known grand mal epilepsy on carbamazepine, recently married and wishes to start a family",
    chiefComplaint: "I've been epileptic since I was 16 and I really want to start a family — I need to know what the risks are",
    underlyingDiagnosis: "Pre-conception counselling for epilepsy — risks of anti-epileptic drugs vs uncontrolled seizures in pregnancy",
    redFlags: [
      "Status epilepticus in pregnancy",
      "Sodium valproate — highest teratogenic risk (neural tube, cognitive)",
      "Stopping medication without advice — risk of status epilepticus",
      "Vitamin K deficiency in neonate",
    ],
    murtaghPearls: [
      "Valproate: highest teratogen risk — avoid in pregnancy if possible",
      "Carbamazepine: 1% risk spina bifida; lamotrigine preferred in pregnancy",
      "Folate 5mg daily: 3 months pre-conception and first trimester (higher dose than general population)",
      "Seizures in pregnancy risk: placental abruption, miscarriage, fetal hypoxia",
    ],
    amcMarkingCriteria: [
      "Elicits seizure type, frequency, and last seizure date",
      "Establishes which anti-epileptic medication and dose",
      "Explains risks of uncontrolled seizures in pregnancy (miscarriage, fetal hypoxia, trauma)",
      "Explains teratogenic risks of anti-epileptic medication (dose-dependent, polytherapy worse)",
      "Specifically addresses carbamazepine: 1% spina bifida risk",
      "Advises high-dose folate 5mg pre-conception and first trimester",
      "Advises aim to reduce to single agent at lowest dose",
      "Explains need for referral to neurologist before conception",
      "Explains multidisciplinary care: neurologist, obstetrician, midwife",
      "Advises Vitamin K supplementation in late pregnancy",
      "Mentions 10% risk child may develop epilepsy",
      "Confirms safe to breastfeed on anti-epileptics",
    ],
  },
  {
    id: 13,
    title: "Loss of Consciousness",
    category: "Neurology",
    difficulty: "Medium",
    patientProfile: "24-year-old male university student, collapsed and lost consciousness briefly during a lecture yesterday",
    chiefComplaint: "I blacked out yesterday in my lecture — I came around on the floor, my friends said I was shaking",
    underlyingDiagnosis: "First seizure — possible epilepsy vs. syncope; requires urgent investigation",
    redFlags: [
      "Tongue biting",
      "Post-ictal confusion or drowsiness",
      "Loss of bladder or bowel control during episode",
      "Prolonged unconsciousness >5 minutes",
      "Focal neurological deficit on recovery",
      "Family history of epilepsy or sudden cardiac death",
    ],
    murtaghPearls: [
      "Differentiate seizure vs syncope: prodrome, duration, recovery, post-ictal phase",
      "Seizure: abrupt onset, no prodrome, post-ictal confusion, tongue bite, incontinence",
      "Syncope: prodrome (nausea, sweating, tunnel vision), brief LOC, rapid recovery",
      "First seizure: full neurological history, MRI brain, EEG, bloods (glucose, electrolytes, FBC)",
    ],
    amcMarkingCriteria: [
      "Asks about prodrome: warning symptoms, aura",
      "Characterises the episode: duration, witness account of movements",
      "Asks specifically about tongue biting, incontinence",
      "Asks about post-ictal phase: confusion, headache, fatigue",
      "Takes previous medical history: febrile convulsions, head injury, meningitis",
      "Takes family history of epilepsy or cardiac conditions",
      "Asks about alcohol, drug use, sleep deprivation (precipitants)",
      "Advises driving restrictions (must not drive until cleared)",
      "Explains need for urgent investigations: MRI, EEG, ECG, bloods",
      "Refers to neurologist for first seizure assessment",
    ],
  },
  {
    id: 14,
    title: "Hypertension in Pregnancy",
    category: "Obstetrics",
    difficulty: "Hard",
    patientProfile: "32-year-old woman, 34 weeks pregnant, presenting with headache and swollen ankles",
    chiefComplaint: "I'm 34 weeks pregnant and I've had a terrible headache for two days, my ankles are really swollen, and I've been getting some spots in my vision",
    underlyingDiagnosis: "Pre-eclampsia (BP >140/90 + proteinuria at ≥20 weeks) — urgent assessment required",
    redFlags: [
      "Severe headache unresponsive to paracetamol",
      "Visual disturbances (scotoma, flashing lights)",
      "Epigastric pain (hepatic involvement)",
      "Rapidly worsening oedema",
      "BP ≥160/110 — severe pre-eclampsia",
      "Reduced fetal movements",
      "Eclampsia — seizures",
    ],
    murtaghPearls: [
      "Pre-eclampsia: BP ≥140/90 + proteinuria (≥300mg/24h or PCR ≥30) after 20 weeks",
      "Triad: hypertension, proteinuria, oedema — only 2 of 3 needed for diagnosis",
      "HELLP syndrome: haemolysis, elevated liver enzymes, low platelets — life-threatening",
      "MgSO4 for seizure prophylaxis in severe pre-eclampsia; antihypertensives: labetalol, nifedipine, hydralazine",
    ],
    amcMarkingCriteria: [
      "Takes thorough obstetric history: gestational age, previous pregnancies",
      "Elicits all features of pre-eclampsia: headache, visual symptoms, epigastric pain, oedema",
      "Asks about fetal movements",
      "Recognises urgency — this is a medical emergency requiring immediate assessment",
      "Checks BP and requests urinalysis/proteinuria",
      "Orders appropriate bloods: FBC, LFTs, renal function, coagulation, uric acid",
      "Monitors fetal wellbeing: CTG, growth scan",
      "Explains diagnosis and risks to mother and baby",
      "Discusses management: antihypertensives, MgSO4 if severe, likely delivery planning",
      "Arranges immediate hospital admission",
    ],
    redBookGuidelines: [
      "RACGP: any pregnant woman with BP ≥140/90 after 20 weeks requires urgent assessment",
      "Aspirin 100mg from 12 weeks for high-risk women to prevent pre-eclampsia",
    ],
  },
];

export function getScenario(id: number): Scenario | undefined {
  return scenarios.find((s) => s.id === id);
}
