-- Personal flashcard library — cards the user authored, imported from
-- Anki, or generated from their own notes via the AI generator. Decks
-- shipped with the platform (cardiologyFlashcards, etc.) stay in
-- packages/content and are NOT mirrored here; this table is for the
-- user's *own* corpus, scoped per-user with RLS.
--
-- Source values:
--   'manual'    — user typed it in
--   'ai_notes'  — generated by /api/flashcards/generate from pasted notes
--   'ai_mcq'    — generated from an MCQ explanation (future)
--   'anki_apkg' — parsed from an uploaded .apkg
--
-- FSRS scheduling lives in flashcard_reviews (migration 043). Card ids
-- there are text columns; when a user_flashcards row needs an FSRS state
-- we use card_id = "uf-{id}" so the namespace can't collide with the
-- packaged-deck ids ("fc-cardio-001", etc.).

create table if not exists public.user_flashcards (
  id                uuid        primary key default gen_random_uuid(),
  user_id           uuid        not null references auth.users(id) on delete cascade,
  source            text        not null default 'manual',
  source_deck_name  text,
  front_md          text        not null,
  back_md           text,
  cloze_text        text,
  tags              text[],
  media             jsonb,
  card_type         text        not null default 'basic' check (card_type in ('basic','cloze')),
  created_at        timestamptz not null default now()
);

create index if not exists user_flashcards_user_created_idx
  on public.user_flashcards (user_id, created_at desc);

create index if not exists user_flashcards_user_source_idx
  on public.user_flashcards (user_id, source);

alter table public.user_flashcards enable row level security;

drop policy if exists "users select own user_flashcards" on public.user_flashcards;
drop policy if exists "users insert own user_flashcards" on public.user_flashcards;
drop policy if exists "users update own user_flashcards" on public.user_flashcards;
drop policy if exists "users delete own user_flashcards" on public.user_flashcards;

create policy "users select own user_flashcards"
  on public.user_flashcards for select using (auth.uid() = user_id);
create policy "users insert own user_flashcards"
  on public.user_flashcards for insert with check (auth.uid() = user_id);
create policy "users update own user_flashcards"
  on public.user_flashcards for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own user_flashcards"
  on public.user_flashcards for delete using (auth.uid() = user_id);
